openmm/openmm

wrappers/python/simtk/openmm/app/amberprmtopfile.py, wrappers/python/simtk/openmm/app/internal/amber_file_parser.py
This addresses the (very old and very stale) issue #101.  The inpcrd file parsers were already updated to rigorously conform to the file spec in #461, but using CHAMBER-style topology files was still not explicitly caught (which meant, more than likely, that an obscure exception would be thrown or, worse, the CHARMM-specific pieces of the force field would be discarded and the simulation would "run").
There is code in ParmEd to properly parse CHAMBER-style topology files and create an OpenMM `System` from it (correctly).  It also has rigorously correct Fortran format string handling as well as a C-accelerated reading routine, so it should be quite efficient when reading large files.
I also switched the parsing loop to use a context manager -- a bit safer when it comes to properly handling …
=> Add a check and raise an exception if someone tries to use a CHAMBER-style prmtop

wrappers/python/src/swig_doxygen/swig_lib/python/pythoncode.i
Current behavior:
```
In [4]: sys.version_info
Out[4]: sys.version_info(major=3, minor=4, micro=2, releaselevel='final', serial=0)
In [5]: simtk.openmm.stripUnits(b'Hello World')
Out[5]: (72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100)
```
=> stripUnits behavior with bytes

platforms/cuda/tests/TestCudaCustomCompoundBondForce.cpp, platforms/opencl/tests/TestOpenCLCustomCompoundBondForce.cpp, platforms/reference/src/SimTKReference/ReferenceCustomCompoundBondIxn.cpp, platforms/reference/tests/TestReferenceCustomCompoundBondForce.cpp
This bug affected CustomCompoundBondForce in the Reference and CPU platforms.  It occurred when the energy expression explicitly depended on the x, y, and z coordinates of an atom.  The coordinates of the wrong atom were being used for those variables.
=> Fixed bug in reference CustomCompoundBondForce

wrappers/python/simtk/openmm/__init__.py
#780 was slightly broken. The += on line 18 forgot to add another semicolon. This prepends the OpenMM stuff instead of appending it.
=> Fix for #780

platforms/cuda/src/kernels/langevin.cu, platforms/cuda/src/kernels/verlet.cu, platforms/opencl/src/kernels/langevin.cl, platforms/opencl/src/kernels/verlet.cl
The effect of this bug is a bit subtle.  It was still choosing the step size to reduce error, and lowering the error tolerance still affected the step size in the correct way.  But the contribution of each atom to the error was scale by sqrt(mass).  As a result, the step size was always set slightly smaller than it should have been.
This was only in the CUDA and OpenCL platforms.  The Reference and CPU platforms calculated it correctly (that is, following the equations in the manual).
=> Variable step size integrators were scaling the step size incorrectly

platforms/cpu/src/CpuKernels.cpp
In addition to checking the positions, it was also checking if the particle charges were nan.  That was generally harmless, except if the system didn't contain a NonbondedForce.  In that case, they would never have been set and could easily be nan.  This was causing TestCpuCustomNonbondedForce to fail.
=> Check for nan positions was being done incorrectly

libraries/lepton/include/lepton/windowsIncludes.h, libraries/lepton/src/CompiledExpression.cpp
The pragma to ignore 4251 already existed in windowsIncludes.h, and it works
when compiling lepton itself. However, when clients use lepton, they get this
warning. I think this is why @sherm1 put the define as shown here:
https://github.com/simbody/simbody/blob/master/SimTKcommon/include/SimTKcommon/internal/common.h#L168
(whether or not the shared library is being built or used).
=> Fixes vs2013 warnings 4251, 4267 in lepton.

plugins/amoeba/openmmapi/include/openmm/AmoebaStretchBendForce.h, plugins/amoeba/openmmapi/src/AmoebaStretchBendForce.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.h, plugins/amoeba/platforms/cuda/src/kernels/amoebaStretchBendForce.cu, plugins/amoeba/platforms/cuda/tests/TestCudaAmoebaStretchBendForce.cpp, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.cpp, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.h, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceStretchBendForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceStretchBendForce.h, plugins/amoeba/platforms/reference/tests/TestReferenceAmoebaStretchBendForce.cpp, plugins/amoeba/serialization/src/AmoebaStretchBendForceProxy.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaStretchBendForce.cpp, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/src/swig_doxygen/swigInputConfig.py
This should address #800.  All of the tests have been updated and continue to pass (including the CUDA test on my machine).  Also, the *old* versions of the test (without the updated energy expression using separate force constants) passed as well, showing that the energies and forces have not *changed* as a result of this PR.
A few notes:
- I tried to maintain as much backwards-compatibility as possible. So the `addStretchBend` and `setStretchBendParameters` functions were supplied with default values for k2 of -1 that results in k1 being used for k2.  However, `getStretchBendParameters` doesn't work this way, and overloading is not an option thanks to the C wrapper generator. This could be worked around if maintaining this backwards-compatibility is important, but it would be clumsy and …
=> Generalize Amoeba Stretch-Bend term

platforms/opencl/src/OpenCLContext.cpp
There was a bug in Nvidia's OpenCL that caused incorrect results on Maxwell GPUs.  It only affected the OpenCL platform, so not many people would have run into it.  A workaround was included in Folding@Home, but it never got ported back to OpenMM.  Also, the bug is fixed in the most recent drivers.
=> Workaround for Nvidia bug on Maxwell in CUDA 6

wrappers/python/simtk/openmm/app/internal/unitcell.py, wrappers/python/tests/TestUnitCell.py
This fixes a simple `NameError` in `unitcell.computeLengthsAndAngles` (it's been there since the beginning).  It also adds a set of tests for that module, and adds a function to reduce box vectors if you start with vectors, but not lengths and angles.
Note that because of the reduction, a round-trip between `computePeriodicBoxVectors` -> `computeLengthsAndAngles` does _not_ actually return the same lengths and angles you fed it necessarily.  However, a 2-cycle round-trip works (as you would expect, given that reduced vectors/lengths should be interconvertible without being changed).
=> Fix `unitcell.py`

openmmapi/include/openmm/State.h, openmmapi/src/State.cpp, serialization/src/StateProxy.cpp, serialization/tests/TestSerializeState.cpp
This is important if we want to support PNaCl, since enabling exceptions causes your code to run about half as fast.
=> Avoid throwing exceptions internally when serializing States

wrappers/python/simtk/openmm/app/internal/pdbstructure.py, wrappers/python/tests/TestPdbFile.py
This is the fix for https://github.com/pandegroup/pdbfixer/issues/81.
=> PdbStructure handles byte streams correctly in Python 3

wrappers/python/simtk/openmm/app/dcdfile.py, wrappers/python/tests/TestAmberPrmtopFile.py
Here is the driver code:
```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout
temperature = 50*kelvin
prmtop = AmberPrmtopFile('CO.prmtop')
inpcrd = AmberInpcrdFile('CO.inpcrd')
system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
system.addForce(MonteCarloBarostat(1.0 * atmospheres, temperature, 1))
integrator = LangevinIntegrator(temperature, 1/picosecond, 0.0001*picoseconds)
simulation = Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
simulation.reporters.append(PDBReporter('output.pdb', 1))
simulation.reporters.append(DCDReporter('output.dcd', 1)) …
```
=> Fixing multiple bugs in dcdfile / dcdreporter.

.travis.yml
This modifies the travis logic so that ctests only fail if they fail on retest, rather than triggering a travis failure if they fail the first time.  This was discussed in #850.
=> Modified travis logic to only fail if retested tests fail.

platforms/opencl/src/OpenCLKernels.cpp
This came up while testing Folding@Home core21.  It caused forces to sometimes be incorrect on Maxwell devices.
=> Fixed a race condition in OpenCL

platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/opencl/src/OpenCLIntegrationUtilities.cpp, platforms/opencl/tests/TestOpenCLVirtualSites.cpp, platforms/reference/include/ReferenceCCMAAlgorithm.h, platforms/reference/src/SimTKReference/ReferenceCCMAAlgorithm.cpp, platforms/reference/src/SimTKReference/ReferenceConstraints.cpp
This reduces the context creation time when using constraints=allbonds.  It also eliminates some duplicated code.
=> Parallelized extraction of inverse matrix for CCMA

platforms/opencl/include/OpenCLFFT3D.h, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLFFT3D.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/fft.cl, platforms/opencl/src/kernels/fftR2C.cl, platforms/opencl/src/kernels/pme.cl, platforms/opencl/tests/TestOpenCLFFT.cpp
When performing a real to complex FFT, it only stores half of the symmetric output matrix.  This is the same output format used by FFTW and cuFFT.  It saves a little memory bandwidth.
=> OpenCL FFT stores only non-redundant elements

wrappers/python/src/swig_doxygen/swig_lib/python/features.i
See swig/swig#387 for a discussion.  It would actually be nice to *not* set the
"compactdefaultargs" feature globally, since that would allow us to actually see
the real API at the Python level the same as you would see by looking at the C++
header files. But this is the only way to support both SWIG 2 and SWIG 3 easily
and avoid a lot of retooling for the SWIG input code generator.
=> Fix SWIG 3 support for the Python wrappers.

wrappers/python/simtk/openmm/app/gromacstopfile.py
Virtual sites are never created by the OpenMM system, and their information is
not parsed from the Gromacs topology file. For now just throw an exception
rather than let them run, since TIP4Pew behaves *very* strangely...
=> Raise exception when processing Gromacs molecule with virtual sites

wrappers/python/simtk/openmm/app/gromacstopfile.py
This was actually fully supported already, since it parsed pairtypes and
assigned the exception parameters correctly from there. All this does is throw
an exception when pair parameters are not defined and gen-pairs=no.
=> support gen-pairs=no in Gromacs

wrappers/python/simtk/openmm/app/internal/amber_file_parser.py
Due to a bug that was uncovered in mdtraj with scipy's NetCDF implementation
regarding mmapping, scipy started issuing the following warning if any NetCDF
variable objects had references remaining after closing the file:
/.../lib/python2.7/site-packages/scipy/io/netcdf.py:287:
RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when
netcdf_variables or arrays referring to its data still exist. All data arrays
obtained from such files refer directly to data on disk, and must be copied
before the file can be cleanly closed. (See netcdf_file docstring for more
information on mmap.)
We were already copying data to avoid segfaults on some scipy versions, but
there were still references to variables that went out of scope shortly after
the NetCDF file was closed.  Simply deleting …
=> Eliminate scipy RuntimeWarning when reading NetCDF restart files

cmake_modules/FindOpenCL.cmake
Useful when cuda is not installed in the default location.
=> Look in cuda dir for opencl headers

.travis.yml
This attempts to address #964 by having travis do both static and dynamic library builds.
Replacement for PR #966 which I screwed up.
=> Add travis build matrix for static and dynamic builds

wrappers/python/simtk/openmm/app/simulation.py
This fixes #962.  The error occurred when a reporter was getting called very frequently (every 10 or fewer time steps).
=> Fixed a bug in runForClockTime()

docs-source/usersguide/library.rst, wrappers/python/simtk/unit/basedimension.py, wrappers/python/simtk/unit/baseunit.py, wrappers/python/simtk/unit/constants.py, wrappers/python/simtk/unit/mymatrix.py, wrappers/python/simtk/unit/prefix.py, wrappers/python/simtk/unit/quantity.py, wrappers/python/simtk/unit/standard_dimensions.py, wrappers/python/simtk/unit/unit.py, wrappers/python/simtk/unit/unit_definitions.py, wrappers/python/simtk/unit/unit_math.py, wrappers/python/simtk/unit/unit_operators.py, wrappers/python/tests/TestUnits.py
The main thing that's done here is that numpy arrays can be given units via the
`*` operator, rather than relying on the Quantity constructor
e.g.,
```Python
>>> import numpy as np
>>> np.zeros(10) * u.angstroms
Quantity(value=array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), unit=angstrom)
```
yay!
Still needs a test
=> A large number of unit cleanups and fix numpy wart

CMakeLists.txt, cmake_modules/FindOpenCL.cmake, libraries/pthreads/include/pthread.h
1. Compiling with x64 VS2010 compilers, I got an error with two `#defines` already having been defined in `pthreads.h`.
2. Extend #948 to search for other usual suspects paths for OpenCL. This isn't strictly necessary, but it smooths things out a little.
=> Compiling on Windows

olla/include/openmm/Platform.h, olla/src/Platform.cpp, wrappers/generateWrappers.py, wrappers/python/src/swig_doxygen/swigInputConfig.py
When debugging installations of the OpenMM OpenCL/CUDA platforms, the general error message is just 'There is no registered platform named CUDA', without any information about how to debug the problem. Usually it's caused by `LD_LIBRARY_PATH` not being set correctly or similar, and the first thing I always do with people is run `ldd` on the `libOpenMMCUDA.so` library, but that's not something they'd think to do themselves without knowledge of the OpenMM plugin architecture and the linker.
This PR adds a new static method to `Platform`, `getLoadFailures`, that returns a vector/tuple of strings containing the errors produced by the last call to `loadPluginsFromDirectory` (which is called from python during the import process).
So, for example, you can do
```
import simtk.openmm as mm …
```
=> Record plugin load failures

CMakeLists.txt, wrappers/python/CMakeLists.txt
re #1007, swig 2.0.4 was the oldest version of swig which produced wrappers that successfully compiled against python 3.4.
=> Swig cmake version check

platforms/cpu/CMakeLists.txt
=> Mark clang 3.6 as unsupported for building CPU platform in cmake

docs-source/DoxyfileC++.in
This is a cleanup to the C++ API docs.  They were including lots of internal classes that weren't meant to be part of the public API.
=> Omit internal directories from API docs

platforms/cuda/src/CudaParameterSet.cpp, platforms/opencl/src/OpenCLParameterSet.cpp
This caused a link error on Windows if you tried to compile a plugin that used CudaParameterSet or OpenCLParameterSet.
=> Added missing Windows imports

serialization/include/openmm/serialization/XmlSerializer.h, serialization/tests/TestSerializeSystem.cpp, wrappers/python/src/swig_doxygen/swig_lib/python/extend.i
Implements #542.  For Python, just call copy() or deepcopy() as usual.  For C++, call XmlSerializer::clone().
=> Implemented cloning of objects by serialization

README.md
This adds badges for the Jenkins builds of the `openmm-dev` conda package so we can tell when it breaks.
=> Added badges for Jenkins openmm-dev conda package builds.

wrappers/python/simtk/openmm/app/forcefield.py
There was a change in behavior between Python 2 and 3 that caused some scripts embedded in force field XML files to stop working: in particular, the one used for the CHARMM polarizable force field.  This change fixes the problem.  See https://simtk.org/forums/viewtopic.php?f=161&t=5888 for more details.
=> Fixed errors executing force field scripts on Python 3

wrappers/python/simtk/openmm/app/__init__.py, wrappers/python/simtk/openmm/app/pdbfile.py, wrappers/python/simtk/openmm/app/pdbreporter.py, wrappers/python/simtk/openmm/app/pdbxfile.py, wrappers/python/tests/TestPdbxFile.py
Add a `PDBxReporter` class that writes a PDBx/mmCIF trajectory just like the PDB reporter does.  The mmCIF writer implemented here is my own code and unlike the RCSB module does not require storing everything in memory before writing the file, so it can be written continuously and does not have to store stuff in memory.
Also adds two tests and makes sure that the CIF files generated can actually be read back in by `PDBxFile` correctly.
There are also a couple other fixes, like changing some implicit relative imports to explicit relative imports (part of the "single code-base for Py2 and Py3 without using `2to3`" -- still a lot to do on that regard, though).
The last change I made here was to have PDBReporter and PDBxReporter automatically call `flush()` on any file object opened for that …
=> Add PDBxReporter class

platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/nonbonded.cl, platforms/opencl/src/kernels/nonbonded_cpu.cl
Code from @peastman on my machine. Test results on OSX laptop (integrated GPU) cc #1089.
```
$ ctest
Test project /Users/rmcgibbo/projects/openmm/build
Start   1: TestReferenceAndersenThermostat
1/149 Test   #1: TestReferenceAndersenThermostat .................   Passed    0.40 sec
Start   2: TestReferenceBrownianIntegrator
2/149 Test   #2: TestReferenceBrownianIntegrator .................   Passed    0.20 sec
Start   3: TestReferenceCheckpoints
3/149 Test   #3: TestReferenceCheckpoints ........................   Passed    0.03 sec
Start   4: TestReferenceCMAPTorsionForce
4/149 Test   #4: TestReferenceCMAPTorsionForce ...................   Passed    0.03 sec
Start   5: TestReferenceCMMotionRemover
5/149 Test   #5: TestReferenceCMMotionRemover ....................   Passed    0.02 sec …
```
=> Fix OpenCL platform on low-end devices

wrappers/python/tests/TestAmberPrmtopFile.py, wrappers/python/tests/TestCheckpointReporter.py, wrappers/python/tests/TestPdbxFile.py
Fixes filesystem issues in 3 tests for windows, all related to closing files before deleting them or not having the same file simultaneously opened in both read and write mode.
=> Fix three tests on windows

wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i
https://github.com/pandegroup/openmm/pull/378 added this typemap, but when I refactored this code for the units stuff, I left it out.
This is necessary for loading checkpoint files in python3.
=> Add bytes typemap

platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLNonbondedUtilities.cpp
This is a workaround for simulating large systems on Windows.  If any kernel takes longer than 2 seconds, the OS resets the driver.  That was sometimes happening because there wouldn't initially be enough space for the neighbor list, so it would fall back to the O(n^2) algorithm for the first step.
=> Ensure neighbor list is large enough on first step

plugins/drude/platforms/reference/tests/TestReferenceDrudeLangevinIntegrator.cpp
I've noticed this one failing a lot recently.  The reference version runs fewer steps than the OpenCL or CUDA versions, but it was still using the same tolerance for the result.
=> Fixed an overly sensitive test case

platforms/cuda/src/CudaKernels.cpp
Now that there's an official CUDA release with the bug fixed, we can start using it again.  In my tests, this gives about a 10% speedup on the DHFR benchmark.
=> Reenabled cuFFT on CUDA 7.5 or later

plugins/amoeba/platforms/cuda/src/kernels/multipoleFixedField.cu
CUDA 7.5 seems to have introduced a bug that was causing AMOEBA GK to crash.  After a lot of experimenting, I came up with this change which makes the error go away.  No idea what the root problem is, though I'm pretty sure it's something in the compiler.
=> Workaround for bug in CUDA 7.5

devtools/forcefield-scripts/processAmberForceField.py
As discussed in #1054. In case of unknown vdW parameters `sigma, epsilon = 1, 0` will now be assigned; in case Amber forcefield specifies `sigma, epsilon = 0, 0` this will be changed to `1, 0`.
=> Resolve sigma = 0 problems from processAmberForceField

platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/nonbonded.cu, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/nonbonded.cl, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp
This includes two related changes.  First, I made it so that in mixed precision mode, the nonbonded kernel accumulates energy in double precision.  This leads to more accurate and more consistent energies.
Unfortunately, it also hurts performance.  The difference isn't huge, but it isn't negligible either, especially on consumer level GPUs with bad double precision performance.  So I also modified how it generates the nonbonded kernel.  It now can compile separate versions of the kernel for computing just forces, just energies, or both.  Since most of the time it's only computing forces, that avoids the added cost except when you actually query the energy.  It even helps in single precision mode, though in that case the difference is tiny.
So the upshot: energies in mixed precision are …
=> Changes to generating nonbonded kernels

devtools/forcefield-scripts/processTinkerForceField.py, plugins/amoeba/openmmapi/include/openmm/AmoebaAngleForce.h, plugins/amoeba/openmmapi/include/openmm/AmoebaOutOfPlaneBendForce.h, plugins/amoeba/openmmapi/src/AmoebaAngleForce.cpp, wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/src/swig_doxygen/swigInputConfig.py, wrappers/python/src/swig_doxygen/swig_lib/python/pythoncode.i, wrappers/python/tests/TestAPIUnits.py
This is the start of what I promised in #1031 
So far it just has the basic classes, but I still want to add:
=> Add a set of unit tests for unit handling in the core API.

wrappers/python/setup.py
Hard-code CC/CXX to clang/clang++ for Macs, since gcc/g++ will *not* work with
Anaconda, despite the fact that distutils will try to use them.  System Python,
homebrew, and MacPorts on Macs will always use clang, so this hack should always
work and fix issues with users that have GCC installed from MacPorts or homebrew
*and* Anaconda.
=> Fix very irritating behavior on some Mac systems.

wrappers/python/src/swig_doxygen/swigInputConfig.py, wrappers/python/tests/TestAPIUnits.py
Now that I have my head on straight, that is.
For some reason I was dividing by length instead of multiplying by it.  These are the correct units.  Not sure what I was doing originally.
=> Fix units of returned dipoles and quadrupoles from AmoebaMultipoleForce.

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/tests/TestCharmmFiles.py
Add relevant tests (that used to fail). This also fixes a subtle bug where
switching functions were not applied when NBFIXes were specified.
=> Add code supporting input with and without units for CharmmPsfFile.

platforms/cuda/src/CudaContext.cpp, platforms/opencl/src/OpenCLContext.cpp
The check is done during molecule reordering, which means it has two limitations.  First, it can take up to 100 time steps for the nan to be detected.  Second, the check isn't done if the simulation is run with no cutoff.  But it's still a big improvement, and doing the check there means that it adds negligible overhead.
=> Added checks for nan coordinates in CUDA and OpenCL

platforms/opencl/src/kernels/customCentroidBond.cl
This fixes the `TestOpenCLCustomCentroidBondForce` failures on the CPU OpenCL device I reported in https://github.com/pandegroup/openmm/pull/1208#issuecomment-150995439
Based on my undersanding of the [spec](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/barrier.html), and [some forum answers](https://software.intel.com/en-us/forums/opencl/topic/413956), the SYNC_WARPS barrier can't be in a conditional that's hit by only a subset of the threads.
=> Fix thread synchronization in customCentroidBond.cl

wrappers/python/src/swig_doxygen/swig_lib/python/extend.i, wrappers/python/tests/TestPickle.py
Intended to address #1190 
Adding a Python test to catch the deepcopy bug as a first step.
=> Fix force deepcopy bug

platforms/cuda/include/CudaContext.h, platforms/cuda/src/CudaContext.cpp
cc #1203, the idea is to check for failures in `cuCtxCreate` and try the next device if it fails, instead of throwing an exception.
=> Ensure context can be created when selecting CUDA device

wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i, wrappers/python/tests/TestSwigWrappers.py
The fix for #1214 is on line 472, because PyImport_AddModule gives a borrowed reference. The other decrefs are just fixing leaked references.
=> Fix segfault in swig wrappers

.travis.yml
For the CUDA build, the CUDA platform is compiled, but the
tests are not run (no GPU). For OS X, the OpenCL platform
is also compiled, but not tested (we skip Apple CPU OpenCL).
=> Add OS X and CUDA builds to Travis-CI config

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/pme.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/pme.cl
This fixes an error that very occassionally caused energies to be slightly off.  When using a separate stream for PME, it was possible for two different kernels to try to update energies at the same time, causing some of the contributions to be lost.  This mainly happens with CUDA 7.5.  There's no reason it couldn't happen with earlier releases, but something in that update seems to have made it more likely to happen.
=> Fixed a race condition in energy computation

wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
This is one piece of #1176.  It allows addExtraParticles() to work for multi-site ion models where several extra particles are connected to the atom (and to each other) by harmonic bonds.  @rafwiewiora and @jchodera could you take a look at this and see if it looks OK for your purposes?
=> addExtraParticles() can use bonds to select positions

docs-source/usersguide/application.rst, wrappers/python/simtk/openmm/app/data/spce.xml, wrappers/python/simtk/openmm/app/data/tip3p.xml, wrappers/python/simtk/openmm/app/data/tip4pew.xml, wrappers/python/simtk/openmm/app/data/tip5p.xml, wrappers/python/simtk/openmm/app/forcefield.py
Fixes #1187.  I also converted the XML files that were written by hand rather than generated from something else.
=> Residue templates can specify atoms by name instead of index

wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/src/swig_doxygen/swigInputConfig.py
apparently SWIG typemaps maps Python's list but not set with std::set. Instead, Python's `set` is mapped with `std::unordered_set`.
The original code of `swigInputBuilder.py` is kindly in a mess. Too much lines in a single method `writeMethods` which causes debug becomes difficult. Also there are a lot of warnings about [PEP8](https://www.python.org/dev/peps/pep-0008/).
A refactoring in the future may be a good idea. :)
=> Fix #1213 addInteractionGroup should accept `set` values as parameters

openmmapi/src/Context.cpp, plugins/rpmd/openmmapi/src/RPMDIntegrator.cpp, tests/TestEnforcePeriodicBox.cpp
This bug was introduced by #1234, which applied periodic boundary conditions incorrectly.  I believe this was probably the cause of #1255.
=> Fixed bug in getState() when enforcing periodic boundary conditions

wrappers/python/simtk/openmm/app/pdbfile.py
Same thing as: https://github.com/mdtraj/mdtraj/issues/977 https://github.com/mdtraj/mdtraj/pull/980 - pdbfile reads CONECT bonds from the first model currently, however due to CONECT being at the end of the file `PDBStructure` only reads CONECT data into the last model. 
I have 3 `nosetests` errors/fails locally:
```
======================================================================
ERROR: Tests the switching function option in AmberPrmtopFile
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/rafalpwiewiora/repos/openmm/wrappers/python/tests/TestAmberPrmtopFile.py", line 303, in testSwitchFunction
switchDistance=0.8*nanometer)
TypeError: createSystem() got an unexpected keyword argument 'switchDistance' …
```
=> Add CONECT bonds for multi-model pdb files 

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/pme.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/pme.cl
I realized that the fix in https://github.com/pandegroup/openmm/pull/1249 wasn't entirely correct.  There were situations in which the energy would still come out wrong, although they were pretty obscure situations.  In particular, all of the following would have needed to be true:
1. You were using PME.
2. You were on a GPU for which it doesn't use a separate stream for PME (so a non-NVIDIA GPU, or in the case of the CUDA platform, a GTX 980).
3. Your system included one of the following: GBSAOBCForce, CustomGBForce, CustomHBondForce, CustomCentroidBondForce, or CustomManyParticleForce.
4. That force was added to the System *before* the NonbondedForce.
So it's very unlikely anyone actually hit this problem.  But anyway, this fixes it.
=> Fixed error in energy computation

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/internal/amber_file_parser.py, wrappers/python/simtk/openmm/app/internal/customgbforces.py
This is part of making these classes a little more consistent and isolating the support functionality and parameter definition specific to these models inside these models themselves.  Right now, there is GB-model-specific code scattered in several places that can make it difficult to maintain.
The main thing that needs to happen now is for the radius assignment (that is currently in `charmmpsffile.py`) to be moved to `customgbforces.py`, and possibly correcting the handling in `amber_file_parser.py` to use the "correct" radii rather than the radii in the prmtop file.  That last one requires some discussion, probably.
That can be done either in another PR or added to this one.
=> Change functions in `customgbforces.py` to subclasses

wrappers/python/simtk/openmm/app/pdbfile.py
Here's the thinking:
1. I scanned the pdbx files of the PDB for all `metalc` bonds. 
2. By looking for bonds with atom.name == residue.name I identified large majority of the metals involved. 
3. Looking at the remaining bonds and checking what atom names started with, removing digits etc. a few further metals were identified. 
4. Wanting to change to coding conditions by element rather than names, I've scanned the whole PDB with both PDBFile and PDBxFile looking for atoms for which topology was returning element as None. Nicely and as you would expect, the only residues for which that happened were `{'ASX', 'GLX', 'UNK', 'UNL', 'UNX'}`. There will be no problems with missing elements. 
5. For final confirmation I had not missed any elements I looked at all elements found in `PDBxFile` …
=> PDBFile - change behavior of connectivity to metals to that of PDBxFile

.travis.yml
Addresses #1313.
A change in the way travis-ci handled the Legacy Precise infrastructure meant that restricted ubuntu packages (such as `fglrx`) were not available unless the `restricted` repository was explicitly added.
=> Fix travis following migration to legacy precise infrastructure.

wrappers/python/simtk/openmm/app/forcefield.py
Really we should move to using six and importing the iterator versions of dict
methods and range/zip from there, but for now just use "values" since using a
raw list doesn't seem like it will cause memory or performance problems here.
This fixes an `AttributeError` I got working with Python 3.
=> Python 3 does not have dict.itervalues

.travis.yml, docs-source/usersguide/application.rst
I just found I missed that I had added some syntax errors to the user guide because none of the travis branches are building/testing the guide.
This PR also builds the user guide in the same branch that the API docs are built, but the user guide currently isn't deployed anywhere.  Do we also want to push that to the S3 docs?
=> Also build the HTML user guide in travis

.travis.yml
I think the HTML user and dev guides were not being correctly moved into the directory uploaded to S3.
=> Fix push of dev user and developer guide HTMLs to S3

README.md
`openmm-dev` builds are now handled by https://github.com/omnia-md/conda-dev-recipes so Jenkins badges are no longer needed.
Reminder to @peastman that he is the only one that can add the AppVeyor badge (#1166)
=> Remove Jenkins badges from README.md

plugins/amoeba/platforms/cuda/src/kernels/amoebaInPlaneForce.cu, plugins/amoeba/platforms/cuda/src/kernels/amoebaStretchBendForce.cu
We still had some Amoeba simulations go off to NaNdyland, although it happened ~once per day rather than every couple minutes since #1327 was merged.  This is hoping that the in-plane angle force (or, less likely, the stretch-bend force) occasionally hits this singularity.
I'll test this out and see if it (hopefully) eliminates our Amoeba blowups.  If it does, I'll remove the [WIP] label.
=> More acos protections in Amoeba

plugins/amoeba/serialization/src/AmoebaAngleForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaBondForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaGeneralizedKirkwoodForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaInPlaneAngleForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaMultipoleForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaOutOfPlaneBendForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaPiTorsionForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaStretchBendForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaTorsionTorsionForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaVdwForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaWcaDispersionForceProxy.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaAngleForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaBondForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaGeneralizedKirkwoodForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaInPlaneAngleForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaMultipoleForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaOutOfPlaneBendForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaPiTorsionForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaStretchBendForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaTorsionTorsionForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaVdwForce.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaWcaDispersionForce.cpp
When AMOEBA forces were serialized, they weren't recording their force group.  This fixes that.
=> Record force group for AMOEBA forces

platforms/cuda/src/CudaKernels.cpp
CUFFT_COMPATIBILITY_NATIVE  is deprecated in CUDA 7.5.  And it wasn't really doing anything, since it only affects in-place transforms.
=> Removed calls to cufftSetCompatibilityMode()

wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
The `ionicStrength` argument was incorrectly being interpreted in determining how many ion pairs to add to the system [here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L522-L529).
Ionic strength is defined as
(via [wikipedia](https://en.wikipedia.org/wiki/Ionic_strength#Quantifying_ionic_strength)), but the factor of 1/2 had been omitted from the calculation.
For monovalent ions, the concentration of monovalent salt pairs should equal the ionic strength.
Later, we can generalize this to correctly compute the appropriate number of pairs for more complex salts as well, but we would need to extend the API or find some way to determine the charge on each ionic species.
=> Fix error in ionicStrength definition in Modeller.addSolvent()

README.md
* Update OpenMM URL to http://openmm.org
* Update docs URL to http://docs.openmm.org (previously they pointed to 6.0 docs)
* Update badges
Has anyone else noticed that the anaconda badge points to 6.2.dev0?  I fear the anaconda precedence thing might be accidentally thinking that 6.2.dev0 is the latest version---maybe we should delete just that version from anaconda cloud (but keep other actual releases)?
=> Update README.md badges and links

platforms/cuda/src/CudaPlatform.cpp, platforms/opencl/src/OpenCLPlatform.cpp
Specifying -1 as the device index for a test case was being interpreted as 0 instead of as "pick fastest device".
=> Fixed bug in selecting device index

platforms/cuda/include/CudaPlatform.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaPlatform.cpp, platforms/cuda/tests/TestCudaFFT3D.cpp, platforms/cuda/tests/TestCudaRandom.cpp, platforms/cuda/tests/TestCudaSort.cpp, platforms/opencl/include/OpenCLPlatform.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLPlatform.cpp, platforms/opencl/tests/TestOpenCLFFT.cpp, platforms/opencl/tests/TestOpenCLRandom.cpp, platforms/opencl/tests/TestOpenCLSort.cpp
If you set this property to "true", that guarantees the separate stream will not be used.  If you set it to "false" (the default), that does *not* guarantee that it *will* be used.  It still will decide for itself based on the GPU.  That's why I called the property "disable" instead of "use".
=> Created property for disabling the PME stream

.travis.yml
cc: #1282 #1357 
This requires updating from the travis `precise` (ubuntu 12.04) build environment to `trusty` (ubuntu 14.04) since the CUDA 7.5 distribution is not available via the same mechanism for 12.04:
https://docs.travis-ci.com/user/trusty-ci-environment/
=> Update travis to use CUDA 7.5

docs-source/usersguide/application.rst, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
This adds one more experimental convenience function `getMatchingTemplates(topology)` to `ForceField`.
This method returns the list of templates that match the corresponding residues in `topology`.
This is valuable in debugging which templates are matching which residues, as well as testing that changes to `Topology` were implemented correctly for transforming a residue into another recognized residue.
Example:
```python
pdb = PDBFile('input.pdb')
forcefield = ForceField('amber99sb.xml', 'tip3p.xml')
templates = forcefield.getMatchingTemplates(topology)
for (residue, template) in zip(pdb.topology.residues(), templates):
print "Residue %d %s matched template %s" % (residue.id, residue.name, template.name)
```
@juliebehr: Can you check if this API would work for you too?
=> Add a method for retrieving list of matching templates to ForceField

wrappers/python/simtk/openmm/app/simulation.py, wrappers/python/tests/TestSimulation.py
This replaces #872.
The actual changes are actually pretty small.  `Simulation` now accepts `None` for its topology argument, and falls back to `system.usesPeriodicBoundaryConditions` to determine the value of `enforceBox` in `Context.getState` calls.  It also accepts either a `System` or `str` input for its `system` and `Integrator` or `str` for its `integrator` arguments.  A string is interpreted as a XML file name in both cases.
The only reason I bothered with an alternate constructor is because `topology` is a *required* positional argument to the `Simulation` initializer, and the `fromXmlFiles` constructor is a clearer API for instantiating a `Simulation` from XML files (even if you can do the exact same thing with the standard constructor).
The `State` XML file is optional.
What do …
=> Create alternative constructor for Simulation from XML files

openmmapi/include/openmm/internal/timer.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/include/CudaPlatform.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaPlatform.cpp, platforms/cuda/tests/TestCudaFFT3D.cpp, platforms/cuda/tests/TestCudaRandom.cpp, platforms/cuda/tests/TestCudaSort.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/include/OpenCLPlatform.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLPlatform.cpp, platforms/opencl/tests/TestOpenCLFFT.cpp, platforms/opencl/tests/TestOpenCLRandom.cpp, platforms/opencl/tests/TestOpenCLSort.cpp
Querying the atom positions involves a nontrivial amount of processing on the CPU.  This parallelizes that.  In most cases the effect is negligible, but in cases where you need to query the positions at every time step, it does make a difference.  (This came up in the context of the PLUMED plugin.)
=> Parallelized the code for downloading positions

plugins/drude/platforms/cuda/src/kernels/drudeParticleForce.cu, plugins/drude/platforms/opencl/src/kernels/drudeParticleForce.cl
The anisotropic polarizability in Drude FF is defined using four particles, first anisotropic term aniso12 using particle 1 and 2, and second term aniso34 using particle 3 and 4. There is a bug in the cuda and opencl platforms that the aniso34 are defined wrongly using the direction of particle 2 and particle 3. This bug escapes our previous tests using water and protein systems because of symmetry in the anisotropy definition in Drude protein force field, but surfaces when we compared energies and forces of nucleic acid systems with Drude FF. 
The reference platform is correct.
=> bugfix on the ansiotropic polarizability for Drude force field

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, tests/TestCustomIntegrator.h
This is closely related to #1384.  It caused the wrong value to be used for "dt" in ComputeGlobal steps.
=> Fixed another error in CustomIntegrator

platforms/cpu/src/CpuNeighborList.cpp, platforms/cpu/tests/TestCpuNeighborList.cpp
In principle this could cause some interactions near the cutoff to be missed when using triclinic boxes.  In practice, I'm not sure how likely that was.  I found the problem while porting the neighbor list code for use in mdtraj.  That version of it operates on atoms individually.  In contrast, the OpenMM version operates on blocks of 4 or 8 atoms, which adds an extra margin of safety.
=> Fixed a bug in CPU neighbor list with triclinic boxes

plugins/amoeba/openmmapi/include/openmm/AmoebaMultipoleForce.h, plugins/amoeba/openmmapi/src/AmoebaMultipoleForce.cpp
These values were provided by @andysim.  They produce more accurate results on a range of different system types.  There's no reference for them yet, since they're still working on the paper.  Once it's published, we should add a reference to it.
=> Updated default coefficients for extrapolated polarization

openmmapi/include/openmm/CustomIntegrator.h, openmmapi/src/CustomIntegrator.cpp, openmmapi/src/CustomIntegratorUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp
Fixes #1410.  For the benefit of Fortran, we can't have a method and an enum value whose names differ only in case.
=> Renamed enums that caused Fortran compiler errors

openmmapi/include/openmm/internal/OSRngSeed.h
This caused a compilation error on some versions of gcc
=> Removed the UTF-8 header from a file

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
This *correctly* fixes #1441.  My earlier fix had a serious error in it.  This definitely needs to be corrected in 7.0, so once this is merged I'll move the `7.0rc1` tag and we'll need to rebuild the release candidate.  Sorry about that!
=> Fixed an error in the earlier fix for tabulated functions with interaction groups

platforms/opencl/src/OpenCLContext.cpp
This came up on my new laptop.  It has both a discrete GPU that supports double, and an integrated GPU that doesn't.  It was automatically selecting the latter, then throwing an exception.
=> In mixed or double mode, don't select devices that don't support double

openmmapi/include/openmm/MonteCarloAnisotropicBarostat.h, openmmapi/include/openmm/MonteCarloBarostat.h, openmmapi/include/openmm/MonteCarloMembraneBarostat.h, openmmapi/src/MonteCarloAnisotropicBarostat.cpp, openmmapi/src/MonteCarloAnisotropicBarostatImpl.cpp, openmmapi/src/MonteCarloBarostat.cpp, openmmapi/src/MonteCarloBarostatImpl.cpp, openmmapi/src/MonteCarloMembraneBarostat.cpp, openmmapi/src/MonteCarloMembraneBarostatImpl.cpp, platforms/reference/tests/TestReferenceMonteCarloMembraneBarostat.cpp, serialization/src/MonteCarloAnisotropicBarostatProxy.cpp, serialization/src/MonteCarloBarostatProxy.cpp, serialization/src/MonteCarloMembraneBarostatProxy.cpp, serialization/tests/TestSerializeMonteCarloAnisotropicBarostat.cpp, serialization/tests/TestSerializeMonteCarloBarostat.cpp, serialization/tests/TestSerializeMonteCarloMembraneBarostat.cpp, tests/TestMonteCarloAnisotropicBarostat.h, tests/TestMonteCarloBarostat.h
This addresses at least part of #1440.  The barostats now have a "default temperature" attribute instead of "temperature", and they define a context parameter for changing the temperature in the middle of a simulation.
Note that this breaks backward compatibility!  Hopefully it will affect very few people, but it's still important to be aware of.
=> Changed mechanism for setting barostat temperature

olla/include/openmm/kernels.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp
This fixes #1478.  If positions have internally been wrapped to the periodic box boundaries, it unwraps them before changing the box dimensions.  This ensures the absolute positions do not change.
=> Changing box vectors does not change positions

platforms/cpu/include/CpuKernels.h, platforms/cpu/include/CpuNeighborList.h, platforms/cpu/include/CpuPlatform.h, platforms/cpu/src/CpuCustomGBForce.cpp, platforms/cpu/src/CpuCustomNonbondedForce.cpp, platforms/cpu/src/CpuKernels.cpp, platforms/cpu/src/CpuNeighborList.cpp, platforms/cpu/src/CpuPlatform.cpp
Previously if you had two forces that needed a neighbor list (like a NonbondedForce and a CustomNonbondedForce), the CPU platform would create a separate neighbor list for each one.  They can now share a single neighbor list, which should help performance in that case.
=> CPU platform shares neighbor list between forces

wrappers/python/simtk/openmm/app/internal/customgbforces.py, wrappers/python/tests/TestAmberPrmtopFile.py
This doesn't lead to incorrect results, but it does erroneously flag some radii
as being illegal when they aren't (making it impossible to run some suggested
systems).
The parameters need to be compared to the table limits *before* subtracting off
the offset, whereas it's currently being done after.
Reported by Alberto Perez in a private email to me.
=> Fix error check for GBneck parameters

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/pme.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/pme.cl, tests/TestEwald.h
=> Fixed bug in PME with triclinic boxes

platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/opencl/src/OpenCLExpressionUtilities.cpp, tests/TestCustomCompoundBondForce.h
Fixes #1476.  This error occurred when the argument to a tabulated function was *exactly* equal to its upper limit.  In that case, there was an indexing error and coefficients were read from the wrong memory location (often leading to a nan).
This only affected 2D and 3D functions, not 1D ones, and only on the CUDA and OpenCL platforms.  It also only affected continuous functions, not discrete ones.
=> Fixed edge case with 2D and 3D continuous functions

platforms/cuda/include/CudaContext.h, platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/customGBEnergyN2.cu, platforms/cuda/src/kernels/customGBValueN2.cu, platforms/cuda/src/kernels/gbsaObc1.cu, platforms/cuda/src/kernels/nonbonded.cu, platforms/opencl/include/OpenCLContext.h, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/customGBEnergyN2.cl, platforms/opencl/src/kernels/customGBEnergyN2_cpu.cl, platforms/opencl/src/kernels/customGBValueN2.cl, platforms/opencl/src/kernels/customGBValueN2_cpu.cl, platforms/opencl/src/kernels/gbsaObc.cl, platforms/opencl/src/kernels/gbsaObc_cpu.cl, platforms/opencl/src/kernels/nonbonded.cl, platforms/opencl/src/kernels/nonbonded_cpu.cl, plugins/amoeba/platforms/cuda/src/kernels/multipoleElectrostatics.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoleFixedField.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoleInducedField.cu, plugins/amoeba/platforms/cuda/src/kernels/pmeMultipoleElectrostatics.cu
This should hopefully fix #1496.  It now checks the neighbor list size on every time step.  That involves transferring data from GPU to CPU, but I was able to overlap that with evaluating the nonbonded forces, so it will usually add negligible overhead.  Also, it will no longer fall back to an O(N^2) algorithm if there isn't enough space for the neighbor list.  Instead, it invalidates the entire force evaluation and repeats it from scratch after allocating more memory.
=> Improved method for resizing neighbor list

platforms/cuda/src/kernels/coulombLennardJones.cu, platforms/opencl/src/kernels/coulombLennardJones.cl
When you used PME, and when two particles whose interaction was excluded had *exactly* the same position, this caused the force to be nan.  The main situation where this could come up is with Drude particles.
=> Fixed error with PME when particles are exactly on top of each other

wrappers/python/CMakeLists.txt
Fixed #1529.  I also made it an error if your SWIG version is too low.  Before it just printed a message, but didn't actually stop you from proceeding.
=> Fixed code that checks SWIG version

plugins/amoeba/openmmapi/include/openmm/AmoebaMultipoleForce.h, plugins/amoeba/openmmapi/include/openmm/AmoebaVdwForce.h, plugins/amoeba/openmmapi/src/AmoebaMultipoleForce.cpp, plugins/amoeba/openmmapi/src/AmoebaVdwForce.cpp, plugins/amoeba/openmmapi/src/AmoebaVdwForceImpl.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.cpp, plugins/amoeba/serialization/src/AmoebaMultipoleForceProxy.cpp, plugins/amoeba/serialization/src/AmoebaVdwForceProxy.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaMultipoleForce.cpp
Fixes #435, among other things.  I replaced several methods to make the AMOEBA API more consistent with the rest of OpenMM.  The old methods are still there but marked as deprecated.
=> Made AMOEBA API more consistent

platforms/cuda/include/CudaContext.h, platforms/cuda/src/CudaContext.cpp
This is a workaround for the fact that the CUDA runtime compiler produces slower code than nvcc.  When you create a context with the CUDA platform, it tries to execute the command "nvcc --version".  If that doesn't produce an error, it concludes nvcc is available and uses that instead of the runtime compiler.
See #1502.
=> Prefer nvcc over runtime compiler

platforms/cuda/src/CudaContext.cpp
This fixes a failing test case
=> If temp directory does not exist, use runtime compiler

platforms/cuda/src/kernels/nonbonded.cu
Fixes #1625.
This was really hard to track down!  The error occurs when `ContextImpl::calcForcesAndEnergy()` gets called with `includeEnergy` true but `includeForces` false.  That doesn't happen when you call `getState()`, since even if you don't ask for forces, it still needs them to correct the kinetic energy.  And it doesn't happen within standard integrators, because they don't use energy.  The only place it happens is in a CustomIntegrator that requests energy but not forces.  That happened in #1625 because it specifies the forces as `f0` (only group 0), but the energy as `energy` (all groups).
=> Fixed bug computing energies without forces

docs-source/usersguide/theory.rst, openmmapi/include/openmm/CustomCompoundBondForce.h, openmmapi/include/openmm/CustomTorsionForce.h
Fixes #1637
Updates docstrings for `CustomTorsionForce` and `CustomCompoundBondForce` to specify units and domain for computed torsion/dihedral.
=> Update docstrings to specify units and domain for torsions

wrappers/python/simtk/openmm/app/internal/customgbforces.py
We just realized we will have to automatically modify energy expressions of `CustomGBForce` forces in YANK to support alchemically-modified GB models that aren't `GBSAOBCForce`.
Previously, the charge variable was `q`, which I fear is going to cause too much trouble due to its non-uniqueness. Changing all of these to `charge` should not affect anything (since these are internal) and will make it easier to recognize and modify these parameters in code that manipulates them (both our `alchemy` and the constant-pH `proton-drive` will need to do this).
More generally, if we could standardize naming of common parameters in `Custom*Force` forces (such as `charge`, `sigma`, and `epsilon`), the tools we build will better be able to support custom forces.
=> Change variable 'q' to 'charge' in custom gb models

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customNonbonded.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customNonbonded.cl, tests/TestCustomNonbondedForce.h
This was a somewhat obscure bug that caused forces and energies to be wrong under a very specialized set of conditions.  To encounter the error, 1) your system needed to included multiple nonbonded forces, 2) at least one of them needed to be a CustomNonbondedForce that enabled the switching function, and 3) you had to be using the CUDA or OpenCL platform.  But even then it wouldn't always happen.  It also depended on the assignment of force groups and the order in which the forces were added to the system.  See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=7140&p=0&start=0&view= for more information.
=> Fixed bug in switching functions with CustomNonbondedForce

platforms/cuda/src/CudaNonbondedUtilities.cpp
We can reenable it once we figure out why it's failing on Kepler GPUs.  See #1613.
=> Disable fine-grained pair list

devtools/packaging/scripts/windows/Vagrantfile, devtools/packaging/scripts/windows/build.bat, devtools/packaging/scripts/windows/prepare.ps1
I'm making progress on this.  Slowly.  And very painfully.  And why does nothing ever work?  And did I mention how much I hate Windows?  It's bad for my health.
It's not yet fully automated, but it's a lot closer than before.  I'm using Vagrant to create a VM.  Then I log into it, clone the OpenMM repository inside it, and run the build script to do the build.
I've never managed to get sphinx to build pdfs on Windows.  See https://github.com/pandegroup/openmm/issues/1362#issuecomment-187351460.  And I don't think it's worth worrying about that right now.  So for this release I'll probably just disable building documentation, then copy over a docs directory from one of the other builds.
Can we drop support for Python 3.4 on Windows?  To build for Python 3.5, we use Visual Studio 2015 which …
=> Automate Windows builds

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=7284&p=19138.
The error was in selecting steps to merge into a single GPU kernel.  It happened when you had three per-DOF computations in a row with the following properties:
Step 1: Invalidates forces (such as by modifying x)
Step 2: Neither uses nor invalidates forces
Step 3: Uses forces
Merging steps 1 and 2 is valid, and merging steps 2 and 3 is also valid, but merging all three steps is not.  It needs to recompute forces somewhere between step 1 and step 3.
The fix is perhaps a bit overly conservative.  I made it so if a step invalidates forces, it will *never* merge that with the following step.  In some cases that will prevent it from merging steps even though it would be ok to do so.  But it's really easy to make …
=> Fixed bug merging steps in CustomIntegrator

wrappers/python/simtk/openmm/app/modeller.py
If you call `addHydrogens()` but don't specify a forcefield, it generates a simple one designed to space out the added hydrogens evenly.  It was using a soft core repulsive force that went to 0 at r=0.  That meant it would occasionally add two hydrogens at the same location.  I've switched it to a hard core force that doesn't have that problem.
=> Avoid adding hydrogens at same location

platforms/opencl/src/kernels/findInteractingBlocks.cl
Fixes #1651.  This only works if you have driver 375.20 or later.  It does *not* work with driver 367.48, which is the one bundled with CUDA 8.0.
=> Fix for errors on Pascal GPUs

wrappers/python/simtk/openmm/app/gromacstopfile.py
Certain GROMACS topologies (see https://github.com/choderalab/yank/issues/623) fail to process correctly when the final term in a torsion uses scientific notation, as it is handled as an integer. Specifically, terms like this are problematic:
```
1       2       3       4     1    1.80000080e+02    1.51670000e+01    2.00000000e+00
```
and produce an error `ValueError: invalid literal for int() with base 10: '2.00000000e+00'` due to the fact that int('2.00000000e+00') raises a value error. Seems like the simplest fix is to process as a float (which works correctly) and if, indeed, this is supposed to be an int (can someone confirm?) then cast to an int after reading.
=> Fix handling of scientific notation for field 7 in torsions in certain GROMACS topologies

platforms/opencl/src/OpenCLKernels.cpp
Fixes #1723.  The error happened when all of the following were true:
1. You were using the OpenCL platform.
2. You had a CustomNonbondedForce that used interaction groups.
3. You also had a barostat in the system.
In that case, the kernel to evaluate the forces for interactions groups would apply periodic boundary conditions based on the box vectors at the start of the simulation, instead of based on the current ones.
=> Fixed bug applying periodic boundary conditions to interaction groups

plugins/amoeba/platforms/cuda/src/kernels/multipoleElectrostatics.cu, plugins/amoeba/platforms/cuda/tests/TestCudaAmoebaExtrapolatedPolarization.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp
Just a couple of small changes to the AMOEBA code, to make the CUDA tests pass cleanly, and to make the code more readable.
=> Trivial changes to AMOEBA plugin.

.travis.yml, tests/TestDispersionPME.h
Fixes #1714.  This forces travis to use an older version of doxygen on OS X to work around the segfault in the newer version.  I also fixed a test failure caused by an overly strict error tolerance.
=> Fixed failing tests

docs-source/developerguide/conf.py, docs-source/usersguide/conf.py
Sphinx's `DUspan` function was improved and renamed to `DUrole` between 1.3.1 and 1.5.1. Since OpenMM's docs extend the custom text role to support `code`, this caused the docs to not compile on both versions. 
This PR allows the old rewrite to `DUspan` (will continue to break for anything other than `code`) while also allowing the new `DUrole` (with proper extension to allow `code`). Both versions yield the same typesetting output for this function. 
Related issues:
omnia-md/conda-recipes#723
omnia-md/conda-dev-recipes#81
=> Allow docs to build in Sphinx 1.3.1 and 1.5.1

wrappers/python/simtk/openmm/app/forcefield.py
If you attached a Drude particle to an isolated atom, not bonded to anything else, ForceField would fail to add a nonbonded exclusion between the atom and its Drude particle.
=> Fixed error with exclusions for Drude particles

docs-source/usersguide/references.bib
Missing comma causes docs not to compile.
Fixes omnia-md/conda-dev-recipes#84
=> Fix typo in bibtex entry

wrappers/python/simtk/openmm/app/forcefield.py
The group is called `openmm.forcefielddir`.  The entry point should be a function that returns a string containing the path to a directory.
See https://github.com/choderalab/openmm-forcefields/issues/6.  Also see http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins for information on creating entry points.
=> Defined entry point so other packages can add force field directories

devtools/packaging/README.md, openmmapi/include/openmm/CustomTorsionForce.h, wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/tests/TestCharmmFiles.py, wrappers/python/tests/systems/improper.psf
Fixes #1760.
This is a major bug that affects the reading of CHARMM files, and can cause anything from subtle incorrect simulations to major explosions. Recommend bugfix point release after merging.
=> Fix bug where CHARMM impropers did not respect toroidal boundary conditions

olla/include/openmm/kernels.h, platforms/cpu/include/CpuPlatform.h, platforms/cpu/src/CpuKernels.cpp, platforms/cpu/src/CpuPlatform.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, plugins/cpupme/src/CpuPmeKernels.cpp, plugins/cpupme/src/CpuPmeKernels.h, plugins/cpupme/tests/TestCpuPme.cpp
Fixes #1799.  The interface is the same as for CUDA: specify `'DeterministicForces':'true'` when you create your context.  This *only* affects the behavior of PME, so unlike with CUDA, the results are still not fully deterministic.  But PME is often the largest source of non-determinism, so the variation should at least be reduced.
=> Added option for CPU PME to be deterministic

platforms/cuda/src/kernels/customManyParticle.cu, platforms/opencl/src/kernels/customManyParticle.cl
See #1794.  The effect was that on the CUDA and OpenCL platforms, it would sometimes include an interaction that was supposed to be excluded.
=> Fixed bug in CustomManyParticleForce.

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
Add support for flexibleConstraints to ForceField.createSystem
There are times when it is helpful to have the energy terms actually
added to the System even if that degree of freedom is constrained. Other
parsers (notably the Amber parsers) already support this keyword, so add
that support to ForceField as well
This also replaces some string-based element detection algorithms with
whatever the PDB parser does (by comparing directly to atom.element)
=> Flexible constraints

openmmapi/src/CustomIntegratorUtilities.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp
See #1815.  It's now better at not repeating the same calculation when you're switching back and forth between force groups.
=> CustomIntegrator avoids unnecessary force/energy computations

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp
This addresses #1828.  In my testing, the speed difference between the versions with and without kinetic energies has decreased from 30% before to only about 12% with this change.
=> Improved performance of computing sums with CustomIntegrator

platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, platforms/reference/src/ReferenceKernels.cpp, tests/TestCustomGBForce.h
Fixes #1848.
This error happened when *all* of the following conditions were met:
- You were using the Reference or CPU platform.
- You were using a cutoff.
- Your system included a CustomGBForce.
- The force had a computation of type `ParticlePairNoExclusions`.
- The force also had exclusions.  On the CPU platform, it could also happen if the CustomGBForce didn't itself have exclusions, but the system contained a NonbondedForce or CustomNonbondedForce that had exclusions.
In that case, the excluded interactions would incorrectly be omitted from the `ParticlePairNoExclusions` computation.
=> Fixed bug in CustomGBForce

platforms/cuda/src/CudaContext.cpp, platforms/opencl/src/OpenCLContext.cpp
This fixes an obscure bug in the logic for identifying identical molecules that can be reordered internally.  It happens when two molecules are identical except for their bonds.  Furthermore, each molecule has the same number of bonds of each type, and corresponding bonds even have identical parameters, but don't connect corresponding atoms.  In that case, it will incorrectly conclude they are identical.
This came up when someone was simulating graphite sheets, so all atoms and all bonds had identical parameters.  See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=8138&p=0&start=0&view=&sid=4f4b9091e65d616b177f72d2fd0739ac.
=> Bug fix to finding identical molecules

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestPatches.py
Tolerate the case where for some reason the user specifies multiple times that a patch can be applied to a residue.
=> Ignore duplicate patch specifications

wrappers/python/simtk/openmm/app/topology.py
Fixes #1931.  If you try to add atoms to a residue or residues to a chain out of order, it throws an exception.
=> Require atoms and residues to be contiguous

devtools/ci/jenkins/install.sh
Right now the Jenkins recipe is configured to test both CUDA 8 and CUDA 9.  However, without this PR both builds will just use CUDA 8.0
=> Test both CUDA 8 and CUDA 9 (and have it work concurrently).

docs-source/usersguide/application.rst, wrappers/python/simtk/openmm/app/forcefield.py
This makes two changes.  First, included files now get processed together with their parent files exactly as if you had directly specified all of them.  That means there are no longer restrictions about which files can reference each other.  All atom types in all files are processed before any templates or force field terms, so they're visible to all files.
Second, if two files each include the same other file, that other file only gets processed once.  It won't lead to duplicate definitions.
=> Improvement to processing of includes in force fields

wrappers/python/simtk/openmm/app/topology.py
The pickle round trip for the Bond object does not preserve the `type` and `order` parameters in Python 2.7.
Near as I can tell, its because the parent `namedtuple` already has a __getstate__ method, so the default of returning the `__dict__` is never given, so `__setstate__` is not called (as default). This leads to pickle restoring the state, but never invoking the `__new__` statement, resulting in `type` and `order` being lost.
This PR fixes this problem in python 2.7, without breaking python 3.x versions.
xref: mdtraj/mdtraj#1308 and #1543
=> Fix Bond pickling in Python 2.7

wrappers/python/simtk/unit/quantity.py, wrappers/python/tests/TestUnits.py
Fix #1940: Bug in `Quantity.__setitem__` when assigning slices. I've also added a test case.
=> Fix Quantity.__setitem__ bug with slice assignment

wrappers/python/simtk/openmm/app/charmmparameterset.py, wrappers/python/simtk/openmm/app/charmmpsffile.py
I've run into a situation (admittedly fairly perverse) situation where condensing the parameters is painfully slow (>20 minutes for a toy system).  As far as I can tell, the condensing operation is there solely to save memory, so it's not unreasonable to let the user choose to skip this step.  I've added a boolean flag and a function to turn this behavior off.
=> allow the user to skip parameter condensing CHARMM parameters

platforms/cuda/src/kernels/pme.cu, platforms/opencl/src/kernels/pme.cl
The charge spreading kernel is one of the slower parts of PME on the GPU, and the cost of that kernel is dominated by all the atomic writes.  I implemented the simple optimization of skipping any particle whose charge is 0.  That doesn't save any computation, since it just leads to thread divergence, but it does save memory access.
The main benefit of this is when you're using LJPME.  Most water models don't have LJ terms on the hydrogens, so this lets it skip nearly 2/3 of all particles.  There usually isn't much benefit for Coulomb PME, but there's an important exception: most four site water models don't have a charge on the oxygen, so it can skip 1/4 of particles.
=> Optimization to charge spreading

docs-source/usersguide/application.rst, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
Fixes #1994.
I debated about whether this should apply to `<CustomNonbondedForce>` tags.  It supports a switching function, but we have no way of knowing what kind of interaction it's being used for.  In the end I decided it was safest not to.  Just because you want a switching function on LJ interactions, that doesn't necessarily mean you also want it on all CustomNonbondedForces, no matter what purpose they're being used for.  So I made this option only apply to `<NonbondedForce>` and `<LennardJonesForce>` tags.
=> Added switchDistance option to ForceField.createSystem()

wrappers/python/simtk/openmm/app/data/amber14/protein.ff14SB.xml, wrappers/python/simtk/openmm/app/data/amber14/protein.ff15ipq.xml
This is a more complete fix for #2003.  This adds the files that were regenerated in https://github.com/choderalab/openmm-forcefields/pull/62.  The changes to protein.ff14SB.xml are simple, but nearly every line of protein.ff15ipq.xml has changed.  However, this seems to be nothing more than reordering the attributes within each tag.
=> Regenerated files to fix missing external bonds

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
When using a CustomNonbondedForce with large interaction groups, creating the Context should now be a lot faster.  See the discussion in #2014.
=> Optimized initializing interaction groups

wrappers/python/tests/TestForceField.py
Fixes #2039.  I created the patch by hand.  I added a test case that verifies it can create a System for a protein with disulfide bonds, but I haven't checked that it produces identical forces to CHARMM.  @jchodera can you check that?
This fixes the problem in most cases, but the molecule a user discovered the problem in (5UIW) still does not work.  It's an unusual case, and a full fix for it will take bigger changes than I feel safe doing in a patch release.  The problem is that it contains two CYS residues that are adjacent to each other along the chain, and each of them forms a disulfide bond.  The code for applying multi-residue patches ends up matching the patch to the two adjacent residues.  They have the right types, after all, and they're bonded to each other.  But then it's …
=> CHARMM36 supports disulfide bonds

platforms/cuda/include/CudaSort.h, platforms/cuda/src/CudaSort.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/cuda/src/kernels/sort.cu, platforms/opencl/include/OpenCLSort.h, platforms/opencl/src/OpenCLSort.cpp, platforms/opencl/src/kernels/sort.cl
These are my attempts to improve performance on Volta, though there's not a lot to show for it.  I was able to reduce shared memory use in `findBlocksWithInteractions()`, which improves occupancy a bit.  Unfortunately, this turned out not to have any effect on performance.  Oh well!
I rewrote `sortShortList()`.  The old version was run entirely on a single thread block.  The new version uses a different algorithm that is less efficient but can be parallelized across multiple blocks.  As a result, it's now about twice as fast.  This does have a significant effect on performance... unless you're using PME.  In that case, it runs the reciprocal space calculations on a separate stream, and it's able to fill up the remaining SMs with work from that stream.  So this change doesn't make any …
=> Minor optimizations

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/pme.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/pme.cl
This is the result of several weeks of work.  I've thought for a long time there must be *some* way to make charge spreading faster.  So I've been trying out all sorts of approaches, from minor tweaks to completely restructured algorithms.  Almost nothing worked consistently.  I found changes that made it faster for small systems, but slower for large systems.  I found ones that made it faster on Titan X, but slower on Titan V.  I found ones that made the charge spreading kernel run faster, but also made it harder for the GPU to run other kernels at the same time so the simulation ended up being slower.
This is the best I've come up with.  It produces a significant speedup on Titan V (roughly 10% improvement to overall simulation speed).  On Titan X it makes no significant difference one …
=> Optimizations to PME charge spreading

wrappers/python/src/swig_doxygen/swig_lib/python/extend.i
This fixes a bug that caused it to throw an exception if you called `getState()` and specified `groups={31}`.
=> Fixed bug in Python wrapper

wrappers/python/simtk/openmm/app/forcefield.py
When an atom does not exist in the defined atom types, instead of raising an error with the available atom names, a NameError is raised because atomIndices is not in scope.
=> minor fix for a NameError in getAtomIndexByName

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, tests/TestDispersionPME.h
The existing call to the CUDA LJ-PME energy is not idempotent if Coulomb terms are absent; this stems from the energy buffer not being zeroed.  If Coulomb terms are present, the buffer is correctly zeroed each energy call (although I can't see where that happens right now) and the code is correct.  A simple call to zero that buffer when Coulomb terms are absent does the trick, and I've added a test to check that the energy call is idempotent.
Most uses of LJ-PME require Coulomb terms, so I wouldn't expect this to impact too many people; pure Lennard-Jones fluid simulations with PME would be impacted and the use case I encountered was running a separate force object to handle electrostatics, while getting LJPME dispersion forces from the normal NonbondedForce.  Sorry for not getting this …
=> Fix bug in CUDA LJPME energy without Coulomb terms

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
The CUDA NonbondedForce routines check for the presence of Coulomb terms, setting `hasCoulomb` accordingly.  If this boolean is false the variable `usePosqCharges` is undefined, leading to the charge elements of `posq` sometimes being clobbered, sometimes not.  This has no consequence for the NonbondedForce (Coulomb terms are off), but I have a plugin that store some charges in `posq` that is affected when the charges in NonbondedForce are zeroed (I use it for LJPME terms).  I'm sure what I'm doing is bad design, but this simple fix gets things up and running for me.  The full test suite passes for me on a P100.
=> Fix uninitialized variable when Coulomb terms are missing

wrappers/python/simtk/testInstallation.py
This makes testing builds a little easier by printing out all the information we look for.  It also gives users clear feedback on whether the differences between platforms are cause for concern.
=> Improvements to testInstallation script

wrappers/python/simtk/openmm/app/forcefield.py
Fixes #2220.
When applying a multi-residue patch, it checked that each residue individually matched its part of the patched template.  It also verified that the residues were bonded to each other, but it didn't check that they were bonded in the correct way.  That led to an exception when two adjacent CYS residues each formed a disulfide bond.
=> Improved logic for matching multi-residue patches

wrappers/python/simtk/openmm/vec3.py, wrappers/python/tests/TestNumpyCompatibility.py, wrappers/python/tests/TestVec3.py
* Added a ``__neg__`` operator overload so that -Vec3(1, 2, 3) returns
the same thing as Vec3(-1, -2, -3)
* Derived Vec3 from namedtuple instead of tuple. This allows you to
access the 3 elements of the vector by name. i.e., vec.x, vec.y, vec.z
=> Improve vec3

platforms/reference/src/SimTKReference/ObcParameters.cpp
This took me way too long to find. There's no reason why these should be defined as floats. I was comparing against my tensorflow reference implementation and found a discrepancy in double precision.
=> Properly define GBSAOBC alpha beta gamma constants to be doubles.

wrappers/python/simtk/openmm/app/gromacsgrofile.py, wrappers/python/simtk/openmm/app/pdbxfile.py, wrappers/python/tests/TestAmberPrmtopFile.py, wrappers/python/tests/TestPdbFile.py
Addressing some `ResourceWarning`s appearing in Python tests. `GromacsGroFile` and `PDBxFile` were both keeping their input file handles open indefinitely. The other cases in the test scripts are fairly harmless, but reducing the number of warnings is never a bad thing.
=> Ensuring opened files are properly closed

wrappers/python/simtk/openmm/app/forcefield.py
Doing some profiling of simulation startup in a large forcefield with 2922 different improper definitions, outside of `new_Context()` the repeated calls to `_matchImproper()` in `PeriodicTorsionGenerator` are far and away the most expensive (3.5 seconds for a 229-residue protein vs. about 200ms for the next-most-expensive call). By caching the improper definitions (or lack thereof) for signatures that have already been seen, the number of calls to `_matchImproper()` is reduced from ~2500 to 92, bringing the time cost down to 125 ms.
Incidentally, the `createForce()` methods in `RBTorsionGenerator` and `CustomTorsionGenerator` are near-identical copies of that in `PeriodicTorsionGenerator`. Looks like these could be quite easily refactored as subclasses of a generic base class?
=> Avoid repeated matching of duplicate impropers

wrappers/python/simtk/openmm/app/modeller.py
After the discussion in #2100, addressing #2099, I implemented a private `addIons` method that replaces waters (or any molecule really) by ions, up to a given concentration or to a certain number of ions. I replaced the ion addition routines in each `addSolvent` and `addMembrane` by a call to the new `addIons`.
Tested locally and it works for both membrane and non-membrane systems. I cannot figure out what would be a proper test for this though, to add to the unit tests.
Suggestions are welcome!
=> Improved ion addition to both addSolvent() and addMembrane()

wrappers/python/simtk/openmm/app/internal/customgbforces.py
Still on a bit of an optimisation spree here, and it turned out that preparation of the `GBSAGBn2Force` was my next biggest bottleneck in simulation startup (~13 of 36 seconds for 6g2j). Introducing a little numpy magic brings that down to 4.1 seconds. 
This passes `TestAmberPrmtopFile.py`, but not `TestCharmmFiles.py`, and I'm not sure why yet. Hoping for any insights?
=> Customgbforces

docs-source/usersguide/theory.rst
I noticed the [conda-dev-builds](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/515150822#L5957-L5975) were failing with:
```
LaTeX Warning: Hyper reference `theory:writing-custom-expressions' on page 125 
undefined on input line 9061.
[125]
! Package inputenc Error: Unicode character π (U+3C0)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
...                                              
l.9122 ... is guaranteed to be in the range {[}-π
, π{]}.  Like PeriodicTor...
? 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: …
```
=> Fix unicode error in sphinx compilation

wrappers/python/simtk/openmm/app/data/pdbNames.xml
Adding alternative names of terminal nucleic acids (5' and 3' as DG5 and DG3).
Adding alternative names of atoms H2', H2'', H5' and H5'' for nucleic acids.
These few changes allow working with PDB files with DNA coming from tleap without renaming atoms and residues (see https://github.com/pandegroup/openmm/issues/2313).
=> Adding alternative names of terminal nucleic acids (5' and 3') and atoms H2', H2'', H5' and H5''.

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/coulombLennardJones.cu, platforms/cuda/src/kernels/nonbondedParameters.cu, platforms/cuda/src/kernels/pmeExclusions.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/coulombLennardJones.cl, platforms/opencl/src/kernels/nonbondedParameters.cl, platforms/opencl/src/kernels/pmeExclusions.cl
Fixes #2310.  The reciprocal space part of excluded interactions are now subtracted off in a separate loop, not as part of the main nonbonded kernel.
=> Revised how exclusions are computed with PME

openmmapi/src/CustomIntegratorUtilities.cpp, tests/TestCustomIntegrator.h
Fixes #2331.  Under certain conditions, this could cause an out of date value for the energy to be used in a step.  The conditions are kind of subtle and difficult to describe.  So far as I know, this only happened on CUDA and OpenCL, not Reference or CPU.  Anyway, I only ever observed it on those platforms.
=> Fixed bug in CustomIntegrator

examples/CMakeLists.txt
One of the files used by the benchmark script wasn't getting installed by `make install`.
=> Install apoa1.pdb

wrappers/python/src/swig_doxygen/swig_lib/python/header.i, wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i
Fixes #2337.  If you supply a 1D Numpy array containing 32 or 64 bit ints or floats, it copies the data directly without going through all the overhead of creating Python objects for each element.
=> Optimized conversion of 1D Numpy array to C++ vector<double>

platforms/opencl/src/OpenCLContext.cpp
This fixes an error that under somewhat exotic circumstances would cause incorrect results.  When *exactly* seven autoclear buffers were added to the OpenCLContext, the last one would only get partially cleared.  This only happened on OpenCL, not any other platform.
This came up in https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10692&p=29834.
=> Fixed error related to autoclear buffers on OpenCL

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/tests/TestCharmmFiles.py
The `setBox()` method in CharmmPsfFile is inconsistent with how we set periodic box vectors everywhere else.  So as an alternative, I've added a pair of optional constructor arguments providing an API identical to the one in GromacsTopFile.
=> Improved API for setting periodic box vectors in CharmmPsfFile

olla/include/openmm/Platform.h, olla/src/Platform.cpp
Sometimes you can't have all your plugins in one place, e.g., due to a modular modules system where third party plugins may be built and loaded into immutable locations independent of the main openmm install. This patch supports path styles for OPENMM_PLUGIN_DIR of the type `some_path/plugins:other_path/plugins:etc`, to ease such use cases.
=> Support for multiple paths in OPENMM_PLUGIN_DIR

wrappers/python/simtk/openmm/app/dcdreporter.py
This should be the correct behavior.
When the step is initialized as 0 (current master version) postprocessing the trajectories in CHARMM leads to warnings and the first frame is skipped.
=> set currentStep in DCDReporter

wrappers/python/simtk/openmm/app/forcefield.py
If you called `forcefield.createSystem()` and specified PME, but the force field included a force that didn't use PME (CustomNonbondedForce, CustomManyParticleForce, etc.), it would throw an exception.  I fixed it so they now interpret it as CutoffPeriodic.  That lets these forces be used in combination with a NonbondedForce using PME.
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10829&p=30031.
=> Force generators that don't use PME still accept it as a nonbonded method

plugins/amoeba/openmmapi/include/openmm/AmoebaVdwForce.h, plugins/amoeba/openmmapi/include/openmm/internal/AmoebaVdwForceImpl.h, plugins/amoeba/openmmapi/src/AmoebaVdwForce.cpp, plugins/amoeba/openmmapi/src/AmoebaVdwForceImpl.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.h, plugins/amoeba/platforms/cuda/src/kernels/amoebaVdwForce2.cu, plugins/amoeba/platforms/cuda/tests/TestCudaAmoebaVdwForce.cpp, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.cpp, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.h, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceVdwForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceVdwForce.h, plugins/amoeba/platforms/reference/tests/TestReferenceAmoebaVdwForce.cpp, plugins/amoeba/serialization/src/AmoebaVdwForceProxy.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaVdwForce.cpp, wrappers/python/src/swig_doxygen/swigInputConfig.py, wrappers/python/tests/TestAPIUnits.py
This addresses issue "AMOEBA vdW softcore support #2369":
https://github.com/openmm/openmm/issues/2369
- Each atom is configured with an alchemical flag to indicate if it should be affected by the softcore functional form.
- The softcore form is defined by 1) multiplying interactions by Lambda^N and 2) adding Alpha*(Lambda -1)^2 to the reduced separation distance (rho = rij / rmin).  Both N and Alpha are global parameters of the force (defaults are 5 and 0.7, respectively) and can be set.
- Application of the softcore form is governed by a enum AlchemicalMethod that is "None" by default, or can be set to either Decouple or Annihilate. Decouple does not apply the softcore form between two atoms that are both alchemical, while Annihilate does.
- A single Context parameter "vdwLambda" …
=> Add Softcore support to AmoebaVdwForce.

openmmapi/include/openmm/internal/MonteCarloAnisotropicBarostatImpl.h, openmmapi/include/openmm/internal/MonteCarloBarostatImpl.h, openmmapi/include/openmm/internal/MonteCarloMembraneBarostatImpl.h, openmmapi/src/MonteCarloAnisotropicBarostatImpl.cpp, openmmapi/src/MonteCarloBarostatImpl.cpp, openmmapi/src/MonteCarloMembraneBarostatImpl.cpp
Previously the barostats created their own random number generators.  The state of that generator didn't get saved to checkpoint files.  That meant if you continued a constant pressure simulation from a checkpoint, the trajectory wouldn't be identical to the original one.  I switched them to use one of the standard random number generators that does get checkpointed.
=> Barostats use checkpointed random number generator

platforms/cuda/src/CudaKernels.cpp
This is a minor change that was needed to make OpenMM and PyTorch get along when both using the GPU in the same process.
=> Make sure correct CUDA context is current

platforms/cuda/src/kernels/findInteractingBlocks.cu
Fixes #2361.
When using a triclinic box, the neighbor list builder would very occasionally miss an interaction that should have been included.  This only happened with CUDA.
=> Fixed error building neighbor list with triclinic box

wrappers/python/simtk/unit/unit_definitions.py
This PR adds the `hartree` unit to `simtk.unit`. This addresses #2419.
This is of immediate need to QCEngine, in particular MolSSI/QCEngine#151.
=> Added hartree unit (addresses #2419)

wrappers/python/simtk/openmm/app/pdbxfile.py, wrappers/python/tests/TestPdbxFile.py
Addresses #2422 
Fixes writing invalid PDBx/mmCIF files when residue insertion codes are blank (not empty) in Topology. Replaces the current check `len(res.insertionCode) > 0` with `res.insertionCode.strip()` to account for cases where the insertion code is stored as a single space from reading e.g. PDB files.
=> Fixes writing PDBx/mmCIF files with blank residue insertion codes.

wrappers/python/simtk/openmm/app/charmmpsffile.py
Fixes #2392.
@jing-huang could you check that my fix is correct?  The problem was an off-by-one error introduced in #2317.  CHARMM numbers atoms starting at 1, and it appears that it sets the fourth atom to 0 (or negative?) to indicate a collinear lone pair.  OpenMM numbers atoms starting at 0, so it subtracted 1 from the indices.  That means it should be checking that the last atom is >=0, not >0.
This affected any file that satisfied very specific conditions: it contained a non-collinear lone pair, and the third atom it depended on was the very first atom in the file.
=> Fixed range error when adding lone pairs from PSF file

platforms/opencl/src/OpenCLPlatform.cpp
=> Catch exception when cl::Platform::get() fails.

openmmapi/include/openmm/BAOABLangevinIntegrator.h, openmmapi/include/openmm/BrownianIntegrator.h, openmmapi/include/openmm/CustomIntegrator.h, openmmapi/include/openmm/Integrator.h, openmmapi/src/BAOABLangevinIntegrator.cpp, openmmapi/src/BrownianIntegrator.cpp, openmmapi/src/Context.cpp, openmmapi/src/CustomIntegrator.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp
This is an optimization to `context.getState(State::Energy)`.  For a leapfrog integrator, we have to first shift the velocities by half a step, which requires computing the forces.  But for non-leapfrog integrators, that isn't necessary.  This change allows it to skip the force evaluation for those integrators.
=> Avoid unnecessary force evaluation when computing kinetic energy

plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.h, plugins/amoeba/platforms/cuda/tests/TestCudaAmoebaMultipoleForce.cpp, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.cpp, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.h, plugins/amoeba/platforms/reference/tests/TestReferenceAmoebaMultipoleForce.cpp, plugins/cpupme/src/CpuPmeKernels.h, plugins/cudacompiler/src/CudaCompilerKernels.h, plugins/drude/platforms/cuda/src/CudaDrudeKernels.h, plugins/drude/platforms/opencl/src/OpenCLDrudeKernels.h, plugins/drude/platforms/reference/src/ReferenceDrudeKernels.h, plugins/rpmd/platforms/cuda/src/CudaRpmdKernels.h, plugins/rpmd/platforms/opencl/src/OpenCLRpmdKernels.h, plugins/rpmd/platforms/reference/src/ReferenceRpmdKernels.h
there were a number of constructors that didn't have the std::string being passed as a reference which is very expensive, this makes them pass by reference if they don't get chaged
=> make std::string pass as references, not values

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/simtk/openmm/app/pdbfile.py, wrappers/python/tests/TestForceField.py
Fixes #2426.  Patches can lead to two identical templates that both match the same residue.  Allow this as long as the templates really are identical.
=> Allow multiple matching templates if they assign identical parameters

wrappers/python/simtk/openmm/app/simulatedtempering.py
This improves the speed of _attemptTemperatureChange during simulated tempering, for those using numpy. List comprehension is required for those not using numpy, hence the if/else.
=> Get and scale velocities using numpy during simulated tempering

.travis.yml
This makes travis test python 3.6 and 3.8.  And yes, I'm dropping the tests for 2.7.  It's time to move on.
=> Update travis to test more recent Python versions

platforms/reference/include/ReferenceTabulatedFunction.h, platforms/reference/src/ReferenceTabulatedFunction.cpp
See #2474.  On the reference and CPU platforms, this can make context creation much faster.
=> Optimized processing of expressions with tabulated functions

wrappers/python/simtk/openmm/app/modeller.py
Within Modeller.addExtraParticles(), add the ability to pass down
an option to modify compiled.matchResidueToTemplate() 's
ignoreExternalBonds parameter.
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=11264&p=0&start=0&view=&sid=e384beeb08f3bfd767dcfb546006ad63
=> Signature modification to Modeller.addExtraParticles()

libraries/lepton/include/lepton/ParsedExpression.h, libraries/lepton/src/ParsedExpression.cpp
Lepton::ParsedExpression::getConstantValue() used to return NaN to indicate non-constant
expressions. This can break with -ffast-math optimization where NaN comparisons are
not defined.
This patch defines isConstant() to test whether an expression is constant before
calling getConstantValue(). getConstantValue() now throws an exception if called on a
non-constant expression.
=> Fix Lepton optimization with -ffast-math

docs-source/usersguide/application.rst, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py, wrappers/python/tests/systems/formaldehyde.pdb
This PR adds a new `ordering='smirnoff'` mode to improper torsion handling in `PeriodicTorsionGenerator` to make it possible to get exact agreement with [SMIRNOFF small molecule force fields](https://open-forcefield-toolkit.readthedocs.io/en/latest/smirnoff.html), which use trefoil-style torsions to avoid improper torsion ambiguity issues that plague GAFF, AMBER, and CHARMM. 
This feature will be used by the [`SMIRNOFFTemplateGenerator`](https://github.com/choderalab/openmm-forcefields/tree/update-amber#examples-using-smirnofftemplategenerator-to-generate-small-molecule-smirnoff-parameters) that provides support for parameterizing small molecules on the fly with the [`openforcefield` toolkit](http://openforcefield.org).
Fixes #2509
=> Add support to ForceField for handling SMIRNOFF trefoil impropers

wrappers/python/simtk/testInstallation.py
We are seeing large differences in forces in the `ppc64le` build attempts. However, these are not caught by the CI because the exit code for those errors is still `0`. Raising an exception if errors are observed will change that behavior.
=> testInstallation: raise exception if large differences are observed

openmmapi/src/BAOABLangevinIntegrator.cpp
This error was introduced by #2447.  Unfortunately, the fix removes much of the benefit of that optimization, since after you call `getState()` to query the energy, the next step you take requires two force evaluations.  I might see if I can do a better fix in the future, but for the moment it's more important that the results be correct.
=> Fixed error in BAOAB on CUDA and OpenCL

wrappers/python/simtk/openmm/app/data/amoeba2009.xml, wrappers/python/simtk/openmm/app/data/amoeba2013.xml, wrappers/python/simtk/openmm/app/data/iamoeba.xml, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
By default `ForceField.createSystem()` makes all water molecules rigid.  This is correct for most water models, but AMOEBA water is supposed to be flexible.  If the user doesn't realize they need to specify `rigidWater=False`, they'll incorrectly get rigid water.  See #2506 fox example.
I made two changes.  First, the force field definition can add the attribute `rigidWater="false"` to the water template to indicate that it should be flexible.  Second, the default value for the `rigidWater` option on `createSystem()` is now `None` instead of `True`.  This tells it to use whatever behavior is appropriate for the water model: rigid models are rigid and flexible models are flexible.  If you explicitly specify `True` or `False` instead, that overrides the default and forces all water to be …
=> Improved behavior of rigidWater option

docs-source/usersguide/application.rst, docs-source/usersguide/library.rst, examples/HelloSodiumChloride.cpp, examples/HelloSodiumChlorideInC.c, examples/HelloSodiumChlorideInFortran.f90, examples/simulateAmber.py, examples/simulateCharmm.py, examples/simulateGromacs.py, examples/simulatePdb.py
=> Updated simulation parameters in documentation and examples

.azure-pipelines/azure-pipelines-windows.yml
In response to all the Appveyor issues, I spent some time taking the machinery that @dgasmith developed for Psi4 and making it work for OpenMM.  The current setup builds and tests the entire code in around 20 minutes, although there's essentially no time limit on that platform.  The only limitation for open source projects is that only 10 concurrent runs are allowed, which is fine.  The Psi4 Linux runner is way faster than Travis, so it may be worth porting that also.
I cybersquatted the dev.azure.com/openmm/openmm domain to get this set up and for a ransom of 0 bitcoins I'll gladly sign it over to @peastman if we choose to go this route.
=> Windows tests on Azure

platforms/cpu/src/CpuKernels.cpp
Fixes #2521.  This happened when the system contained a NonbondedForce that viewed the system as periodic (the nonbonded method was CutoffPeriodic, PME, etc.), and it also contained some other nonbonded interaction (CustomNonbondedForce, GBSAOBCForce, etc.) that used a non-periodic nonbonded method.  In that case, the CPU platform would leave out the long range dispersion correction when computing the energy.
=> Fixed error on CPU platform when forces disagree about whether the system is periodic

platforms/common/src/CommonKernels.cpp
Constraints are applied relative to a base configuration that determines which directions the constraint forces are applied along.  Different platforms were using different base configurations when you executed the following sequence of steps:
1. Update positions
2. Update positions again
3. Apply constraints
The Reference and CPU platforms used the positions at the start of step 1 as the base.  The CUDA and OpenCL platforms used the positions at the start of step 2.  I changed them to behave the same as Reference.
=> Fixed inconsistency between plaforms in constraints with CustomIntegrator

olla/src/Platform.cpp
The `RTLD_GLOBAL` flag causes problems when building with (e.g.) devtoolset-7, which statically links in all newer components of the static library to maintain backward compatibility to CentOS 7. The problem arises when the resulting build is used with another library also built with devtoolset-7: calling `dlopen` with `RTLD_GLOBAL` causes the statically-linked components to be loaded twice. Things still tend to work until the application is closed, at which point there's a crash looking like the one below, due to the symbol tables from the `dlopen`ed libraries getting jumbled up (see https://stackoverflow.com/questions/11005881/static-library-loaded-twice). If I understand correctly, the only real reason for using `RTLD_GLOBAL` used to be to allow passing of exceptions between DLLs, but …
=> Switched dlopen flag from RTLD_GLOBAL to RTLD_LOCAL

platforms/cuda/src/CudaContext.cpp
A long time ago, the CUDA runtime compiler had a bug that caused it to ignore optimization flags, leading to slower performance.  To work around that, we made it prefer nvcc over the runtime compiler when both were available.  The bug was fixed a long time ago (I think in CUDA 8.0?), but we never switched it back.
Using the runtime compiler has fewer opportunities for things to go wrong, since it doesn't require locating nvcc on disk, having a host compiler, and having a temp directory we can write to.  So this switches it back.
=> Prefer runtime compiler over nvcc

openmmapi/include/openmm/CompoundIntegrator.h, openmmapi/include/openmm/Integrator.h, openmmapi/include/openmm/LangevinIntegrator.h, openmmapi/include/openmm/LangevinMiddleIntegrator.h, openmmapi/include/openmm/VerletIntegrator.h, openmmapi/src/Context.cpp, plugins/drude/platforms/common/src/CommonDrudeKernels.cpp, plugins/drude/tests/TestDrudeLangevinIntegrator.h, plugins/drude/tests/TestDrudeNoseHoover.h, plugins/drude/tests/TestDrudeSCFIntegrator.h, tests/TestBrownianIntegrator.h, tests/TestCustomIntegrator.h, tests/TestLangevinIntegrator.h, tests/TestLangevinMiddleIntegrator.h, tests/TestNoseHooverIntegrator.h, tests/TestVariableLangevinIntegrator.h, tests/TestVariableVerletIntegrator.h, tests/TestVerletIntegrator.h
See https://github.com/openmm/openmm/pull/2518#issuecomment-572741719 and https://github.com/openmm/openmm/issues/2532#issuecomment-582676175.  I also fixed some tests that were failing on my laptop due to running out of GPU memory.
=> setVelocitiesToTemperature() applies offset for leapfrog integrators

platforms/cpu/src/CpuCustomGBForce.cpp, platforms/cpu/src/CpuKernels.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceObc.cpp, plugins/amoeba/serialization/src/AmoebaTorsionTorsionForceProxy.cpp
This dead code was identified with the help of [scan-build](https://clang-analyzer.llvm.org/scan-build.html). Every variable that I am proposing to remove is initialized to the result of some function call, making it very unlikely that the compiler's optimizer will automatically eliminate the unnecessary code.
=> Remove unused variables

.azure-pipelines/azure-pipelines-windows.yml
When I first set up Azure CI I used the oldest VS version, in keeping with the OpenMM ethos of supporting legacy hardware and software stacks where possible.  Recently Microsoft issued the warning
```
On March 23, 2020, Azure Pipelines will remove Windows Server 2012 R2 with Visual Studio 2015(`vs2015-win2012r2`), macOS High Sierra 10.13 (`macOS-10.13`), and Windows Server Core 1803 (`win1803`) from our hosted pools. This includes builds using the `Hosted` agent pool. A series of brownouts to highlight builds and releases using these soon-to-be-removed images will be conducted over the next couple of weeks. During these brownouts, any builds and releases using the vs2015-win2012r2, macOS-10.13, or win1803 images will fail.
```
To address the deprecation, this PR updates the VM to a newer, …
=> Update Azure VM to newer version

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/simtk/openmm/app/internal/compiled.pyx, wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestPatches.py
This is related to #2585.  To use the polarizable force field, you need to call `addExtraParticles()` to add the Drude particles and virtual sites, but it didn't make use of patches in figuring out what to add.  Supporting that took a lot of changes.  I also needed to add the ability for patches to define virtual sites.
=> Changes to support CHARMM polarizable force field

libraries/jama/include/jama_cholesky.h, libraries/jama/include/jama_eig.h, libraries/jama/include/jama_svd.h
These changes follow the Java version of JAMA 1.0.3 at https://math.nist.gov/javanumerics/jama/, latest updated on November 2012.
The C version from https://math.nist.gov/tnt/download.html (with different versioning numbers) hasn't been updated since May 207
Changes in jama_svd.h are necessary to reach convergence in Arm platforms (#2618)
=> Update JAMA to version 1.0.3

libraries/lepton/src/MSVC_erfc.h
This small proposed change enables using MingW to build Lepton when it is linked with LAMMPS.
A PR affecting the LAMMPS copy is already open (see below) and this PR is needed to avoid deviations from the original.  Any improvements to this PR will be applied verbatim to the copies as well.
https://github.com/lammps/lammps/pull/1992
=> Lepton: define M_PI if needed with MingW (in addition to MSVC)

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/tests/TestCharmmFiles.py
As described in #2614 , ```CharmmPsfFile``` parser is not handling constrains with CHARMM TIP3 water topology properly. Proposed changes should be enough to fixed it.
=> Fix for CharmmPsfFile parser constrains with CHARMM TIP3 water topology

plugins/cpupme/src/CpuPmeKernels.cpp
Reduce necessary synchronization between threads, and improve memory locality.
=> Use coarser granularity to split work in PME kernels

libraries/irrxml/include/irrTypes.h
Inline assembly isn't supported by the x64 Microsoft compiler (msvc).
=> Replace inline assembly with compiler intrinsic for _IRR_DEBUG_BREAK_IF

platforms/cpu/include/CpuNeighborList.h, platforms/cpu/src/CpuCustomGBForce.cpp, platforms/cpu/src/CpuCustomManyParticleForce.cpp, platforms/cpu/src/CpuCustomNonbondedForce.cpp, platforms/cpu/src/CpuGayBerneForce.cpp, platforms/cpu/src/CpuNeighborList.cpp
The exclusion mask was 8-bits wide, but future CPU support will require
more bits than this (e.g., AVX-512 will be 16-bit).
=> CPU: Widen mask for exclusion bits (#2676)

openmmapi/src/SplineFitter.cpp, tests/TestSplineFitter.cpp
This PR addresses issue #2627 by means of the following tasks:
=> Bug fix in periodic spline filter (solves #2627)

plugins/drude/serialization/src/DrudeNoseHooverIntegratorProxy.cpp
This is required by msvc when standard conformance mode is not enabled (DrudeNoseHooverIntegratorProxy.cpp(53): error C2065: 'not': undeclared identifier).
=> Replaced alternative spelling of not-operator with '!'

platforms/common/src/kernels/customIntegratorPerDof.cc
Naming the argument list of a variadic macro is a GNU extension which is not supported by msvc. Since CUDA uses the system preprocessor this will fail to build kernels on Windows (fixes error C2010: '.': unexpected in macro parameter list).
=> Removed name of variadic argument list

openmmapi/include/openmm/internal/vectorize8.h, openmmapi/include/openmm/internal/vectorize_neon.h, openmmapi/include/openmm/internal/vectorize_pnacl.h, openmmapi/include/openmm/internal/vectorize_ppc.h, openmmapi/include/openmm/internal/vectorize_sse.h, tests/TestVectorize.cpp, tests/TestVectorize8.cpp, tests/TestVectorizeGeneric.h
Pulled generic vector tests out into a separate header file which can then be easily reused for all available SIMD types. Currently only vec4/vec8 are tested, but other widths can be easily created by
adding extra test files (e.g., AVX-512). Note that the tests mostly check the API required by the CpuNonbondedFvec class, and ignore other APIs (e.g., ivecX). Some of the original tests have been left in place to verify the original APIs, but older tests have been removed where replaced by the new API.
=> Cpu generic vector test

platforms/common/src/CommonKernels.cpp, platforms/common/src/IntegrationUtilities.cpp, plugins/drude/platforms/common/src/CommonDrudeKernels.cpp
This ensures that the correct argument size is used when calling clSetKernelArg.
=> Replace NULL with nullptr when adding kernel arguments

libraries/pthreads/include/pthread.h
Cast 'int' to an integer with the same size as a pointer before casting to a 'void*'
(fixes warning C4312: 'type cast': conversion from 'int' to 'void *' of greater size).
=> Silence warning about casting 'int' to 'void*' on x64 for msvc

platforms/cpu/src/CpuKernels.cpp, platforms/reference/src/ReferenceKernels.cpp
Fixes #2709.  This happened on the Reference and CPU platforms if you were using a parameter offset to modify an exception.
=> Fixed check for changed exceptions

examples/benchmark.py
This updates the benchmarking script to use LangevinMiddleIntegrator and a larger time step where possible.  Here are the speeds I get for the PME benchmark with different possible combinations of settings.
LangevinIntegrator, 2 fs, HBonds constraints: 417
LangevinMiddleIntegrator, 4 fs, HBonds constraints: 740
LangevinMiddleIntegrator, 5 fs, AllBonds constraints, HMR: 568
Langevintegrator, 5 fs, AllBonds constraints, HMR: 775
The ordering is the same for most benchmarks.  Using LangevinMiddleIntegrator with the larger step size produces a big speed improvement compared to LangevinIntegrator.  But the very fastest combination is to use LangevinIntegrator with HMR and more constraints.  Since LangevinMiddleIntegrator needs to apply constraints more often, it takes a big hit from using …
=> Updated benchmark script

.travis.yml
The travis file didn't specify what Python to use for the Mac build, and it was defaulting to 2.7.
=> Use Python 3.6 for Mac build

platforms/opencl/src/OpenCLContext.cpp
When selecting a platform, it will always prefer a supported one over an unsupported one.  If it's forced to use an unsupported platform, it prints a warning to the console.
=> Added check for unsupported OpenCL implementation

devtools/Jenkinsfile
Jenkins has more power!  Amber has graciously donated 4 more machines for me to add to the Jenkins array (2 with GTX 780s and 1 with a GTX 1660).  Builds should go a lot smoother and faster now with newer, faster machines (and 20+ more executors so no more bottlenecks).
[Here are the Ansible playbooks I used to configure the nodes](https://github.com/swails/cluster-setup/tree/master/ubuntu-nodes) and they are already connected to Jenkins and waiting for jobs.
New docker doesn't expose GPUs the same way they used to, though, so we need to add `--gpus all` to the docker arguments for the builds to keep passing on the new executors.
=> Add arguments needed by the new CUDA agents

platforms/common/include/openmm/common/IntegrationUtilities.h, platforms/common/src/IntegrationUtilities.cpp, platforms/common/src/kernels/integrationUtilities.cc, platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/opencl/src/OpenCLIntegrationUtilities.cpp, tests/TestVerletIntegrator.h
Fixes #2814.  For systems with up to 1024 CCMA constraints, it runs that whole algorithm in a single kernel.  This involves much less overhead than the standard implementation, but also requires it to be run in a single thread block.
I haven't tested this with CUDA yet.  The cutoff of 1024 is roughly where the performance crossover happens on my laptop's GPUs, but higher end GPUs might have different performance.  This will need a lot of testing.
=> CCMA with a small number of constraints uses a single kernel

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/nonbonded.cu, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/nonbonded.cl
Fixes #2830.  This only caused problems in unusual situations.  It came up in the revised AMOEBA vdw kernel.  It's possible there could have been other situations where it would have produced errors, but I don't know of anyone actually encountering any.
=> Fixed illegal memory access in nonbonded kernel

openmmapi/include/openmm/LangevinMiddleIntegrator.h
Fixes #2832.
I gave up on including a URL and just used conventional citations.  The comments first get processed by Doxygen, then by a Python script, and finally by Sphinx.  Trying to figure out how to get a URL safely through that whole process was more trouble than it was worth.
=> Improved documentation for LangevinMiddleIntegrator

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/pme.cu
These changes were suggested by David Clark at NVIDIA.  They produce about a 5-10% speedup for DHFR, but a much smaller speedup (<1%) for ApoA1.
=> Minor optimizations to CUDA kernels

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu
I implemented this optimization a while back, but it was causing errors so I disabled it.  @dmclark17 tracked down the problem, which means we can enable it again.  On Titan V it only has a very small effect on speed, around 1%.  On A100 it makes a bigger difference, around 5%.
=> Re-enabled single pair list

platforms/opencl/tests/TestOpenCLNonbondedForce.cpp
4*(1<<30) evaluates to 0 so the check returns true on 2GB cards. Test runs fine on 2GB cards but requires over 4GB of system memory.
=> Fix 4GB memory check

wrappers/python/simtk/openmm/app/modeller.py
This fixes an error that was introduced in #2425.  It would sometimes cause residues to have ids that were ints rather than strings, which produced an exception if you tried to write them to a PDB file and specified `keepIds=True`.
=> Fixed bug in addMembrane()

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/tests/TestOpenCLNonbondedForce.cpp
Minor changes to avoid silent failure of cuFFT execution if an error occurs. Previously, if a cuFFT execution call returned a non-zero result, it would not trigger an exception. This would cause the affected unit tests to fail, seemingly for correctness issues, giving something like this:
```
101: exception: Assertion failure at TestEwald.h:191.   Expected [-198.058, -224.745, -102.259], found [-276.679, -263.117, -92.902]
1/1 Test #101: TestCudaEwaldSingle ..............***Failed    1.58 sec
```
I added error checks to the execution step similar to those of the plan creation. If the FFT execution returns a non-zero error code, it is now reflected in the failure message: 
```
101: exception: Error executing FFT: 1
1/1 Test #101: TestCudaEwaldSingle ..............***Failed    1.59 sec
``` …
=> cuFFT execution error checking

platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/kernels/utilities.cl
The error isn't really specific to RMSDForce, but as far as I can tell, that's the only force that's affected by it.  If you use OpenCL and you have a low end GPU that doesn't support 64 bit atomics, the forces are reported as 0.
=> Fixed error with RMSDForce on GPUs without 64 bit atomics

examples/benchmark.py
This pull request makes the standard OpenMM benchmark script be able to run tests from the Amber suite (as well as all the original tests).  The suite is downloaded and unpacked automatically (into the current directory) if it is not already there. The Amber20 benchmark suite is available here: https://ambermd.org/GPUPerformance.php
Rationale: this has some significantly larger systems than the benchmarks already included in OpenMM, up to the 1 million atom STMV system.  It also allows direct comparisons with published Amber benchmarks.  The intention is to make this as close to apples-to-apples as possible (but there are some remaining small issues, see below).
Questions / caveats:
Impact: should have no effect on any of the existing benchmarks; just adds new ones.
Testing:
- Tested on …
=> Add benchmarks from Amber20 benchmark suite to standard benchmark script

examples/benchmark.py
This makes the `--ensemble` flag work with all benchmarks, and fixes some bugs introduced in #2970.
=> Fixes to benchmark script

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
See https://github.com/conda-forge/openmm-feedstock/pull/46.  This accounts for a difference between CPython and Pypy in how they order the elements of sets.
=> Made ordering of impropers more deterministic

README.md
=> Anaconda badge should point to conda-forge

platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/tests/TestOpenCLNonbondedForce.cpp, tests/TestNonbondedForce.h
See https://github.com/openmm/openmm/pull/2964.
=> Fixed test failures on CPU OpenCL

devtools/Jenkinsfile, platforms/cuda/include/CudaContext.h, platforms/cuda/include/CudaPlatform.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaPlatform.cpp, platforms/cuda/tests/TestCudaFFT3D.cpp, platforms/cuda/tests/TestCudaRandom.cpp, platforms/cuda/tests/TestCudaSort.cpp
In 7.5 we changed the behavior of compiling CUDA kernels, so it would prefer the runtime compiler over the command line compiler. This was supposed to avoid problems, but it ended up creating some new problems. One of them is that if anything went wrong with the runtime compiler, it was hard to fix.  There was no straightforward way to force it to use the command line compiler instead.
This PR changes the behavior so that if you explicitly specify a command line compiler, either with the `'CudaCompiler'` property or the `OPENMM_CUDA_COMPILER` environment variable, that forces it to use the compiler you specify.  It will never use the runtime compiler instead.
=> Use command line compiler if it is explicitly specified

platforms/cuda/include/CudaContext.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaContext.cpp, plugins/cudacompiler/src/CudaCompilerKernels.cpp, plugins/cudacompiler/src/CudaCompilerKernels.h
In 7.5 we changed the behavior of compiling CUDA kernels, so it would prefer the runtime compiler over the command line compiler.  This was supposed avoid problems, but it ended up creating some new problems.  One of them is that conda would sometimes make a bad choice of what toolkit to install, and you would get a compiler too old to support your GPU's architecture.
This PR addresses the problem by querying the runtime compiler to find the maximum architecture it supports.  It then tells the compiler to target the highest architecture that is supported by both the compiler and the GPU.
=> Improve selection of architecture to compile for

platforms/common/include/openmm/common/ComputeContext.h, platforms/common/src/ComputeContext.cpp
While trying to debug the #3039 i ran into a problem: when i tried to catch crashes from main, the exception just "ignored" the catch statement. It puzzled me for a while and after some thinking i realized what the problem was: when an exception arises inside of a worker thread, it crashes the entire thing. So i made it stash the exception until the `flush()` is called and then rethrow it into the main thread.
=> Made ComputeContext worker threads rethrow encountered exceptions into the main thread.

wrappers/python/openmm/app/charmmparameterset.py, wrappers/python/openmm/app/charmmpsffile.py
Read the E14FAC Coulomb 1-4 scaling factor from CHARMM parameter files (NONBONDED line).
This would enable support of different force field specifications in the CHARMM input format.
=> Read E14FAC Coulomb 1-4 scaling factor in CHARMM files

wrappers/python/openmm/app/metadynamics.py
Moved _syncWithDisk in init before adding table of biases to CustomCVForce so that loaded biases are included in the biasing potential.  Addresses issue #3051.
=> Include biases loaded from disk in CustomCVForce during Metadynamics initialization

platforms/cuda/src/kernels/findInteractingBlocks.cu
Fixes #3029.
This fixes a very rare error related to the single pairs optimization, which was reenabled in #2863.  It doesn't know in advance how many single pairs there will be.  So it allocates an amount of memory that it hopes will be enough.  If it ever turns out not to be, it cancels that force evaluation and allocates a new, larger array for it.
Due to an off by one error, if the number of single pairs was *exactly* equal to the number it allocated space for, the last few entries in the list wouldn't get recorded properly.
=> Fixed rare error related to single pairs

wrappers/python/openmm/app/metadynamics.py
The current code would produce incorrect results, if the force group `31` is already assigned and the metadynamics force is added.
=> Correctly use the force group for the metadynamics force

wrappers/python/src/swig_doxygen/swig_lib/python/exceptions.i
The Python wrapper already released the GIL when calling `step()` or `minimize()`, but not `getState()`.  This matters for two reasons.  First, it allows another Python thread to run while OpenMM is working.  Second, it's necessary for the PyTorch plugin.  Apparently the latest version of libtorch throws an exception if you try to do certain operations while holding the GIL.
=> Release GIL when calling getState()

tests/TestVectorizeGeneric.h
Fixes #3033.  For some reason, the compiler being used there seems to require an extra `#include` that isn't required on other compilers.
=> Fix compilation error in test

plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.h, plugins/amoeba/platforms/cuda/src/kernels/amoebaGk.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoleElectrostatics.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoleInducedField.cu, plugins/amoeba/platforms/cuda/src/kernels/multipolePme.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoles.cu, plugins/amoeba/platforms/cuda/src/kernels/pmeMultipoleElectrostatics.cu, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.h
This includes a lot of minor cleanups to the CUDA implementation of AmoebaMultipoleForce to make things a little cleaner and more similar to the HIPPO implementation.  I also removed the obsolete SOR code that hasn't been used in years.
=> Cleanup to AmoebaMultipoleForce

wrappers/python/openmm/app/charmmpsffile.py, wrappers/python/tests/TestCharmmFiles.py
When viewing a PDB generated from some CHARMM files earlier, I noticed that the unitcell was orthorhombic even after setting a triclinic box up via the `setBox` function.  Unless I'm misunderstanding, the problem is that the orthorhombic `setUnitCellDimensions` was being called on the underlying topology object so I switched it.  The test case in this PR provides a MWE.
=> Fix PSF setBox function for Triclinic case

platforms/common/src/kernels/ewald.cc
The error was introduced by #3073.  It caused an error compiling a kernel when using Ewald on a GPU that doesn't support 64 bit atomics.
=> Fixed compilation error on low end GPUs

docs-source/api-python/CMakeLists.txt
This fixes one part of #3126.  For some reason the dependency was commented out.
=> Building Python API docs automatically builds the API first

wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
This implements a new feature described in https://github.com/openmm/openmmforcefields/pull/156#issuecomment-870799618.  It allows overriding the standard logic for matching templates to residues.
=> Allow custom template matchers for residues

wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
This allows force fields to include an `<InitializationScript>` tag that gets executed when the file is loaded.  This is needed to let GLYCAM be fully self contained.  See https://github.com/openmm/openmmforcefields/pull/156#issuecomment-870799618 for details.
For the moment, I'm leaving this as an undocumented feature and treating it as part of the internal implementation of GLYCAM.  That way we can change it in the future without breaking users' code.  If we decide later we want to make it a fully supported feature, we can document it then.
For GLYCAM, add the following tag to the XML file:
```xml
<InitializationScript>
class GlycamTemplateMatcher(object):
def __init__(self, glycam_residues):
self.glycam_residues = glycam_residues
def __call__(self, ff, residue):
if residue.name in …
```
=> Support initialization scripts in force fields

openmmapi/include/openmm/NonbondedForce.h, openmmapi/src/NonbondedForce.cpp, openmmapi/src/NonbondedForceImpl.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, serialization/src/NonbondedForceProxy.cpp, serialization/tests/TestSerializeNonbondedForce.cpp, tests/TestNonbondedForce.h
This lets you use a NonbondedForce only for the reciprocal space calculation, while using a CustomNonbondedForce to compute the direct space part in a nonstandard way.  This will be useful for #3166.
cc @dominicrufa @zhang-ivy
=> Allow disabling the direct space calculation in NonbondedForce

openmmapi/include/openmm/internal/ContextImpl.h
Whenever a `ContextImpl` object is destroyed, it calls `contextDestroyed` which deletes the `platformData`, thus corrupting all copies of the object that might have been created, because all the `platformData` pointers in copies are now dangling. The same happens to pointers in `forceImpls`. Therefore, it should be impossible to copy `ContextImpl`.
I got bitten by this after accidentally passing a `ContextImpl` object by value into a function, which deleted the `platformData` after it returned. It wasn't trivial to track down, hence the motivation to propose this change.
=> Deleted the default copy-constuctor for ContextImpl.

docs-source/usersguide/library/02_compiling.rst
This is a major reorganization and rewrite of the chapter on compiling from source.  It hopefully should now be simpler and easier to follow, as well as being accurate and up to date.
=> Update instructions on compiling from source

.github/workflows/CI.yml
Previously, the 404 checker run on the docs in CI would fail when a document has a relative link to a page in one of the other documentation sites. This is because linkinator assumed the web server was running from each site's root directory, so relative paths further up the file hierarchy were errors. This PR fixes this behaviour and should hopefully fix the documentation check failures.
The failure is confirmed spurious by the fact that the sidebar links work correctly on the [development documentation](http://docs.openmm.org/development/userguide/)
=> Accept relative links between documentation sites

wrappers/python/openmm/app/gromacstopfile.py
Fixes #3096.  When adding exclusions, it was specifically checking whether they were in ascending order.  I have no idea why I originally wrote it that way in #482!  I can't find anything in the documentation that suggests it should work that way.  It would make sense if top files included duplicate exception records with both orders, but the files I looked at don't.
cc @Ziz1
=> Fixed error adding exclusions from Gromacs top file

wrappers/python/openmm/app/topology.py
Pdbfixer attempts to add di-sulfide bonds to any pair of CYS "S" atoms that are less than 3 A. This procedure fails when multiple such bonds are assigned to a given atom. 
Here we rectify this issue by a greedy algorithm: Atom I is chosen to be bonded to `argmin(distance([:I-1, I])` over all candidate di-sulfide bonds. This procedure will not generally result in a set of minimal distance di-sulfide bonds, but will fix the "tri-sulfide bond" problem. Fixing the more general case would require a solution to global constraint satisfaction problem.
See https://github.com/openmm/openmm/issues/3179 for more context.
**Legal**
This patch is provided under the CC0 license (https://creativecommons.org/share-your-work/public-domain/cc0/).
This is not an officially-supported Google product. It is …
=> Remove tri-sulfite bond formation.

platforms/opencl/include/OpenCLContext.h, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLParallelKernels.cpp, platforms/opencl/src/kernels/utilities.cl
This addresses the "OpenCL is broken too" part of #3039 
The `VerletIntegrator` provides incorrect results on OpenCL platform when launched on multiple GPUs. This is because it uses 64-bit fixed point `longForceBuffer` array which isn't updated properly by `OpenCLParallelCalcForcesAndEnergyKernel`.
I believe this was introduced by #2488 so everyone who might've used OpenCL on multiple GPUs since then would have been affected by this.
=> Fix for incorrect behavior of OpenCL platform on multiple GPUs.

docs-source/usersguide/application/02_running_sims.rst, wrappers/python/openmm/app/data/implicit/gbn.xml, wrappers/python/openmm/app/data/implicit/gbn2.xml, wrappers/python/openmm/app/data/implicit/hct.xml, wrappers/python/openmm/app/data/implicit/obc1.xml, wrappers/python/openmm/app/data/implicit/obc2.xml, wrappers/python/setup.py, wrappers/python/tests/TestForceField.py
This provides an implementation of GBSA implicit solvent that works with current force fields.  Like the old Amber99 implementation you just include an extra XML file.  But instead of containing parameters, it contains a script that invokes existing code to select parameters.
So far I've written the OBC2 implementation.  Modifying it for other versions will be trivial.
A question is where to put the files and how to present them.  Right now I have them in a folder that's just called `implicit`, indicating that they aren't specific to any force field.  That's kind of true.  They should work with any force field as long as we have parameters for all necessary elements.  But they came from Amber, and I don't know how valid it is to use them with other force fields.  If you used the Amber GB …
=> Implicit solvent for modern force fields

libraries/lepton/src/Operation.cpp, platforms/common/src/CommonKernels.cpp
Fixes #3111.
Lepton now implements the derivatives of min() and max() using the select() function.  This makes it very slightly more robust, since there's one less opportunity for a nan to propagate up.
=> Simplified derivatives of min() and max()

wrappers/python/openmm/app/forcefield.py, wrappers/python/openmm/app/internal/argtracker.py, wrappers/python/tests/TestForceField.py, wrappers/python/tests/TestIntegrators.py
Fixes #97.
The main benefit of this is to detect typos.  In a few cases it can also detect standard arguments that were provided when they didn't make sense, but most of the time it can't do that.
=> Check for keyword args to createSystem() that are never used

openmmapi/include/openmm/internal/CustomNonbondedForceImpl.h, openmmapi/src/CustomNonbondedForceImpl.cpp, platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp
Fixes #3229.  This PR includes three different optimizations.
1. Any part of the computation that doesn't depend on context parameters is precomputed and saved.  It only needs to be repeated if you call `updateParametersInContext()`, not if you change a global parameter.
2. The computation of integrals is parallelized across all the cores in your CPU.
3. On the CUDA and OpenCL platforms, the computation is driven by a separate worker thread so it can be done at the same time the GPU is computing the forces.
I can't give a single number for how much faster it is.  That depends both on the details of your system and on the relative speed of your CPU and GPU.  In the best case where computing the coefficient on the CPU takes less time than computing the forces on the GPU, changing a global …
=> Optimized computing long range correction for CustomNonbondedForce

platforms/common/src/kernels/monteCarloBarostat.cc, platforms/reference/src/SimTKReference/ReferenceMonteCarloBarostat.cpp, tests/TestMonteCarloAnisotropicBarostat.h
Fixes #2898.
Previously every time a barostat attempted a step, it would begin by translating all the molecules into a single periodic box.  I'm not sure why I originally wrote it that way.  I thought it was necessary, but looking at it now I can't see any reason it would be.  I removed the code to do the translation and all the tests still pass.
=> Barostat does not translate into a single periodic box

wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/src/swig_doxygen/swig_lib/python/extend.i, wrappers/python/tests/TestPickle.py
Implements #1911.
If you define a Python class that extends a C++ Force or Integrator class, `copy()` and `deepcopy()` now work better than before.  They return an instance of the correct Python class, not the C++ parent class, and any fields defined in Python get copied.
This appears to work correctly in my tests, but there's a lot of subtlety in the interaction between C++ and Python.  Please watch for any errors related to this and report anything you find.  Also remember that this only affects copying.  If you serialize an object to XML and deserialize it, you'll still get the C++ class.  The XML representation doesn't have enough information to reconstruct an instance of a Python class.
=> copy() works better for Python subclasses of C++ classes

platforms/common/include/openmm/common/ComputeContext.h, platforms/common/include/openmm/common/ContextSelector.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/ComputeContext.cpp, platforms/common/src/IntegrationUtilities.cpp, platforms/cuda/include/CudaContext.h, platforms/cuda/src/CudaArray.cpp, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaParallelKernels.cpp, platforms/cuda/tests/TestCudaFFT3D.cpp, platforms/cuda/tests/TestCudaNonbondedForce.cpp, platforms/cuda/tests/TestCudaRandom.cpp, platforms/cuda/tests/TestCudaSort.cpp, plugins/amoeba/platforms/common/src/AmoebaCommonKernels.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/drude/platforms/common/src/CommonDrudeKernels.cpp, plugins/rpmd/platforms/common/src/CommonRpmdKernels.cpp
This reworks management of CUDA contexts as suggested in #3256.  Instead of calling `setAsCurrent()` on a ComputeContext to make it the current context, you call `pushAsCurrent()`.  You then have to call `popAsCurrent()` when you're done.  To simplify that process, I created a ContextSelector class that does it automatically.  Where before you would have written
```c++
cc.setAsCurrent();
```
you now write
```c++
ContextSelector selector(cc);
```
The constructor for the object pushes the context onto the stack.  Then when it goes out of scope, its destructor pops it back off again.
=> Use cuCtxPushCurrent() and cuCtxPopCurrent() for selecting CUDA context

devtools/forcefield-scripts/processTinkerForceField.py, openmmapi/src/HarmonicBondForceImpl.cpp, wrappers/python/openmm/app/data/amoeba2018.xml, wrappers/python/openmm/app/data/amoeba2018_gk.xml
Fixes #3304.  This fixes two problems.  First, it did not specify that `rigidWater` should default to `False` for AMOEBA.  Second, AMOEBA uses a harmonic bond with a negative force constant for the Urey-Bradley term on water, and that was being caught as invalid.
=> Fix errors with AMOEBA 2018

platforms/cuda/src/CudaKernels.cpp
I'm hoping this will address #3310.  The C++ code was declaring a variable as type bool, then passing it to a kernel that interpreted it as an int.  Since false is normally represented by 0 and true by a nonzero value, that ought to work, but it's possible some compilers would implement it in a way that didn't.
=> Fixed an inconsistency in data type

wrappers/python/openmm/app/gromacstopfile.py, wrappers/python/tests/TestGromacsTopFile.py
Fixes #3334.  I also added a deprecation notice indicating that implicit solvent support with GromacsTopFile will be removed in a future release, since Gromacs dropped support for it a couple of years ago.  See #3006.
=> Fixed error in computing charges for Gromacs implicit solvent

docs-source/usersguide/library/02_compiling.rst
I added some instructions on how to test local build and how to use it with other conda packages, which I believe must be a common case scenario.
Specifically, I changed the order of `make test` to test the local build before install (which I think it is the correct logical order) and added some instructions on how to use the local build of `openmm` alongside conda tools/packages that need it and could potentially overwrite the local build installation.
=> More detailed instructions for using local builds.

platforms/cuda/src/CudaContext.cpp
This fixes an error that was introduced in #3258.  We didn't have a valid context set while calling `cuProfilerStop()`.  It didn't actually cause any problems as far as I can tell, but it caused `cuda-memcheck` to report lots of errors.
=> Fixed incorrect context handling

platforms/common/src/kernels/nonbondedParameters.cc, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/tests/CudaTests.h, platforms/cuda/tests/TestCudaNonbondedForce.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/tests/TestOpenCLNonbondedForce.cpp
This fixes some errors that were encountered when parallelizing a simulation across multiple GPUs.
- If you used LJPME, it would throw an exception due to an error in the kernel compiler.
- If you applied an offset parameter to an exception, it would produce incorrect results.
- In certain situations, `updateParametersInContext()` would report an error claiming the set of exceptions had changed, even though it really hadn't.
=> Fixed errors when running on multiple GPUs

platforms/cuda/include/CudaParallelKernels.h, platforms/cuda/src/CudaParallelKernels.cpp
cc @aizvorski @dmclark17
I'm trying to make the improvements discussed in #3333.  So far I've done the first part, using multiple streams to broadcast the positions.  Unfortunately, I don't have any hardware to properly test it on.  The best I can do is "parallelize" the computation across multiple contexts on a single GPU.  That's hopefully enough to verify I haven't broken anything, but it doesn't tell us anything about performance.
Can you try this out?  If you can check the following it would be a big help.
- Does it affect performance?  If so, how?
- Try running it in the profiler.  How does it look?  Hopefully we should now see multiple memcpy operations happening in parallel, and also each GPU should begin computing as soon as it has the positions, even if the transfer to another …
=> Improve performance running on multiple GPUs

docs-source/usersguide/application/05_creating_ffs.rst
Fixes #3360.  I just revised one example to more clearly show that `<Patch>` tags go inside the `<Patches>` block.
=> Minor clarification to manual

devtools/ci/gh-actions/scripts/install_amd_opencl.sh
The AMD OpenCL build has been failing for a while.  I'm trying to get it working again.
The M1 Mac build is also failing for reasons I don't understand.  Here's the relevant part of the log:
```
Ensuring installer...
Can we use bundled Miniconda?
Can we download a custom installer by URL?
... will download a custom installer by URL.
Ensuring Installer...
Checking for cached Miniforge3-MacOSX-arm64.sh@0.0.0-a2d8cad428e2d23deaa456f3311b6d36ac7f3da6dde71365e519b8e85c586e5f...
Found Miniforge3-MacOSX-arm64.sh cache at /Users/lilmac/Projects/GH-Runner/actions-runner/_work/_tool/Miniforge3-MacOSX-arm64.sh/0.0.0-a2d8cad428e2d23deaa456f3311b6d36ac7f3da6dde71365e519b8e85c586e5f/x64!
Running installer...
Error: Unknown installer extension: 
```
@mikemhenry do you have any idea what the problem is?
=> Try to fix errors setting up CI builds

platforms/cuda/include/CudaSort.h, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/CudaSort.cpp, platforms/cuda/src/kernels/sort.cu, platforms/cuda/tests/TestCudaSort.cpp, platforms/opencl/include/OpenCLSort.h, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/OpenCLSort.cpp, platforms/opencl/src/kernels/sort.cl, platforms/opencl/tests/TestOpenCLSort.cpp
Fixes #3357.  This improves performance with very large systems where it can't use the short list version of the kernel.  It's especially important for multi-GPU simulations.
I benchmarked it on 1 to 4 A100s.  Here are the speeds for cellulose (about 400,000 atoms) with CUDA.
| GPUs | Original | Optimized |
| --- | --- | --- |
1 | 105.3 | 111.5
2 | 164.4 | 173.5
3 | 193.1 | 206.9
4 | 210.7 | 222.2
And for STMV (about 1 million atoms).
| GPUs | Original | Optimized |
| --- | --- | --- |
1 | 32.2 | 33.3
2 | 51.1 | 53.1
3 | 61.1 | 65.6
4 | 71.1 | 73.6
Here is cellulose with OpenCL.
| GPUs | Original | Optimized |
| --- | --- | --- |
1 | 69.2 | 70.1 | 
2 | 83.8 | 85.6 | 
3 | 92.8 | 95.2 | 
4 | 90.3 | 90.9 |
And STMV with OpenCL.
| GPUs | Original | Optimized |
| --- | --- | --- |
1 | 18.2 | …
=> Optimize sorting of non-uniformly distributed data

wrappers/generateWrappers.py
There are some methods with `long long` types, which were introduced in #3248. However, Fortran cannot recognize such type, making compiling errors with Fortran code.
I have added the translation for `long long` to `integer*8` in the translation list. Making the Fortran wrappers compatible.
=> Add Fortran type translation for `long long`

platforms/common/src/kernels/nonbondedParameters.cc, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
Fixes #3392.  If you had exception parameter offsets but no particle parameter offsets, it would read from uninitialized memory which could potentially lead to a crash.  In practice the error only happened on AMD (and possibly Intel?), because NVIDIA initialized the memory to all zeros.
=> Fixed uninitialized memory access

openmmapi/src/MonteCarloAnisotropicBarostat.cpp, openmmapi/src/MonteCarloBarostat.cpp, openmmapi/src/MonteCarloFlexibleBarostat.cpp, openmmapi/src/MonteCarloMembraneBarostat.cpp
Fixes https://github.com/openmm/openmm/issues/3408 by allowing the barostat frequency to be 0 for `MonteCarloBarostat`, `MonteCarloFlexibleBarostat`, `MonteCarloMembraneBarostat`, and `MonteCarloAnisotropicBarostat`.
=> Fix barostat frequency check

wrappers/python/src/swig_doxygen/swig_lib/python/exceptions.i
Release the GIL when calling `OpenMM::Context::setVelocitiesToTemperature`, for the same reason as https://github.com/openmm/openmm/pull/3061
Fix https://github.com/openmm/openmm-torch/issues/61.
=> Fix GIL for OpenMM::Context::setVelocitiesToTemperature

platforms/common/include/openmm/common/ArrayInterface.h, platforms/common/include/openmm/common/ComputeArray.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/ComputeArray.cpp, platforms/common/src/IntegrationUtilities.cpp, platforms/cuda/include/CudaArray.h, platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaArray.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/opencl/include/OpenCLArray.h, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLArray.cpp, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/findInteractingBlocks.cl, plugins/amoeba/platforms/common/src/AmoebaCommonKernels.cpp
Fixes #3414.  There were a few ways you could get invalid memory access on the GPU if the number of tiles in the neighbor list became too large.  In practice, that happened if you were simulating a very large system, and then it blew up.  You would end up with atoms scattered at effectively random positions through the periodic box, so almost every atom block interacted with almost every other.  That could lead to various numbers exceeding the bounds of a signed int, which led to the invalid memory access.
=> Fixed potential invalid memory access

docs-source/api-c++/Doxyfile.in, plugins/amoeba/wrappers/Doxyfile.in, wrappers/Doxyfile.in, wrappers/python/src/swig_doxygen/doxygen/Doxyfile.in
Without this restriction in the patterns, the compilation fails if the project folder has parent folders called "tests", "internal" or other words used in these generic patterns.
=> Remove generic patterns in Doxyfiles

docs-source/usersguide/application/05_creating_ffs.rst, openmmapi/include/openmm/CustomNonbondedForce.h, openmmapi/include/openmm/internal/CustomNonbondedForceImpl.h, openmmapi/src/CustomNonbondedForce.cpp, openmmapi/src/CustomNonbondedForceImpl.cpp, platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/customNonbondedComputedValues.cc, platforms/cpu/include/CpuCustomNonbondedForce.h, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuCustomNonbondedForce.cpp, platforms/cpu/src/CpuKernels.cpp, platforms/reference/include/ReferenceCustomNonbondedIxn.h, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceCustomNonbondedIxn.cpp, serialization/src/CustomNonbondedForceProxy.cpp, serialization/tests/TestSerializeCustomNonbondedForce.cpp, tests/TestCustomNonbondedForce.h, wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
Implements #3368.  You can call `addComputedValue()` on a CustomNonbondedForce to add a computed value.  It is computed for each particle based on the global and per-particle parameters, and can appear in the energy expression.
=> CustomNonbondedForce supports computed values

wrappers/python/openmm/app/data/pdbNames.xml
Fixes #3439.  This adds a few more names to our list of recognized nonstandard ones.
=> Support some nonstandard names generated by PyMol

wrappers/python/openmm/app/internal/amber_file_parser.py, wrappers/python/tests/TestAmberInpcrdFile.py
With the release of scipy `1.8.0` some deprecation warning showed up for `openmm` when running tests on a downstream project:
```
/home/sroet/miniconda3/envs/python3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py:1377: DeprecationWarning: Please use `NetCDFFile` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.
from scipy.io.netcdf import NetCDFFile
```
This solves them for all the `scipy.io` that I could find with the `grep -r -n scipy.io --include='*.py'`
=> resolve scipy 1.8.0 io.netcdf deprecation warning

platforms/common/src/ComputeContext.cpp
Fixes #3447.  The error occurred when you called `updateParametersInContext()`, and the changed parameters caused the previous atom ordering to no longer be valid.  In that case, if you were using mixed precision, the array of corrections to positions could get corrupted.
=> Fixed error when invalidating molecules

wrappers/python/src/swig_doxygen/swig_lib/python/exceptions.i
Release the GIL when calling `OpenMM::CustomCVForce::getCollectiveVariableValues`, for the same reason as https://github.com/openmm/openmm/pull/3061 and https://github.com/openmm/openmm/pull/3424
Fix https://github.com/openmm/openmm-ml/issues/22.
=> Fix GIL for OpenMM::CustomCVForce::getCollectiveVariableValues

.github/workflows/CI.yml
This should fix the failing docs builds.  They are caused by a [bug in recent versions of linkinator](https://github.com/JustinBeckwith/linkinator/issues/374), so I pinned it to a slightly older version that doesn't have the bug.  Hopefully they will eventually fix it, and then we can remove the pin.
=> Pin linkinator to 3.0.0

wrappers/python/openmm/__init__.py
This revises how the library path is specified on Windows, as suggested in https://github.com/conda-forge/openmm-feedstock/pull/70#issuecomment-1046253738.
cc @jaimergp @isuruf
=> Call add_dll_directory() as context manager

wrappers/python/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
=> Added option for box shape when building solvent boxes

olla/include/openmm/kernels.h, openmmapi/include/openmm/internal/ContextImpl.h, openmmapi/src/ContextImpl.cpp, platforms/common/include/openmm/common/IntegrationUtilities.h, platforms/common/src/IntegrationUtilities.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, plugins/drude/openmmapi/include/openmm/DrudeLangevinIntegrator.h, plugins/drude/openmmapi/include/openmm/DrudeNoseHooverIntegrator.h, plugins/drude/openmmapi/src/DrudeHelpers.cpp, plugins/drude/openmmapi/src/DrudeLangevinIntegrator.cpp, plugins/drude/openmmapi/src/DrudeNoseHooverIntegrator.cpp, plugins/drude/platforms/reference/src/ReferenceDrudeKernels.cpp, plugins/drude/tests/TestDrudeLangevinIntegrator.h, plugins/drude/tests/TestDrudeNoseHoover.h, wrappers/python/openmm/app/statedatareporter.py, wrappers/python/src/swig_doxygen/swigInputConfig.py
This is part of #2513.  I added a `computeSystemTemperature()` method to DrudeLangevinIntegrator and DrudeNoseHooverIntegrator.  It returns the temperature of the part of the system coupled to the main heat bath, ignored the internal motion of Drude particle pairs that is couple to a lower temperature heat bath.  StateDataReporter checks for that method and uses it to compute the temperature it reports.
=> Improved temperature reporting for Drude particles

wrappers/python/openmm/app/amberprmtopfile.py
May resolve #3488 if my diagnosis is correct
The repro in the linked issue becomes:
```python3
In [1]: from openmm import app, unit
In [2]: sys = app.AmberPrmtopFile("gbsa.tmp.prmtop").createSystem(
...:     nonbondedMethod=app.CutoffNonPeriodic,
...:     implicitSolvent=app.OBC2,
...:     switchDistance=0.7 * unit.nanometer,
...: )
/Users/mwt/miniconda3/envs/openff-interchange-env/lib/python3.8/site-packages/openmm/app/internal/amber_file_parser.py:1102: UserWarning: Non-optimal GB parameters detected for GB model OBC2
warnings.warn(
In [3]: import openmm
In [4]: for force in sys.getForces():
...:     if type(force) == openmm.NonbondedForce:
...:         print(force.getSwitchingDistance())
0.7 nm
=> Fix possible bug in `AmberPrmTopFile.createSystem()`

.github/workflows/CI.yml
The docs build has been failing because linkinator incorrectly reports https://www.pnas.org/content/105/17/6290 as being broken.  I [reported the issue](https://github.com/JustinBeckwith/linkinator/issues/386), but so far haven't received any reply.  For now, I'm telling it to skip checking any URLs at www.pnas.org.
=> Workaround for error in finding broken URLs

devtools/ci/gh-actions/conda-envs/build-ubuntu-latest.yml, libraries/lepton/include/lepton/CompiledExpression.h, libraries/lepton/src/CompiledExpression.cpp
This is another optimization to JIT compilation of custom expressions on the CPU.  Simulating DHFR with CHARMM36 on the CPU platform, it increases the speed from 7.4 ns/day to 10 ns/day.  There may also be some benefit for #3361.
=> Optimized computing powers in CompiledExpression

wrappers/python/openmm/app/dcdfile.py
Fixes #3507.  This should produce DCD files that are read correctly by cpptraj.  @drroe does this look correct to you?
=> DCDFile reports CHARMM version 21 instead of 24

wrappers/python/openmm/app/internal/pdbstructure.py, wrappers/python/openmm/app/pdbfile.py, wrappers/python/tests/TestPdbFile.py
Fixes #3501.  This is the format used by VMD.  When an atom ID passes 99999 or a residue ID passes 9999, it switches to hex.
cc @billswope @swails
=> Use hex for large atom and residue IDs in PDB files

openmmapi/src/CompoundIntegrator.cpp, openmmapi/src/ContextImpl.cpp
This fixes a bug that caused `TestReferenceCompoundIntegrator`, `TestSerializeState` and `TestSerializeNoseHooverIntegrator` to fail (maybe some others too).
Interestingly enough, for me it segfaults when compiled with `-O3`, but not when compiled with `-O0`. And it's very surprising that this is the case, because one would think that dereferencing `NULL` would trigger a segfault in both cases.
The nature of the `TestSerializeState` bug is that the
```cpp
platform->getPropertyNames();
```
is invoked before `platform` is checked for `NULL`. The `TestSerializeNoseHooverIntegrator` invokes the `Context` constructor without specifying a platform, so it triggers this bug.
And the nature of the `TestReferenceCompoundIntegrator` bug is that `CompoundIntegrator::cleanup` doesn't erase the ptr to …
=> Fix for nullptr dereferencing that caused test failures

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/nonbonded.cu
This removes obsolete code that existed to support very old GPUs (pre-Kepler) that didn't support shuffle instructions.  The code had been broken for a while, but no one seems to have noticed.
=> Removed code for CUDA devices without shuffle

wrappers/python/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
This addresses two issues that were introduced in #3480.  First, it revises the method for selecting box size.  When building a water box around a very small solute, it will never make the box width less than `2*padding`.
Second, it fixes a bug when building a non-rectangular solvent box.  Previously it set the box vectors correctly, but still added enough water to fill a rectangular box.
Fixes #3502.
=> Improvements to choosing box size

tests/TestParser.cpp
These tests were supposed to have been included in #3520 but accidentally got left out.
=> Added a few Lepton tests

wrappers/python/openmm/app/forcefield.py
Fixes #3557.
Instead of generating error messages that index the residue within the entire topology when a residue template is not found:
```
ValueError: No template found for residue 1168 (ASN). The set of atoms matches ASN, but the bonds are different.
```
we now generate a more useful error message:
```
ValueError: No template found for chainid <G>, resid <213>, resname <ASN> (residue index in topology 1168). 
The set of atoms matches ASN, but the bonds are different.
```
=> Generate more informative error message if residue template not found

platforms/cuda/src/CudaParallelKernels.cpp
Fixes #3535.  This addresses a race condition when parallelizing a simulation across multiple GPUs, but the System includes a force that is not parallelized (such as CustomCentroidBondForce).
=> Fixed race condition with multiple GPUs

wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/tests/TestAPIUnits.py
Fixes #3562.  It was broken by a change in behavior in Doxygen 1.9.2.
=> Fixed return type of getTabulatedFunction()

platforms/cuda/include/CudaContext.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaEvent.cpp, platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/CudaParallelKernels.cpp
Fixes #3547.  If the user specifies "UseBlockingSync" when creating a Context, the `CU_EVENT_BLOCKING_SYNC` option is enabled for events.
cc @dmclark17
=> Use blocking sync when creating events

platforms/cpu/src/CpuKernels.cpp, platforms/reference/src/ReferenceKernels.cpp
Fixes #3570.  Many integrators apply a half step offset to the velocities when computing kinetic energy.  After updating the velocities, it needs to apply constraints to them to make sure the updated velocities still respect the constraints.
LangevinMiddleIntegrator does not apply an offset, but on the CPU and Reference platforms it was still applying constraints.  In the example from that issue, the velocities being loaded into the Context did not respect the constraints.  This led to different kinetic energies being reported by different platforms.
I changed Reference and CPU to behave the same way OpenCL and CUDA do: if no offset is applied, do not apply constraints.  That means if you call `setVelocities()` or `setState()`, the kinetic energy will exactly match the velocities you set, …
=> Fixed inconsistency in computing kinetic energy

platforms/cpu/include/CpuCustomNonbondedForce.h, platforms/cpu/include/CpuCustomNonbondedForceFvec.h, platforms/cpu/include/CpuNeighborList.h, platforms/cpu/include/CpuNonbondedForce.h, platforms/cpu/include/CpuNonbondedForceFvec.h, platforms/cpu/include/CpuPlatform.h, platforms/cpu/src/CpuCustomNonbondedForce.cpp, platforms/cpu/src/CpuCustomNonbondedForceAvx.cpp, platforms/cpu/src/CpuCustomNonbondedForceFvec.cpp, platforms/cpu/src/CpuCustomNonbondedForceVec4.cpp, platforms/cpu/src/CpuGayBerneForce.cpp, platforms/cpu/src/CpuKernels.cpp, platforms/cpu/src/CpuNeighborList.cpp, platforms/cpu/src/CpuNonbondedForce.cpp, platforms/cpu/src/CpuNonbondedForceAvx.cpp, platforms/cpu/src/CpuNonbondedForceAvx2.cpp, platforms/cpu/src/CpuNonbondedForceFvec.cpp, platforms/cpu/src/CpuNonbondedForceVec4.cpp, platforms/cpu/src/CpuPlatform.cpp, platforms/reference/src/ReferenceTabulatedFunction.cpp, tests/TestNonbondedForce.h
Previously, NonbondedForce and CustomNonbondedForce were only vectorized on the CPU platform when using a cutoff.  When not using a cutoff, interactions were computed one at a time.  This PR vectorizes them, which leads to very large speedups (about 2-7x depending on the case).
=> Vectorize nonbonded interactions with no cutoff

.github/workflows/CI.yml
All our Python 3.6 builds have recently begun failing.  It looks to me like `importlib_metadata` no longer supports it.  I believe Python 3.6 is now past its end of support date, and 3.10 has been out for a while now.  This PR updates our CI builds to run on Python 3.7 and 3.10 instead of 3.6 and 3.9.
=> Update Python versions in CI

wrappers/python/openmm/app/internal/customgbforces.py
Fixes #3578.  The `cutoff` and `kappa` arguments are documented to accept either a number or a Quantity, but if you provided a Quantity it threw an exception.
=> Strip units from customgbforce args

wrappers/python/openmm/app/data/pdbNames.xml
This accepts TIP as another synonym for water.  This is the name that's used in the PDB file for the ApoA1 benchmark.  As a result, that benchmark was using SHAKE instead of SETTLE for the waters, which made it very slightly slower.
=> Add another synonym for HOH in PDB files

openmmapi/include/openmm/internal/Messages.h, openmmapi/src/CustomGBForceImpl.cpp, openmmapi/src/CustomHbondForceImpl.cpp, openmmapi/src/CustomManyParticleForceImpl.cpp, openmmapi/src/CustomNonbondedForceImpl.cpp, openmmapi/src/GayBerneForceImpl.cpp, openmmapi/src/Messages.cpp, openmmapi/src/NonbondedForceImpl.cpp, platforms/common/src/ComputeContext.cpp, platforms/cpu/src/CpuKernels.cpp, plugins/amoeba/openmmapi/src/AmoebaMultipoleForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaVdwForceImpl.cpp, plugins/amoeba/openmmapi/src/HippoNonbondedForceImpl.cpp, wrappers/python/openmm/app/dcdfile.py, wrappers/python/openmm/app/forcefield.py, wrappers/python/openmm/app/pdbfile.py, wrappers/python/openmm/app/pdbxfile.py, wrappers/python/openmm/app/statedatareporter.py
When throwing exceptions, include links to relevant FAQ entries in the error messages.
Fixes #3502.
=> Added FAQ links to error messages

wrappers/python/openmm/app/simulatedtempering.py, wrappers/python/tests/TestSimulatedTempering.py
The title more or less explains it all:
This pull request allows simulated tempering to be run in isobaric ensembles using Monte Carlo barostats by adjusting the temperature of the barostat.
fixes #3612
=> Added temperature adjustment to MC barostat for simulated tempering

platforms/common/include/openmm/common/ComputeContext.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/ComputeContext.cpp
Fixes #3661.
The freeze happened if you used multiple GPUs, and the system included a CustomNonbondedForce that used a long range correction.  The problem was introduced by #3236.
=> Fixed freeze when using multiple GPUs

platforms/common/CMakeLists.txt, platforms/cuda/CMakeLists.txt, platforms/opencl/CMakeLists.txt
Installs header files `[Common|Cuda|OpenCL]KernelSources.h`, generated during compilation, in the corresponding include directories.
=> Kernel source headers included in installation

openmmapi/include/openmm/internal/CustomCVForceImpl.h, openmmapi/src/CustomCVForceImpl.cpp, tests/TestCustomCVForce.h
This might or might not be the fix for https://github.com/openmm/openmm-ml/issues/36.  Each Force object reports what atoms it creates bonds between, so all the atoms in a molecule are translated together when applying periodic boundary conditions.  CustomCVForce did not propagate the bond specifications from the Forces it contained.
This only applied to output when calling `getState()` with `enforcePeriodicBox=true`.  There's a different mechanism used to identify molecules when internally translating positions to preserve accuracy.  That mechanism was handled correctly, so it never broke up molecules during normal integration.  It only happened when returning output from `getState()`.
cc @dominicrufa
=> CustomCVForce avoids breaking up molecules

platforms/cuda/src/CudaPlatform.cpp
On recent CUDA versions, this seems to give better performance.  See https://github.com/choderalab/perses/issues/613#issuecomment-1180894126.  Also, given the changes in #3561, this is actually closer to the default behavior in previous releases.
=> UseBlockingSync defaults to false

platforms/common/src/CommonKernels.cpp
Fixes #3726.  When you had two CustomNonbondedForces, both having interaction groups, and both having tabulated functions, it would lead to a kernel compilation error on CUDA and OpenCL.
=> Fixed compilation error with multiple CustomNonbondedForces

platforms/common/include/openmm/common/ComputeContext.h, platforms/common/src/ComputeContext.cpp, platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLNonbondedUtilities.cpp
This is a possible fix for https://github.com/choderalab/perses/issues/613.  See the discussion in https://github.com/choderalab/perses/issues/613#issuecomment-1188474425 and following.
Normally it reorders atoms every 250 steps.  The change here is that if it ever sees the size of the neighbor list has increased by more than 10% since the last reordering, then it immediately forces a new reordering to try to bring it back down.  However, it still will never reorder more often than every 25 steps.  That's to reduce the risk of catastrophic slowdowns in pathological cases.
This code should be considered experimental.  Before we decide whether to merge it or try a different approach instead, we need to thoroughly test it to see how it affects performance on all the relevant use cases.
cc …
=> Improved logic for deciding when to reorder atoms

wrappers/python/openmm/app/modeller.py
Regarding the discussion [Add support for other water models for Modeller.addSolvent #3752](https://github.com/openmm/openmm/issues/3752), I thought it would be helpful to update the `Modeller.addSovlent` docstring.
=> update modeller.addSolvent docstring

platforms/common/src/CommonKernels.cpp
JAMA::Eigenvalue can run in an infinite loop if there are upstream NaN in atom positions. Throwing an exception is probably preferable. This checks for NaN directly before the JAMA call.
See: #3034
=> Detect NaN to avoid infinite loop in JAMA::Eigenvalue

CONTRIBUTING.md
I just encountered this while reading through the contributing guidelines, and thought it might be important to fix since it's public documentation. I have a bad habit of pointing out typos, so for less important cases like typos in source code comments I probably won't make a PR.
If this is discouraged because it triggers integration tests, please let me know so I can avoid repeating something similar in the future.
=> Minor spelling nit

wrappers/python/openmm/mtsintegrator.py, wrappers/python/tests/TestIntegrators.py
Previously, `openmm.MTSLangevinIntegrator` would use an effective collision rate that is too large when there were multiple steps, since every substep used the outer timestep instead of the inner substep timestep to apply the friction.
This PR corrects this, using a fix suggested by Charlie Matthews (@c-matthews) in #3790.
=> Fix #3790: Collision rate for MTS BAOAB Langevin integrator now correctly accounts for number of substeps

docs-source/usersguide/application/05_creating_ffs.rst
The chapter on writing force fields didn't include a decription of this tag.
=> Document <LennardJonesForce> tag

platforms/opencl/src/OpenCLContext.cpp
This initialization is needed to prevent segfault during object destruction in certain circumstances (e.g., when a `Force` is changed before calling `Context.reinitialize()` and this change causes the corresponding `ForceImpl` to throw an exception).
=> Initialize pinnedBuffer at OpenCLContext creation

platforms/opencl/src/OpenCLBondedUtilities.cpp, platforms/opencl/src/kernels/common.cl, platforms/opencl/src/kernels/nonbonded.cl
Fixes #3855.  In some (but not all) cases, this produced compilation errors on GPUs that didn't support 64 bit atomics (mostly low end embedded ones).  We need to test this on as many OS/GPU combinations as possible.
=> Fix compilation error in OpenCL kernels on some platforms

openmmapi/src/MonteCarloBarostat.cpp, openmmapi/src/MonteCarloFlexibleBarostat.cpp, openmmapi/src/MonteCarloMembraneBarostat.cpp, plugins/rpmd/openmmapi/src/RPMDMonteCarloBarostat.cpp
Negative pressure is well defined and can be useful.  I got a report from someone that this check broke their workflow.
=> Remove checks for negative pressure

openmmapi/src/LocalEnergyMinimizer.cpp, tests/TestLocalEnergyMinimizer.h
Fixes #3884.  This addresses an obscure situation.  Normally we don't allow a constraint to involve a massless particle.  But if both particles connected by a constraint are massless we do allow it, since the constraint will just be ignored.  That makes it easy to immobilize whole molecules without worrying about what constraints they contain.  In that situation, the minimizer was incorrectly enforcing the constraint rather than ignoring it.
=> Minimizer does not move constrained massless particles

examples/benchmark.py
This fixes error that were introduced in #3887.  If the Amber benchmarks hadn't already been downloaded, trying to run any of them would produce an exception.
Once this is merged, I'll build an updated release candidate package.
=> Fixed exceptions in benchmark script

wrappers/python/src/swig_doxygen/swigInputConfig.py
Fixes #3921.  If you called `getParticleTypeParameters()` or `getTypePairParameters()`, it would throw an exception due to the number of return values being specified incorrectly.
=> Fixed errors in Python wrapper for AmoebaVdwForce

platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/kernels/utilities.cu, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/kernels/utilities.cl
This reduces the overhead of evaluating the energy on the CUDA and OpenCL platforms.  If you're doing a lot of energy evaluations for a very small system or inexpensive force, this can significantly improve performance.  In most other cases the effective is negligible.
=> Optimized reducing energy

wrappers/python/openmm/app/forcefield.py
As described in #3897 , this pr aims to avoid the potential problem of over-catching errors to omit errors when parsing the xml files of the Amoeba forcefield.
I'm unsure if I need to add unit tests related to the incorrect xml node attributes. Because there are so many possibilities for errors, I suspect that we probably don't need unit tests to ensure that error raises properly.
This will close #3897 .
=> fix: py Interface omit errors in xml attributes.

platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/reference/include/ReferenceCustomCVForce.h, platforms/reference/src/SimTKReference/ReferenceCustomCVForce.cpp
This changes the implementation of CustomCVForce so the expression is evaluated with CompiledExpression instead of the much slower ExpressionProgram.  Most CustomCVForces have fairly simple expressions with just a few CVs, so this doesn't make much difference.  But for ones with complicated expressions that involve lots of CVs, it improves speed a lot.
cc @SalomeRonja
=> Use CompiledExpression for CustomCVForce energy expression

platforms/opencl/include/OpenCLContext.h, platforms/opencl/src/OpenCLContext.cpp
Since we don't have good OpenCL profilers on some platforms, this provides built in profiling using the native profiling API.  To enable it, uncomment the define at the top of OpenCLContext.cpp.  It prints out the data to stdout in a format you can load into a web viewer.
=> Profiling of OpenCL kernels

platforms/opencl/src/OpenCLNonbondedUtilities.cpp
The Apple Metal/MoltenCL backend has strange behavior regarding OpenCL events, causing them to infect any nearby commands. We explicitly flush whenever touching an event, ensuring a smooth command stream.
Refs: #3937
=> [macOS GPU Support] Fix `MTLCommandBuffer` bottlenecks for Apple silicon GPUs

wrappers/python/openmm/app/topology.py
`Topology.bonds()` states that iterates over a tuple of `Atom` objects. While this is technically correct, as the `Bond` class is a named tuple, this also hides the fact, that `Bond` objects also provide the `order` and `type` attributes. Therefore, I propose to change the sentence, so that it uses the capitalized *Bonds* indicating that they are actually objects.
=> Fix misleading documentation of `Topology.bonds`

wrappers/python/openmm/unit/quantity.py
This PR should fix the docstring rendering of `Quantity`, which currently looks the following way: http://docs.openmm.org/latest/api-python/generated/openmm.unit.quantity.Quantity.html#openmm.unit.quantity.Quantity
=> Fix ReStructuredText formatting in docstring

examples/benchmark.py
Fix specifying a device will fail to run when multiple OpenCL platforms are available. Specifying `--verbose` prints the following exception: `Specified DeviceIndex but not OpenCLPlatformIndex. When multiple platforms are available, a platform index is needed to specify a device.`
=> Add OpenCLPlatformIndex to benchmark.py

platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp
Apple GPUs generally work well when you have an even division of their maximum thread count (3072). That is, 768 (1/4) or 1536 (1/2). Something odd like 768+32 or 1536-32 will surely harm performance. Going all the way to 3072 was also bad in [metal-benchmarks](https://github.com/philipturner/metal-benchmarks), where I never exceeded 2816 (92% occupancy). This observation may not apply to other use cases; metal-benchmarks used some very peculiar GPU kernels. For the lower bound, Apple designed their GPU so that 768 threads is a magic number. Going lower will not allocate more registers per thread, going higher will not improve ALU utilization unless arithmetic intensity is low.
Expanding the threadgroup size seems to harm performance on GBSA. However, our benchmark uses only 2489 atoms - …
=> [macOS GPU Support] Tune dispatching of persistent threads for Apple silicon GPUs

wrappers/python/openmm/app/pdbreporter.py, wrappers/python/tests/TestPdbReporter.py
This is a first attempt at a way to output atom subsets with PDBReporter addressing issue #3925
It creates a subset topology and position list with just the specified atoms, similar to [MDTraj](https://www.mdtraj.org/1.9.8.dev0/api/generated/mdtraj.reporters.DCDReporter.html#mdtraj.reporters.DCDReporter).
It then passes the new topology and positions to PDBFile.
=> Add support for writing atom subsets to PDBReporter

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp
It may contain a garbage, and if it is large then updateNeighborListSize does not force reorder atoms after 25 steps, multi-GPU load balancing (for amber20-stmv particularly) uses an initial order splitting work between GPUs suboptimally.
I've noticed a strange behavior for multi-GPU STMV benchmarks on the HIP platform:
1. Amber benchmarks use LocalEnergyMinimizer which sets positions multiple times
2. tilesAfterReorder may have a garbage which can be very large
3. So this check https://github.com/openmm/openmm/blob/master/platforms/cuda/src/CudaNonbondedUtilities.cpp#L428 does not trigger reordering at step 25
4. Multi-GPU load balancing works only during first 200 steps, reordering will happen at step 250
5. So a distribution between GPU is based on blocks of unordered atoms (IIRC there …
=> Initialize tilesAfterReorder with zero

openmmapi/src/LocalEnergyMinimizer.cpp
I originally made this a draft because I'm not entirely sure whether it's a good idea long-term. It solves a symptom of the problem: the current source line prevents people from using custom platforms with OpenMM.
I recently said I would give up making a Metal backend and emulating FP64. Therefore, I spent a significant amount of time building a header, which exposes the Metal Standard Library to OpenCL. <b>Then GPT-4 happened.</b> I want to explain what’s changed and how that relates to this PR.
I learned the reason for the surge in interest around ML potentials: quality approaching DFT, but O(n) scaling. Apple MPSGraph could execute ML potentials trained from DFT simulations, with much higher performance than PyTorch. Simultaneously, the new generative AI models could make porting …
=> Recognize Metal platform

wrappers/python/openmm/app/data/pdbNames.xml
Addressing #4012:
"NHE" is the AMBER standard naming of NH2 termination according to their manual ([here](https://ambermd.org/doc12/Amber19.pdf) page 211 bottom). In OpenMM, although "NHE" shows up in the forcefield XML files (e.g., AMBER ff14SB)
https://github.com/openmm/openmm/blob/3dc2f12ff20efcb609dfa5508431065d2c98d028/wrappers/python/openmm/app/data/amber14/protein.ff14SB.xml#L1900 this end group cannot be recognized by `openmm.app.PDBFile` to create correct bond graphs. When calling `forcefield.createSystem`, there is such error message:
```
(openmm) $ python vacuum_relax.py 
Traceback (most recent call last):
File ".../capped_version/vacuum_relax.py", line 5, in <module>
sys = forcefield.createSystem(pdb.topology)
File "${CONDA_PREFIX}/lib/python3.9/site-packages/openmm/app/forcefi …
```
=> Add support to "NHE" C-terminal caps

platforms/cuda/include/CudaParallelKernels.h, platforms/cuda/src/CudaParallelKernels.cpp, platforms/opencl/src/OpenCLParallelKernels.cpp
This PR makes two changes to load balancing.
1. It initializes the fractions in a way that more evenly distributes the work from the beginning.
2. Previously it only did load balancing during the first 200 steps.  That generally worked, but it was noisy.  Different runs would end up with slightly different distributions of work between the GPUs, which led to performance variations.  This changes it to continue doing load balancing after the first 200 steps, but only every 30 steps to keep the overhead minimal.
I ran a few benchmarks on four A100s.  I repeated each one three times to show the variation between runs.  Here are the speeds for the old version.
|Test|Run 1|Run 2|Run 3|
|---|---|---|---|
apoa1rf|757.216|757.864|767.391
apoa1pme|635.692|688.033|683.12 …
=> Improved load balancing between GPUs

.github/workflows/CI.yml
The runner hasn't worked in over a year, so I'm disabling the build.  @mikemhenry if you can get the runner working again we can reenable it.  Until then, all it does is guarantee that every build will be marked as having failed.
=> Disable M1 build

wrappers/python/openmm/app/modeller.py
Fixes #4023.  If the force field passed to `addMembrane()` used a CustomNonbondedForce (for example, CHARMM36), it would throw an exception.  This fixes it.
=> addMembrane() works with CustomNonbondedForce

openmmapi/include/openmm/internal/ForceImpl.h, openmmapi/include/openmm/internal/NonbondedForceImpl.h, openmmapi/src/CMAPTorsionForceImpl.cpp, openmmapi/src/CustomAngleForceImpl.cpp, openmmapi/src/CustomBondForceImpl.cpp, openmmapi/src/CustomCVForceImpl.cpp, openmmapi/src/CustomCentroidBondForceImpl.cpp, openmmapi/src/CustomCompoundBondForceImpl.cpp, openmmapi/src/CustomExternalForceImpl.cpp, openmmapi/src/CustomGBForceImpl.cpp, openmmapi/src/CustomHbondForceImpl.cpp, openmmapi/src/CustomManyParticleForceImpl.cpp, openmmapi/src/CustomNonbondedForceImpl.cpp, openmmapi/src/CustomTorsionForceImpl.cpp, openmmapi/src/GBSAOBCForceImpl.cpp, openmmapi/src/GayBerneForceImpl.cpp, openmmapi/src/HarmonicAngleForceImpl.cpp, openmmapi/src/HarmonicBondForceImpl.cpp, openmmapi/src/NonbondedForceImpl.cpp, openmmapi/src/PeriodicTorsionForceImpl.cpp, openmmapi/src/RBTorsionForceImpl.cpp, openmmapi/src/RMSDForceImpl.cpp
Fixes #3427.  Once you create a Context, any changes to the System or the Forces it contains should be ignored.  In the case of force groups, they sometimes weren't.
=> Ignore changes to force group after context creation

platforms/common/include/openmm/common/CommonKernels.h
Fixes #4038.
CustomIntegrator needs to keep the values of global variables synchronized between the CPU and GPU.  To do that, it has a boolean flag that tracks whether the values on the GPU are currently valid.  That flag wasn't being initialized, which could sometimes lead to the initial value of a global variable not getting uploaded to the GPU.  It wouldn't get set correctly until the first time an integration step set it.
=> Fixed uninitialized memory error

openmmapi/src/MonteCarloAnisotropicBarostatImpl.cpp, openmmapi/src/MonteCarloBarostatImpl.cpp, openmmapi/src/MonteCarloFlexibleBarostatImpl.cpp, openmmapi/src/MonteCarloMembraneBarostatImpl.cpp, platforms/common/src/CommonKernels.cpp
Fixes #4032.
This fixes an error that was introduced by #4034.  Due to a subtle interaction, rejecting a step could sometimes introduce small errors into positions.
=> Fixed error in barostats

platforms/reference/src/SimTKReference/ReferenceCustomCVForce.cpp
This was causing intermittent test failures on Windows CI.
=> Fixed an incorrectly sized array

platforms/cuda/src/kernels/findInteractingBlocks.cu
I finally found a use for half precision, though it's just for storage, not computation.  This reduces memory bandwidth when building the neighbor list.  For very large systems it can produce a bit of a speedup.  For smaller systems the effect is negligible.  See https://github.com/openmm/openmm/issues/4063#issuecomment-1537514168.
cc @philipturner
=> Store bounding box sizes in half precision

platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/customHbondForce.cc, tests/TestCustomHbondForce.h
I've rewritten the CUDA/OpenCL implementation of CustomHbondForce to be much faster, at least on high end GPUs.  The new version has two advantages.  First, it's much better at distributing the work over many threads.  Second, it only needs to compute each interaction once instead of twice.  On the other hand, it does involve more memory access than the old version.
I haven't attempted to build a neighbor list or anything like that.  It still loops over the full set of O(n^2) interactions.  For large systems where most donor/acceptor pairs are outside the cutoff, there should be room for more speedup by doing that.  I'll leave that for the future if there's demand for it.
=> Faster implementation of CustomHbondForce

platforms/common/include/openmm/common/NonbondedUtilities.h, platforms/common/src/CommonKernels.cpp, platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/nonbonded.cu, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/nonbonded.cl, tests/TestNonbondedForce.h
For very small systems, building the neighbor list takes more time than it saves.  It's better to skip that step and just compute all interactions.  Based on https://github.com/openmm/openmm/issues/4065#issuecomment-1546727759, I settled on the simple heuristic of skipping the neighbor list for systems of up to 3000 atoms.  That's for NonbondedForce.  If you have a CustomNonbondedForce I set the limit lower at 2000 atoms.  Many CustomNonbondedForces are inexpensive, but since we don't know for sure how expensive a particular one will be, it seemed safer to be a little bit more conservative.  If you have any other force that involves a neighbor list, like GBSAOBCForce or AmoebaMultipoleForce, it always builds the neighbor list.
=> Skip neighbor list for very small systems

plugins/rpmd/platforms/common/src/CommonRpmdKernels.cpp
=> Sync threads at the end of FFT in `RPMDIntegrator`

wrappers/python/openmm/app/modeller.py
previously pre-existing (i.e. potentially crystallographic waters) were candidates for replacement with an ion, now only newly added waters can be replaced with an ion
concentration calculations (i.e. total water molecules) still include these pre-existing water molecules
possibly fixes #4103
Currently this is always on/changing behaviour, I could put this behaviour behind some `preserveExistingWater=True` kwarg if required
=> addSolvent now only replaces newly added water molecules with ions

olla/include/openmm/kernels.h, openmmapi/src/MonteCarloAnisotropicBarostatImpl.cpp, openmmapi/src/MonteCarloBarostatImpl.cpp, openmmapi/src/MonteCarloFlexibleBarostatImpl.cpp, openmmapi/src/MonteCarloMembraneBarostatImpl.cpp, platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/include/ReferenceMonteCarloBarostat.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceMonteCarloBarostat.cpp, plugins/rpmd/openmmapi/src/RPMDMonteCarloBarostatImpl.cpp
This is an attempt at fixing #4071.  It splits `saveCoordinates()` and `scaleCoordinates()` into two separate methods.
=> Attempt at fixing errors with barostat

wrappers/python/openmm/app/modeller.py
Cf. #4112 for background
Sorry to not add any tests! I was a little wary of mucking around in the tests for such a small change! I can add a simple test in `TestModeller.py` if you like, though. (I wasn't sure if adding a validation that bond info is preserved in `ValidateModeller.py:validate_preserved` would break things)
fixes #4112
=> modeller: Convey bond info when adding Modellers

platforms/common/include/openmm/common/CommonKernels.h, platforms/common/include/openmm/common/ComputeContext.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/ComputeContext.cpp
This aims to fix #4117 
In #4117 the atomic indices can end up incorrectly reordered.
In this PR the atomIndex vector is saved before an attempted MC move and  restored after a rejected one.
=> another attempted fix for MonteCarloBarostat

openmmapi/src/NoseHooverIntegrator.cpp, plugins/drude/tests/TestDrudeNoseHoover.h
Fixes #4109.  When using Nose-Hoover for Drude particles, it would fail to subtract 3 from the degrees of freedom for a CMMotionRemover.  This caused the temperature to be very slightly too high.
NoseHooverIntegrator lets you use different thermostats for different parts of the system.  That creates an ambiguity for which one to subtract 3 from.  Or should it be split among them?  It probably doesn't make much difference.  The effect should be tiny, and I don't know if anyone even uses that feature much.  I chose the simple answer of subtracting them from the largest subset.
cc @Olllom @andysim
=> Fixed DOF calculation for NoseHooverIntegrator

docs-source/usersguide/theory/04_integrators.rst
This issue fixes https://github.com/openmm/openmm/issues/4135. 
It should make it clear that the random variable $R_i$ has unit variance. Further I made the variable notation of $m_i$ consistent and highlighted that we have to divide by the mass.
=> Improve documentation of LangevinIntegrator

platforms/cpu/src/CpuNeighborList.cpp
This modification has been discussed in [issue#4141](https://github.com/openmm/openmm/issues/4141).
=> Fix bug in CpuNeighborList::Voxels::getVoxelIndex()

platforms/common/src/kernels/customNonbondedGroups.cc
Fixes #4127.
The error was caused by a combination of two factors:
1. The system had a CustomNonbondedForce that used very large interaction groups.  In the issue that was reported, the interaction groups contained nearly 3.5 billion interactions.
2. You were running on a GPU with a very large number of SMs.  It happened on RTX 3090 (82 SMs) and H100 (114 SMs), but not on RTX 3080 (68 SMs) or RTX 4080 (76 SMs).
The combination of those two factors led to a number that exceeded the range of a 32 bit integer, leading to some interactions being included more than once.
=> Fixed numeric overflow in computing interaction groups

platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/findInteractingBlocks.cl, platforms/opencl/src/kernels/findInteractingBlocks_cpu.cl
This is an attempt to improve the scaling on large systems.  As discussed in #4063, one part of building the neighbor list involves comparing the bounding boxes of "atom blocks" composed of 32 atoms each.  This scales as O(n^2).  For small to medium systems it takes very little time, but for systems with more than about a million atoms it can become a bottleneck.
This PR introduces "large blocks" composed of 32 atom blocks (1024 atoms).  Each atom block is checked against large blocks to see if we need to check against the individual blocks it contains.  For very large systems, this should reduce the cost of the O(n^2) loop by roughly a factor of 32.  In principle we could add still more levels (blocks of blocks of blocks) to create a full bounding volume hierarchy, which could …
=> Use large blocks to optimize building the neighbor list

wrappers/python/openmm/app/pdbfile.py, wrappers/python/openmm/app/pdbxfile.py, wrappers/python/tests/TestPdbFile.py, wrappers/python/tests/TestPdbxFile.py
This is a minor simplification to the API for writing PDB and PDBx/mmCIF files.  Instead of having to write
```python
with open(filename, 'w') as output:
PDBFile.writeFile(topology, positions, output)
```
it now will also accept
```python
PDBFile.writeFile(topology, positions, filename)
```
=> writeFile() accepts a filename instead of a file object

wrappers/python/openmm/app/xtcfile.py, wrappers/python/tests/TestXtcFile.py
Fixes #4163.
Both the reporter and the tests expected the first step to have index 1, causing the time of the first step to be assigned the time `dt` instead of 0.
Now running this snippet:
```python
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
pdb = PDBFile('villin.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy(maxIterations=100)
simulation.reporters.append(XTCReporter('traj.xtc', 1000, …
```
=> Fix "off by one" error in xtc time reporting.

plugins/amoeba/platforms/common/src/kernels/multipolePme.cc
Fixes #4125.
For some reason the AMOEBA PME code does its indexing differently from the standard PME kernels.  I'm not sure if that's just for historical reasons, or if it's necessary to match Tinker.  In any case, it assumed particles would either be in the primary periodic box (between 0 and width) or one box over from it.  If a particle was too many box widths away from the origin, it would lead to an invalid index and overwrite unrelated memory.
=> Fixed memory error in AMOEBA PME

openmmapi/include/openmm/internal/CustomIntegratorUtilities.h, openmmapi/src/CustomIntegratorUtilities.cpp, tests/TestCustomIntegrator.h
This addresses #2866.  When you create a Context with a CustomIntegrator, it needs to analyze the algorithm to determine which steps should recompute forces and/or energy.  The cost of the analysis scales exponentially in the number of `if` and `while` blocks in the integrator.  For very complicated integrators with a lot of flow control, it becomes prohibitively expensive.
This modifies it to ignore blocks that neither use nor invalidate forces or energy.  Those blocks aren't relevant to the analysis, and ignoring them reduces the number of paths to consider.  That can make it a lot faster.
=> Optimized Context creation with complex CustomIntegrators

platforms/opencl/include/OpenCLFFT3D.h
The latest version of macOS deprecated the `sprintf()` function.  We don't use `sprintf()` anywhere, but vkFFT does.  This leads to huge volumes of deprecation warnings when compiling.  I added a pragma to remove the warnings.
=> Avoid deprecation warnings in vkFFT

docs-source/api-c++/conf.py, docs-source/api-python/conf.py, docs-source/developerguide/conf.py, docs-source/usersguide/conf.py
This PR adds a link to the cookbook and tutorials page from the side panel navigation links of the OpenMM documentation.
=> Add link to cookbook and tutorials in docs

examples/benchmark.py
Test no longer runs and prints out a warning when running benchmark.py with `--verbose`. Fixes #3391
=> Remove amber20-factorix from benchmarks

platforms/common/src/CommonKernels.cpp
Fixes #4173.
When running on Windows, we flush the GPU's work queue after every time step.  This is primarily for Folding@home, to keep the UI responsive.  It can sometimes hurt performance, especially when simulating small systems or running on very fast GPUs.
This changes it to only flush the queue every 25 ms.  That should be enough to keep the UI responsive, while not affecting performance as much.
It would be great if some of the Folding@home developers could test this to verify the UI performance is still acceptable.  This change only affects Windows.  It is ignored on other operating systems,
cc @bdenhollander @hmacdope @jcoffland @dotsdl
=> Flush queue less frequently

platforms/common/src/IntegrationUtilities.cpp
Fixes #4216 
Removes deprecated `std::binary_function` inheritance from `ConstraintOrderer` as it is removed in C++17.
=> Remove std::binary_function from ConstraintOrderer functor

wrappers/python/openmm/app/forcefield.py, wrappers/python/openmm/app/modeller.py
Implements #3445.
`ForceField.createSystem()` lets you specify a `residueTemplates` argument to clarify which templates to use in cases where it's ambiguous.  There are other methods that create systems internally for which this argument would also make sense.  This adds it to `addSolvent()`, `addHydrogens()`, `addExtraParticles()`, `addMembrane()`, and `getUnmatchedResidues()`.
=> Added residueTemplates argument to more methods

wrappers/python/openmm/app/amberprmtopfile.py, wrappers/python/tests/TestAmberPrmtopFile.py, wrappers/python/tests/TestForceField.py
Fixes #4212.
Amber files list an extra "bond" between the hydrogens of a water molecule, which was incorrectly included in the Topology built from a prmtop file.  A Topology should only include actual chemical bonds.
=> Don't add extra bond between water hydrogens

docs-source/api-c++/extras.rst, openmmapi/include/openmm/LocalEnergyMinimizer.h, openmmapi/src/LocalEnergyMinimizer.cpp, tests/TestLocalEnergyMinimizer.h, wrappers/python/openmm/app/simulation.py, wrappers/python/src/swig_doxygen/OpenMM.i, wrappers/python/src/swig_doxygen/swig_lib/python/exceptions.i, wrappers/python/src/swig_doxygen/swig_lib/python/features.i, wrappers/python/tests/TestSimulation.py
Implements #1155.
This adds a virtual MinimizationReporter class.  You subclass it, implementing the `report()` method, and pass it to `minimize()`.  It gets called after each iteration.
The Python API was a little challenging.  This is the first time we've had an interface in which C++ code invokes Python code, instead of the other way around.  I ran into some SWIG issues (https://github.com/swig/swig/issues/2670 and https://github.com/swig/swig/issues/2671), but I think I have workarounds for them.
=> Report status during minimization

wrappers/python/openmm/app/gromacstopfile.py, wrappers/python/setup.py
Distutils has been deprecated in favor of setuptools for quite a while.  Python 3.12 removes it altogether.  This switches the imports, which I think is the only change necessary.
=> Replace distutils with setuptools

platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/customNonbondedGroups.cc
Fixes #4247.  When all of the following conditions were met, derivatives of the energy with respect to global parameters could be calculated incorrectly.
1. The System included multiple Forces that each requested one or more parameter derivatives.
2. One of them was a CustomNonbondedForce.
3. It used interaction groups.
4. You were using the CUDA or OpenCL platform.
=> Fixed error in accumulating parameter derivatives

devtools/ci/gh-actions/conda-envs/build-macos-latest.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-latest.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-pypy.yml, wrappers/python/openmm/app/gromacstopfile.py, wrappers/python/tests/TestGromacsTopFile.py
Fixes #3006.
Gromacs 2019 removed all support for implicit solvent, and apparently it had been broken for years before that.  We continued to support implicit solvent when reading Gromacs .top files, but it only worked if you had an increasingly obsolete version of Gromacs installed.  In OpenMM 7.7 we marked it as deprecated.  This goes the rest of the way and completely removes support for Gromacs files with implicit solvent.
=> Remove support for Gromacs implicit solvent

platforms/opencl/src/OpenCLNonbondedUtilities.cpp
With changes introduced in https://github.com/openmm/openmm/pull/4070 the nonbonded kernel uses USE_NEIGHBOR_LIST (useNeighborList) so host code also must check it instead of useCutoff.
See also https://github.com/openmm/openmm/issues/3462
(I discovered this issue when I encountered test failures in OpenMM-HIP after merging https://github.com/amd/openmm-hip/pull/9)
=> Fix exclusion tiles sorting on AMD GCN/CDNA (64 threads per wave) in OpenCL

wrappers/python/openmm/app/xtcfile.py
The recently added `XTCReporter` is very useful. It's space efficient. And it records time together with positions, making the calculation of time-related properties more convenient.
The time unit used by GROMACS is picosecond. `XTCFile` writes femtosecond into the file by accident.
=> fix the time unit in XTC trajectory file

platforms/common/src/CommonKernels.cpp
`copyParametersToContext()` wasn't setting the CUDA context, causing tests to fail.
=> Fixed test failure in ATMForce

wrappers/python/openmm/app/gromacstopfile.py
Fixes #4284.  The `iteritems()` method was changed to `items()` in Python 3.
=> Removed use of obsolete method iteritems()

.github/workflows/CI.yml
Fix `node12` and `set-output` warnings displayed under [Annotations](https://github.com/openmm/openmm/actions/runs/6607208277).
- Upgrade actions/checkout to v3
- Upgrade actions/cache to v3.3.2
=> Fix CI deprecation warnings

openmmapi/include/openmm/CustomGBForce.h, wrappers/python/src/swig_doxygen/swigInputBuilder.py
Fixes #4266.  If a C++ class name contained a digit, Python docstrings weren't generated correctly for it.  This affected the tabulated function classes.  I also fixed a few html tags that were confusing the converter.
=> Fixed errors in generating Python docstrings

wrappers/python/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
This is not linked to an open issue (as far as I can tell), but it falls in the same category as #4112 (issue), #4113 (PR), completing the work of the latter. 
----
When generating a new topology for a `Modeller` as a result of any operation, bonds that had `type` and `order` attributes in the original topology should retain them, instead of implicitly setting them to `None`.
This PR
- ensures that  `delete()` (therefore implicitly `deleteWater()`), `addSolvent()`, `addHydrogens()` and `addExtraParticles()` behave in the desirable way, while #4112 did it for `add()` (and implicitly for `addMembrane()`).
- adds regression tests either as new tests method, or as assertions in existing test methods
=> Preserve bond type and order in all `Modeller` operations

wrappers/python/openmm/app/dcdfile.py, wrappers/python/openmm/app/dcdreporter.py, wrappers/python/openmm/app/pdbfile.py, wrappers/python/openmm/app/pdbreporter.py, wrappers/python/openmm/app/pdbxfile.py, wrappers/python/openmm/app/xtcfile.py, wrappers/python/openmm/app/xtcreporter.py
It turned out that the reporters for writing trajectories in OpenMM had much higher overhead than was really necessary.  See https://github.com/mdtraj/mdtraj/issues/1840, which found that the new XTCReporter is many times slower than the corresponding one in MDTraj.
The first major source of overhead was that they retrieved the positions from the State by calling `getPositions()`, which involves constructing a Vec3 object for every particle, rather than `getPositions(asNumpy=True)`, which just requires a simple memcpy.  It was especially bad for XTCReporter, which then internally coverts it to a Numpy array anyway.
To test this, I ran the simulatePdb.py example, which simulates a fairly small system, while having it write a frame every 10 steps in a few different formats.  That's much …
=> Optimizations to reporters

plugins/drude/openmmapi/src/DrudeSCFIntegrator.cpp, plugins/drude/platforms/common/src/CommonDrudeKernels.cpp, plugins/drude/platforms/common/src/CommonDrudeKernels.h, plugins/drude/platforms/common/src/kernels/drudeSCF.cc, plugins/drude/platforms/reference/src/ReferenceDrudeKernels.cpp, plugins/drude/platforms/reference/src/ReferenceDrudeKernels.h, plugins/drude/tests/TestDrudeSCFIntegrator.h, wrappers/python/tests/TestAPIUnits.py
Previously DrudeSCFIntegrator just called the generic L-BFGS optimizer to solve for the Drude particle positions.  That worked but was very slow.  I replaced it with a new algorithm that tends to be much faster.  It works roughly like this.
1. Compute the forces on the Drude particles.
2. Jump to the minimum of the harmonic restraining force while assuming all other forces are constant.
3. Iterate until it converges.
I also made one other change.  The default value for the minimization tolerance was 0.1 kJ/mol/nm.  That worked for the test case, which just involves a small cluster of water molecules, but in more typical systems it turned out to be far too low.  The minimizer would thrash, never managing to get the forces down to anything close to that.  I increased it to 10 kJ/mol/nm. …
=> Faster algorithm for DrudeSCFIntegrator

plugins/drude/openmmapi/src/DrudeHelpers.cpp, plugins/drude/tests/TestDrudeSCFIntegrator.h
If a Drude particle had zero mass, `setVelocitiesToTemperature()` would set the velocity of its parent particle to zero.  This was an issue when using DrudeSCFIntegrator.
=> setVelocitiesToTemperature() works with massless Drude particles

platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp
Fixes #4360.  It's closely related to #4049, #4106, and #4119.  It's yet another problem that happened when atom reordering took place in the middle of a barostat move that then got rejected.  In this case the problem was in velocities.  Reordering would cause the array of particle velocities to be reordered.  When we rejected the move, they didn't get put back again.  This caused the velocities of the water molecules to get shuffled.
For flexible water models that didn't actually matter much.  They just reflected a Boltzmann distribution either way.  But for rigid water, it meant the constrained directions no longer matched the directions of zero velocities.  When velocity constraints were next applied, it would cause a sudden drop in the temperature.
This fix should be included in …
=> Fixed error in barostat

docs-source/api-python/process-docstring.py, docs-source/sphinx/autonumber.py, wrappers/python/src/swig_doxygen/swigInputBuilder.py
This pull requests fixes a formatting issue for the LocalCoordinatesSite Python API documentation . Previously, the \<sub\> tag in the Python API documentation was not being processed correctly, leading to display issues.
Before the fix (Incorrect formatting with \<sub\> tag):
After the fix (Corrected formatting):
=> Fixes formatting issue for "sub" tag conversion in Python API documentation

platforms/common/include/openmm/common/ComputeParameterSet.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/ComputeParameterSet.cpp, platforms/common/src/ExpressionUtilities.cpp
Fixes #4373.  When using double precision mode, some calculations still ended up happening in single precision.  This should improve the accuracy.
=> Improved accuracy in double precision mode

libraries/lepton/src/ExpressionTreeNode.cpp
that are causing warnings by Clang. This is just touching one file from the Lepton library.
```
lepton/src/ExpressionTreeNode.cpp:66:105: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
```
=> Fix unqualified std::move instances

wrappers/python/openmm/app/dcdfile.py
Revert #3521; see #4405.
Essentially OpenMM is writing values that are compatible with the symmetric shape matrix, even if it is not calculated the same way. For a version of 21 in the DCD file to be valid, OpenMM would need to store X Y Z and alpha beta gamma (in degrees). Therefore, a version of 24 is more appropriate.
Eventually it may be better to actually calculate the symmetric shape matrix, but this PR should fix compatibility with CHARMM. 
Tagging @peastman and @RickVenable.
=> Write DCD version as 24 instead of 21 to fix ability of CHARMM to read DCD trajectories written by OpenMM

platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/customHbondForce.cc, tests/TestCustomHbondForce.h
It computes a bounding box for each block of 32 donors or acceptors.  That allows it to quickly skip tiles that contain no interactons.
=> Improved performance of CustomHbondForce on large systems

openmmapi/src/CustomGBForceImpl.cpp, openmmapi/src/CustomNonbondedForceImpl.cpp, openmmapi/src/NonbondedForceImpl.cpp, platforms/common/src/ComputeContext.cpp
See #4452.  This slightly reduces context creation time for systems with very large numbers of exclusions.
cc @philipturner.  On your system with two CustomNonbondedForces and 4.8 million exclusions, this reduces context creation time by about 1.5 seconds.
=> Minor optimization to validating exclusions

wrappers/python/openmm/app/internal/amber_file_parser.py
Makes the error message print correctly. The variable `self.lines` does not exist, it was a typo.
=> Fix minor issue in error message with non-existent self.lines

CMakeLists.txt, cmake_modules/TargetArch.cmake, openmmapi/include/openmm/internal/hardware.h
LoongArch is a new architecture, already supported by linux-6.1, gcc-12.
=> Add LoongArch architecture LSX support.

.github/workflows/CI.yml, devtools/ci/gh-actions/scripts/install_cuda.sh
CUDA builds have recently begun failing.  I'm not sure why, though I think it might be that github has started using a newer version of Ubuntu.  I'm attempting to get it working again.
I also updated the versions of CUDA and Python in various builds to better reflect the versions we currently support.
=> Revised code from installing CUDA on CI

docs-source/usersguide/application/02_running_sims.rst
Small thing (the link redirects after both name change and organization transfer) but it stood out to my eyes while doing some questionable things with combinations of force fields ...
=> Update references to "openmmforcefields" project

wrappers/python/openmm/app/internal/debuggingreporter.py
This class mostly isn't intended to be visible to users, which is why it's in `internal`.  But I find it useful frequently enough it seemed sensible to put it into the repository.  It also could be useful to be able to point users at it when they report certain types of hard to reproduce errors.
=> Created DebuggingReporter class

wrappers/python/openmm/app/internal/xtc_utils/src/xtc.cpp
The XTC wrappers store some indexes as int, which can overflow when the trajectories are sufficiently large (a.i. 2e6 atoms in frame 1000).
https://github.com/openmm/openmm/blob/f82876f05d0a3d87927ba32428ee165e056829ab/wrappers/python/openmm/app/internal/xtc_utils/src/xtc.cpp#L137-L139
This PR changes these calculations so that they are stored as size_t instead.
=> Avoid overflow in large XTC files

openmmapi/src/ATMForceImpl.cpp, platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/atmforce.cc, platforms/reference/src/ReferenceKernels.cpp, tests/TestATMForce.h
Fixes #4395.  The main context and the inner contexts are reordered independently now, so each one can pick an appropriate atom order based on its forces.
@egallicc can you try this out?  You should now get good performance without needing the workaround.
=> ATMForce reorders inner contexts for better performance

wrappers/python/openmm/app/simulation.py
Fixes #4503 
Calling Simulation.step() will now raise a TypeError when passed a non-integer value. A type hint was added as well.
A more lenient approach would be to to convert a passed float to an int and provide the user with a warning instead. In my opinion, a fractional step does not really make a lot of sense and therefore restricting the number of steps to be taken to an integer is a better option.
=> added type checking for Simulation.step()

wrappers/python/openmm/app/modeller.py
During the solvation process, a new `Topology` is created when adding the water molecules. Providing a residueTemplates to the `Modeller.addSolvent` method results in an error when adding the ions, as the residueTemplates' keys point to the old topology.
This PR creates an updated newResidueTemplates with the updated keys, that is then provided to the `Modeller._addIons` method.
In my case, this fix solves the issue described in #4524
=> Update residueTemplates dictionary when solvating a system

wrappers/python/openmm/app/forcefield.py
This implements a suggestion that `openmforcefields` appears to need for current versions of GAFF and/or `prmchk2`: https://github.com/openmm/openmmforcefields/issues/281#issuecomment-1599598920
I have no idea how to test this here and I haven't thought of unintended consequences. It certainly seems like the short of change that could have side effects.
=> Allow multiple registrations of the same atom type if definitions identical

wrappers/python/openmm/app/internal/amber_file_parser.py, wrappers/python/tests/TestAmberInpcrdFile.py
In scipy=1.14 the `NetCDFFile` alias is no longer exported. Instead, use `from scipy.io import netcdf_file` which looks to be compatible [as far back as scipy=0.6](https://github.com/scipy/scipy/blob/maintenance/0.6.x/scipy/io/__init__.py#L13). (I tested as far back as scipy=1.0 which is the earliest I could install with conda).
Fixes https://github.com/openmm/openmm/issues/4601
=> Fix import of netcdf_file for compatibility with scipy 1.14

wrappers/python/openmm/app/forcefield.py
`importlib_metadata` was created to backport `importlib.metadata` to older versions of Python.  If you're using a recent Python version that does have it (which includes all versions we support), this allows the entry points to be loaded even if `importlib_metadata` isn't installed.
=> Don't require importlib_metadata

platforms/common/src/CommonKernels.cpp, platforms/cuda/src/CudaContext.cpp, platforms/opencl/src/OpenCLContext.cpp
Fixes #4548.  It makes the changes described in https://github.com/openmm/openmm/issues/4548#issuecomment-2289227736.
If the default periodic box vectors were rectangular, but they later changed to be triclinic, that could lead to incorrect results on the OpenCL and CUDA platforms.  That was most likely to happen when using a MonteCarloFlexibleBarostat.
=> Fixed periodic box changing from rectangular to triclinic

docs-source/usersguide/introduction.rst
This updates the manual to tell people to cite the OpenMM 8 paper.
=> Update reference for citing OpenMM

serialization/src/CustomIntegratorProxy.cpp, serialization/tests/TestSerializeIntegrator.cpp
Fixes #4637.
When serializing a CustomIntegrator, it recorded the global variables as attributes on a single XML tag.  That doesn't preserve order, so when you reloaded it, the global variables would come out in alphabetical order.  It now uses separate tags so the order is preserved.
=> Serializing CustomIntegrator preserves order of global variables

platforms/common/src/CommonKernels.cpp, platforms/cuda/tests/TestCudaCustomCPPForce.cpp, platforms/hip/tests/TestHipCustomCPPForce.cpp, platforms/opencl/tests/TestOpenCLCustomCPPForce.cpp
Fixes https://github.com/openmm/openmm-plumed/issues/88.
Multi-GPU parallelization and CustomCPPForceImpl both use the same worker threads, but for different purposes.  Multi-GPU uses them to let the GPUs do work in parallel.  CustomCPPForceImpl uses them to let the C++ code run in parallel with other work on the GPU.  Trying to do both at once leads to a deadlock.  To fix the problem, I made CustomCPPForceImpl check whether you are using multiple GPUs, and not try to do any further parallelization if it is already running on a worker thread.
=> Prevent deadlock using CustomCPPForceImpl with multiple GPUs

platforms/cpu/src/CpuSETTLE.cpp
Fixes #4644.
This error happened when simulating a very large system on a computer with a very large number of cores.  Specifically if the product of the number of water molecules times the number of cores was greater than about 200 million, it would overflow the range of a 32 bit int, leading to an exception.
=> Fixed numeric overflow

wrappers/python/openmm/app/xtcfile.py, wrappers/python/openmm/app/xtcreporter.py
This pull request addresses issue #4651.
Currently, if an XTC file already exists, the XTCReporter raises an exception the first time it tries to write a frame. With this pull request, it will instead overwrite the existing file, consistent with the behavior of the PDB and DCD reporters.
Additionally, a check on the positions has been added. The XTCFile scales up positions by 1000 and store them as integers. If a position value exceeds 2E6, the xtc file becomes corrupted and unreadable by an xtc parser. This fix introduces a validation step that raises an exception if the positions exceed the limit that xtc format can handle.
=> XTCReporter overwrites existing xtc file

platforms/common/src/kernels/pme.cc, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/hip/include/HipKernels.h, platforms/hip/src/HipKernels.cpp, platforms/hip/src/kernels/common.hip, platforms/opencl/src/OpenCLKernels.cpp, plugins/amoeba/platforms/common/src/AmoebaCommonKernels.cpp
The PME optimizations consists of two commit. "Copy 3 kernels from pme.cc to HIP for future optimizations" copies the kernels without modifications, so the changes of "Optimize PME spread and interpolate kernels" are better visible. The main idea is to process one atom with 5 (PME_ORDER) threads using cross-lane operations, from the commit message:
* PME_ORDER lanes process one atom;
* PME_ORDER lanes access consecutive addresses;
* No need to permute z indices with zindexTable;
* Each component (x, y, z) of thetas is calculated by one lane;
This change improves overall performance of benchmarks with PME by 4-14% (depending on the GPU and the benchmark).
I think, this optimization can be ported to CUDA but I haven't tried this yet.
@peastman, are interested in it? Can we have it as it is …
=> Optimize PME spread charges: process 1 atom by 5 threads

docs-source/developerguide/07_cuda_platform.rst, docs-source/usersguide/application/01_getting_started.rst, docs-source/usersguide/application/02_running_sims.rst, docs-source/usersguide/library/01_introduction.rst, docs-source/usersguide/library/02_compiling.rst, docs-source/usersguide/library/04_platform_specifics.rst, docs-source/usersguide/library/08_amoeba_plugin.rst
This adds more documentation about the HIP platform.
@ex-rzr am I right that it's currently only supported on Linux?  I didn't add anything about it in the section on compiling for Windows.
=> Added documentation on HIP

devtools/ci/gh-actions/conda-envs/build-macos.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-latest-hip.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-latest.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-pypy.yml, devtools/ci/gh-actions/conda-envs/build-windows-latest.yml, devtools/ci/gh-actions/conda-envs/docs.yml
In CI we've been pinning doxygen to an old version.  I don't know if there's actually a good reason for it, and it has started causing one of the builds to fail since the version isn't available.  I'm trying removing it.
=> Remove doxygen pin

wrappers/python/openmm/app/dcdfile.py, wrappers/python/openmm/app/pdbfile.py, wrappers/python/openmm/app/pdbxfile.py, wrappers/python/openmm/app/xtcfile.py
Fixes #4676.  The problem was introduced in #4330.  It made writing faster if you passed the positions as a numpy array, but much slower if you passed them as a list.
=> Improved performance of writeModel()

docs-source/usersguide/application/02_running_sims.rst
Units for energy minimization have changed recently(ish). The units in the API don't match the user guide.
http://docs.openmm.org/latest/api-python/generated/openmm.app.simulation.Simulation.html#openmm.app.simulation.Simulation.minimizeEnergy
=> updated units in energy minimisation user guide

.github/workflows/CI.yml, devtools/ci/gh-actions/conda-envs/build-macos.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-latest-hip.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-latest.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-pypy.yml, devtools/ci/gh-actions/conda-envs/build-windows-latest.yml, devtools/ci/gh-actions/conda-envs/docs.yml
We're currently running tests on Python 3.9 and 3.11.  This updates it to 3.10 and 3.13.
=> Updated Python versions for CI

examples/benchmark.py
- Add `--disable-pme-stream` to benchmark.py to easily compare performance without having to build with different default values for `DisablePmeSteam`
- Replace utcnow to remove DeprecationWarning
- Check for nvidia-smi before attempting to launch it
- Mention HIP where appropriate
=> Benchmark enhancements

docs-source/usersguide/application/01_getting_started.rst
I updated the installation instructions to reflect the currently supported CUDA versions.  I also added an instruction to download and install HIP from AMD if you want to use the HIP platform, since the current packages for it on conda-forge don't work. :(  (See #4675.)
=> Updated installation instructions

wrappers/python/setup.py
This is a change needed for building PyPI wheels.  When building the Python package, we can set an environment variable to add a suffix to the version number, like "rc1".
cc @mikemhenry
=> Allow adding a suffix to the version number

docs-source/usersguide/application/01_getting_started.rst
Assuming testing the release candidate goes smoothly, the release of 8.2 will support installing with pip.  This updates the documentation to describe how to do it.
=> Document installing with pip

platforms/hip/include/HipContext.h, platforms/hip/src/HipContext.cpp, platforms/hip/src/HipKernels.cpp, plugins/amoeba/platforms/hip/src/AmoebaHipKernels.cpp
This made it impossible for any external package to provide a HIP implementation of a feature.  `#include "HipContext.h"` would lead to a compilation error, because vkFFT.h couldn't be found.
=> Prevent HipContext.h from including vkFFT.h

platforms/common/src/ComputeContext.cpp
This should fix the problems reported in #4707.  Instead of considering every particle in a group to be directly bonded to every other, it treats them as bonded in a linear chain.  When a group contains a very large number of particles, this uses much less memory.
=> Reduced memory use while identifying molecule groups

openmmapi/include/openmm/CompoundIntegrator.h, openmmapi/src/CompoundIntegrator.cpp, plugins/drude/serialization/src/DrudeLangevinIntegratorProxy.cpp, plugins/drude/serialization/src/DrudeNoseHooverIntegratorProxy.cpp, plugins/drude/serialization/tests/TestSerializeDrudeLangevinIntegrator.cpp, plugins/drude/serialization/tests/TestSerializeDrudeNoseHooverIntegrator.cpp, serialization/src/BrownianIntegratorProxy.cpp, serialization/src/CustomIntegratorProxy.cpp, serialization/src/LangevinIntegratorProxy.cpp, serialization/src/LangevinMiddleIntegratorProxy.cpp, serialization/src/NoseHooverIntegratorProxy.cpp, serialization/src/VariableLangevinIntegratorProxy.cpp, serialization/src/VariableVerletIntegratorProxy.cpp, serialization/src/VerletIntegratorProxy.cpp, serialization/tests/TestSerializeIntegrator.cpp, serialization/tests/TestSerializeNoseHooverIntegrator.cpp
Fixes #4730.
While fixing this, I realized our handling of force groups for CompoundIntegrator was inconsistent.  The CompoundIntegrator stored a list of force groups, and so did each integrator it contained.  They were set independently and used inconsistently.  Performing integration would use the groups for the currently selected integrator.  Energy minimization would use the groups for the CompoundIntegrator itself.
I therefore changed the behavior so the CompoundIntegrator doesn't have its own independent set of force groups.  `getIntegrationForceGroups()` returns the groups for the currently selected integrator.  `setIntegrationForceGroups()` sets the groups for *all* contained integrators.
=> Serialization records integration force groups

wrappers/python/openmm/app/modeller.py
Fixes #4739.  Modeller wasn't preserving the formal charges of atoms when editing topologies.
=> Modeller preserves formal charge

wrappers/python/openmm/app/modeller.py
This is similar to https://github.com/openmm/openmm/pull/4528 but was missed out. When the membrane and protein are combined a new topology is created. This invalidates the residueTemplates dict so it must be recreated before calling addSolvent.
=> Fix residueTemplates argument in addMembrane

platforms/cuda/src/CudaKernels.cpp, platforms/hip/src/HipKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
The GPU platforms distinguish nonbonded exceptions based on whether they're exclusions (charge and epsilon are both zero so we simply skip computing them) or whether they still need to be computed, just with different parameters.  They don't allow that to change.  When you create a Context, they mark each exception for whether it is an exclusion, and you can't change parameters in any way that would change that.
This PR makes it a little more tolerant.  If an interaction is initially excluded, it has to remain excluded.  But if an interaction is initially non-excluded, it will allow you to later set charge and epsilon to zero.
This change is needed for constant pH.
=> Allow more changes to nonbonded exceptions

wrappers/python/openmm/unit/quantity.py, wrappers/python/tests/TestUnits.py
This changes the default string representation of Quantities to print values with units in a simpler form.  With the current code:
```python
>>> 1.5*nanometers
Quantity(value=1.5, unit=nanometer)
```
With this PR:
```python
>>> 1.5*nanometers
1.5 nm
```
=> Cleaner printing of units

wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
Currently, when an `<NBFixPair>` entry is present in a `<LennardJonesForce>`, `openmm.app.forcefield.LennardJonesGenerator` creates an entry in a dictionary for every _pair_ of matching atom types.  This can lead to significant memory consumption even when simply loading a force field XML file, _e.g._, loading [openmmforcefields' version of CHARMM36](https://github.com/openmm/openmmforcefields/blob/main/openmmforcefields/ffxml/charmm/charmm36_nowaters.xml) creates over 156 million entries in the `nbfixTypes` table and consumes over 31 GiB of memory.
This memory consumption can be cut significantly by storing the parameters for each `<NBFixPair>` entry and keeping track of which atom types can match which entries.  An entry for a particular pair of atom types can be found with a set …
=> Reduce LennardJonesGenerator memory consumption with many NBFixPair-matching pairs

wrappers/python/openmm/app/amberprmtopfile.py
Fixes #4771.  If a prmtop file did not specify periodic boundary conditions, but the user provided them to the constructor, `createSystem()` would incorrectly throw an exception when they tried to specify a periodic nonbonded method.
=> Fixed error in AmberPrmtopFile checking for periodic system

wrappers/python/openmm/app/modeller.py
This adds an argument to `Modeller.addMembrane()` for selecting which platform to use.  It works exactly like the corresponding argument to `addHydrogens()`.
=> Added platform argument to addMembrane()

.github/workflows/CI.yml
The docs build recently started failing, claiming it can't reach https://commonfund.nih.gov/bioinformatics.  The URL is fine, but sometimes the checker has problems with pages that require scripts.  I added it to the exclusion list.
The pypy build has been failing for some months.  Conda-forge no longer supports pypy, and I don't see a lot of people trying to run OpenMM on it.  I'm therefore removing that build.
=> Fix failing CI builds

wrappers/python/openmm/unit/baseunit.py, wrappers/python/openmm/unit/prefix.py
This addresses #4784.  Note that previously, the behavior of `BaseUnit` with respect to comparison of and interaction between different unit objects having the same name was ambiguous.  For instance, I would assume that after
```
import openmm.unit as unit
dim = unit.BaseDimension("test")
a = unit.BaseUnit(dim, "test_a", "test_a")
b = unit.BaseUnit(dim, "test_b", "test_b")
b.define_conversion_factor_to(a, 10)
b2 = unit.BaseUnit(dim, "test_b", "test_b")
```
either `b2` should behave equal to `b` and have conversion factor of `1` to `b` and `10` to `a`, or `b2` should not behave equal to `b` and refuse to be converted to `a` or `b`.  However,
```
for i in (a, b, b2):
for j in (a, b, b2):
try:
print(f"{i.conversion_factor_to(j):4.1f}", end=" ")
except Exception:
print("????", end=" ") …
```
=> Compare and track openmm.unit.BaseUnit objects by name

wrappers/python/openmm/app/internal/xtc_utils/src/xtc.cpp, wrappers/python/tests/TestXtcFile.py
Should fix #4793.  Note that this issue in the reading code is triggered by attempting to append to an XTC because the XTC writer reads before appending to check that the number of atoms is consistent.
=> Fixes precision mismatch when appending to an XTC file with 9 atoms or less

.github/workflows/CI.yml, wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
`ForceField` allows multiple atom type definitions with the same name if their parameters are identical and forbids them if they differ.  `registerAtomType()` allows atom types' elements to be `None` (by not specifying an `element` attribute in the `<Type>`): https://github.com/openmm/openmm/blob/39808f12cb7dc0465748cc3884b50594ef568523/wrappers/python/openmm/app/forcefield.py#L452-L456 but this is not handled correctly in the duplicate checking code, which assumes that the element is not `None` and that the attribute is always present:
https://github.com/openmm/openmm/blob/39808f12cb7dc0465748cc3884b50594ef568523/wrappers/python/openmm/app/forcefield.py#L447-L449 This came up in trying to split a Drude force field, which uses atom types without elements for the Drude particles, into …
=> Properly handle and test multiple registration of atom types without elements

wrappers/python/openmm/app/charmmpsffile.py, wrappers/python/tests/TestCharmmFiles.py
Addresses #4828.  Allows up to 3 wildcards in any positions for dihedrals and impropers.  4 out of 4 wildcards in a parameter file shouldn't happen so that isn't checked (it won't match and an error will be raised unless there were other matching entries).  The maximum number of wildcards is just the `max_wc_count` argument to `_match_with_wildcards` though so it can be changed if we want.
ParmEd seems to go further in its handling of these wildcards for impropers and considers other permutations by sorting the atom types, but that doesn't seem consistent with what CHARMM actually does as far as I can tell.
The test generates some PSF files, and PRM files with wildcards, and makes sure that the dihedrals or impropers match (or don't).
=> Check all wildcard combinations for dihedrals and impropers

openmmapi/src/ATMForceImpl.cpp, platforms/reference/src/ReferenceKernels.cpp, tests/TestATMForce.h
=> ATMForce: ignore invalid energy term when the energy expression does not depend on it 

platforms/cpu/src/CpuKernels.cpp, platforms/reference/src/ReferenceKernels.cpp
#4766 modified the GPU platforms to allow more types of changes to be made to nonbonded exceptions.  This PR makes the same changes to the Reference and CPU platforms.
=> Reference and CPU allow more changes to nonbonded exceptions

wrappers/python/openmm/app/dcdfile.py, wrappers/python/tests/TestDcdFile.py
To fix #4866
- Allows appending to DCDs with a number of comment lines other than 2 (this is allowed by CHARMM's format, and files like this can be created by some other programs like MDAnalysis)
- Very basic validation of the header to ensure we are actually appending to a valid DCD and not some other kind of file
- More informative error message when number of atoms doesn't match
=> Check comment block length from DCD when appending

platforms/common/include/openmm/common/ComputeContext.h, platforms/common/include/openmm/common/ComputeQueue.h, platforms/common/src/ComputeContext.cpp, platforms/cuda/include/CudaContext.h, platforms/cuda/include/CudaFFT3D.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/include/CudaQueue.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaFFT3D.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaQueue.cpp, platforms/hip/include/HipContext.h, platforms/hip/include/HipKernels.h, platforms/hip/include/HipQueue.h, platforms/hip/src/HipContext.cpp, platforms/hip/src/HipKernels.cpp, platforms/hip/src/HipQueue.cpp, platforms/opencl/include/OpenCLArray.h, platforms/opencl/include/OpenCLContext.h, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/include/OpenCLQueue.h, platforms/opencl/src/OpenCLArray.cpp, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLKernels.cpp
This is the second piece of unifying the NonbondedForce code.  I created an abstract ComputeQueue class.  Platform-specific subclasses wrap a cl::CommandQueue, CUstream, or hipStream_t.
=> Unified interface for queues

platforms/cuda/src/CudaArray.cpp, platforms/hip/src/HipArray.cpp
This PR provides a potential fix for a GPU-side memory leak on CUDA/HIP platforms in the Context/Array destructors (issue #4939).
=> Fix GPU memory leak in context arrays

wrappers/python/openmm/app/forcefield.py
In error messages about template matching errors, it lists the residue index as `res.index+1`.  This was done to match the indices in PDB files, which start from 1 rather than 0.  But there's no guarantee that will match what's in the file, so it often ends up being confusing.  This removes the +1 to match the index of the residue in the Topology.
An alternative would be to print `res.name` and `res.chain.id`, which should match the original file.  However, that isn't always unique since it's fairly common to find multiple chains with the same ID, so it would be confusing in a different way.  And of course, there's no guarantee that the Topology even came from a PDB file.
=> Improved residue indexing in error messages

platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/copyCoordinateBuffers.cc, platforms/cuda/src/CudaContext.cpp, platforms/hip/src/HipContext.cpp, platforms/opencl/src/OpenCLContext.cpp
When calling `setPositions()` or `setVelocities()` on one of the GPU platforms, this eliminates an unnecessary device to host data transfer.  In situations where you're calling `setPositions()` repeatedly, for example to compute energies of many conformations, the benefit can be significant.
=> Optimized setPositions() and setVelocities()

platforms/common/src/CommonKernels.cpp, tests/TestATMForce.h
Addresses issue #4839 
On the GPU platforms, atom reordering of the inner ATMForce contexts was issued before the box dimensions were set. 
This delays atom reordering until box dimensions are set.
=> set box vectors of the inner contexts before atom reordering

platforms/common/include/openmm/common/IntegrationUtilities.h, platforms/common/src/IntegrationUtilities.cpp, platforms/common/src/kernels/integrationUtilities.cc
To compute the kinetic energy, the GPU platforms first download the velocities to the host, then compute the total kinetic energy on the CPU.  This PR changes it to compute it on the GPU.  In single precision mode, the GPU can compute it a lot faster than the CPU.  In mixed precision it might or might not be faster depending on your GPU, but it at least shouldn't be a lot slower.  And then we only have to transfer a few bytes rather than the full array of velocities, which saves time.  Testing the CUDA platform on a RTX 4080, I find a significant speedup in all cases.
=> Optimize computing kinetic energy

platforms/common/src/CommonKernels.cpp
Fixes #4950.  If you called `computeCurrentPressure()` before the barostat had yet attempted a move, it would throw an exception.  The fix is to initialize the kernels in `saveCoordinates()` instead of `scaleCoordinates()`.
=> Fixed exception when computing pressure

platforms/hip/src/kernels/nonbonded.hip
`computeNonbonded` hangs in some tests (without neighbor list)  on the HIP platform
Reproducible on ROCm 6.4 and 6.4.1 (maybe on older versions too) on various architectures (both CDNA and RDNA).
Affected tests:
* TestHipATMForce
* TestHipMonteCarloBarostat
* TestHipNonbondedForce
* TestHipVirtualSites
Disassembly shows that the compiler splits branches of `if (skipBase+tgx < NUM_TILES_WITH_EXCLUSIONS)` and does
`SHFL(skipTiles, TILE_SIZE-1) < pos` checks in them separately, even though `__builtin_amdgcn_ds_bpermute` is a convergent function. Apparently in this case not all lanes participate in each call.
Unlike other common or CUDA kernels, the HIP kernel uses shuffles instead of shared memory.
First I fixed this issue by adding `SYNC_WARPS` at the end of the loop to ensure that the …
=> Fix computeNonbonded hang on the HIP platform

docs-source/usersguide/application/06_creating_ffs.rst
This gives `KeyError: ' theta0'` otherwise.
=> Fix typo in CustomAngleForce docs

wrappers/python/openmm/app/forcefield.py
Fixes #4985 
My change to the `CustomManyParticleGenerator`'s `parseElement` simply adds the function parsing line needed; compare to line 3007 in the `CustomNonbondedGenerator`'s corresponding `parseElement` function. You can run the test code in the issue to verify that this works.
Please let me know where I should add new tests to the package if the developers feel this is appropriate.
=> Add function parsing to custom multiparticle force

platforms/cpu/include/CpuPlatform.h, platforms/cpu/src/CpuPlatform.cpp, platforms/reference/include/ReferencePlatform.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/ReferencePlatform.cpp
The CPU platform provides a shared ThreadPool for use by any code that needs it.  The Reference platform does not, since it mostly is single threaded.  But there are a few places that do require a ThreadPool, mainly for code that's shared between multiple platforms, so it ends up needing to create one anyway.  And in trying to implement adQTB, I'm finding that the lack of a standard thread pool makes the code unnecessarily complicated.
So this PR unifies the handling.  `ReferencePlatform::PlatformData` now includes a shared ThreadPool, and the `threads` field of `CpuPlatform::PlatformData` is just a reference to it.
Note that `ReferencePlatform::contextCreated()` uses a property called `"Threads"` to specify the number of threads to use.  That's done only as a mechanism for CpuPlatform to …
=> Unified threading for Reference and CPU platforms

wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
Here's an attempt at generating more informative errors when a residue in a topology doesn't match any template in a force field.  Addresses #1195 and #3181.  The test cases should give some ideas about the sorts of messages generated.  I've additionally tested it manually on many of the relevant examples that have been submitted to the issue tracker over the years.
Essentially, differences between the set of heavy atoms is checked first, then all particles, then internal bonds, then external bonds.  If a template is found where all atoms and bonds match (based on their elements), only then is a generic error message returned indicating that the connectivity is different.  Special messages are shown for common cases like the presence of an element not supported by any template, atoms …
=> Output more detailed messages when template matching fails

wrappers/python/openmm/app/checkpointreporter.py, wrappers/python/openmm/app/internal/safesave.py, wrappers/python/openmm/app/simulation.py, wrappers/python/tests/TestCheckpointReporter.py, wrappers/python/tests/TestSimulation.py
Addresses the first of two items from https://github.com/openmm/openmm/issues/1645#issuecomment-3080876997.  `Simulation.saveCheckpoint()` and `Simulation.saveState()` should now ensure that if OpenMM is interrupted while overwriting an existing file, the existing checkpoint data will not be lost.  Previously, only `CheckpointReporter` did this, and there was a possibility to overwrite another file if one happened to have been manually created with the same name that `CheckpointReporter` would choose for a temporary file.
=> Always safely overwrite checkpoint and state files

platforms/common/include/openmm/common/CommonCalcNonbondedForce.h, platforms/common/src/CommonCalcNonbondedForce.cpp
Implements #4982.
When simulating small systems (up to 15,000 atoms) with PME, it only sorts the particles every fourth step.  The result is a significant though not huge speedup for very small systems (around 1000) atoms.  It shrinks for larger systems, and mostly disappears by about 15,000 atoms, which is why I set the cutoff there.
cc @dmclark17
=> Reducing sorting overhead for small systems with PME

platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/atmforce.cc
This PR reduces the overhead of calling the ATMForce GPU kernels raised in PR #4776 and discussion #5051.
The variable displacement enhancement added three kernels to the two (`hybridForce` and `copyState`) that were already there:
- `setDisplacements`: assign displacement vectors to particles (fixed or variable)
- `resetDisplForce`: set to zero to buffer that holds the component of the gradients due to variable displacements
- `displForce`: calculates the component of the gradients due to variable displacements
I was able to get rid of `setDisplacements` by merging it with the existing `copyState` kernel. The particle displacement is set on the fly in local registers when the particle coordinates of the inner contexts are set. This has the added benefit of not storing displacements in …
=> optimization of ATMForce kernels

docs-source/usersguide/application/03_model_building_editing.rst
The discussion of `addSolvent()` in the user guide had gotten a little out of date.  This updates it to match the current options.  The API documentation was already correct.
Fixes #5059.
=> Updated documentation on adding solvent

platforms/common/src/CommonCalcNonbondedForce.cpp, platforms/common/src/kernels/nonbondedParameters.cc
Fixes #5067.  On the GPU platforms, if a NonbondedForce used PME and included parameter offsets, the neutralizing plasma self energy would be computed incorrectly.
=> Fixed bug in calculating plasma self energy correction with offsets

plugins/amoeba/platforms/common/src/AmoebaCommonKernels.cpp
This pull request fixes a critical uninitialized memory bug in AmoebaCommonKernels.cpp that can cause simulations involving `AmoebaMultipoleForce` and `CustomNonbondedForce` to fail with NaN energies and forces.
The issue is subtle and non-deterministic. It typically only manifests on the first execution of a simulation step within a newly created context (e.g., the first run in a newly launched container or machine). Subsequent runs in the same hardware often succeed because the uninitialized memory may have been overwritten by other operations, masking the bug. This made the issue very difficult to track down.
When a system contains `AmoebaMultipoleForce` and the number of particles is not an exact multiple of the compute tile size (typically 32), the `posq` buffer is padded. We …
=> Bugfix: Zero-initialize padded posq buffer in AmoebaCommonKernels

docs-source/usersguide/application/02_running_sims.rst, wrappers/python/openmm/app/data/amber19-all.xml, wrappers/python/openmm/app/data/amber19/lipid21.xml, wrappers/python/tests/TestModeller.py
Adds Lipid21 from https://github.com/openmm/openmmforcefields/pull/390.  (Presumably we shouldn't merge this PR before that one.)  In addition to adding Amber19 to the Modeller test, I've also manually checked that the updated `amber19-all.xml` can be used to add membranes of all Modeller-supported types, and to set up a stable membrane protein simulation.
=> Add Lipid21

docs-source/usersguide/theory/02_standard_forces.rst, openmmapi/include/openmm/ConstantPotentialForce.h
Emphasizes that it is incorrect to set non-zero charges in a NonbondedForce when using constant potential, and adds a note about running constant potential simulations with polarizable models.
=> Update constant potential entry in user guide

platforms/common/src/CommonIntegrateQTBStepKernel.cpp, platforms/common/src/kernels/qtb.cc, platforms/reference/src/SimTKReference/ReferenceQTBDynamics.cpp
This fixes a subtle bug: it needs to record the velocities half way through the step instead of at the beginning.  This caused the adaptation mechanism to produce incorrect results at high frequencies.
=> Bug fix to QTBIntegrator

examples/CMakeLists.txt
A side effect of reorganizing the examples directory is that some of its subdirectories don't get installed.  That breaks the conda builds, which run the benchmark script as a test.  This fixes it.
=> Install benchmarks and extras
