wrappers/python/simtk/testInstallation.py
=> .message -> str()

wrappers/python/simtk/openmm/__init__.py, wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i
@peastman: does this look the right idea for setting the PATH and plugin dir based on strings in `version.py`? I'm working on another patch for the conda installer that uses the `post-link.(sh|bat)` to modify the `version.py` file inside the package in `conda install` (http://conda.pydata.org/docs/build.html#pre-post-link-unlink-scripts)
=> Some windows changes

libraries/lepton/src/ExpressionTreeNode.cpp, libraries/lepton/src/Parser.cpp
=> Lepton exceptions have more informative messages

devtools/forcefield-scripts/residuesFinal.xml, wrappers/python/simtk/openmm/app/data/amoeba2013.xml, wrappers/python/simtk/openmm/app/data/amoeba2013_gk.xml
The only change is that a single atom type had an incorrect mass.  See #755.  I also discovered that an XML file needed by the processTinkerForceField.py script wasn't checked in, so I added it.
=> Regenerated AMOEBA2013 based on Tinker 7.0.1

openmmapi/include/openmm/System.h, openmmapi/src/System.cpp, tests/TestSystem.cpp
By popular demand!  I did *not* add a removeParticle(), because that would break all sorts of things.  But removing forces and constraints should be pretty safe, since nothing else in the API references them by index.
=> Added removeForce() and removeConstraint() to System

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
=> Fixed an incorrect unit conversion when constraining angles with AMOEBA

wrappers/python/simtk/openmm/app/pdbfile.py
This is the first part of addressing https://github.com/pandegroup/pdbfixer/issues/54#issuecomment-77052328.
=> Added keepIds flag to PDBFile.writeFile()

olla/include/openmm/kernels.h, openmmapi/src/ContextImpl.cpp, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/include/CudaParallelKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/CudaParallelKernels.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/include/OpenCLParallelKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/OpenCLParallelKernels.cpp, platforms/opencl/src/kernels/findInteractingBlocks.cl, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp
This fixes two different bugs in multi-GPU simulations.  These were really subtle, and I've spent close to two weeks tracking them down.  One caused the forces to sometimes be incorrect, but only by a tiny amount.  The other caused larger errors, but also happened less often.  And on the CUDA platform, they only occurred during the first few hundred force evaluations.  After that, they were fine.  For more details, see https://simtk.org/forums/viewtopic.php?f=161&t=5473.
=> Bug fixes to multi-GPU simulations

examples/benchmark.py, platforms/cuda/include/CudaParallelKernels.h, platforms/cuda/src/CudaParallelKernels.cpp
This was caused by my recent bug fixes.
=> Fixed a performance regression in multi-GPU on CUDA

wrappers/python/simtk/openmm/app/internal/amber_file_parser.py
Some topology files have some of the nonbonded pairs in the Lennard-Jones matrix
pointing to a 0 entry in the HBOND_ACOEF and HBOND_BCOEF arrays. This commit
simply skips over those entries, having previously checked that all entries in
the 10-12 sections are 0.  There is actually an example of this already in the
test suite (see ff14ipq.parm7), but this fortuitously did not cause any
difference in those test results.
The reason this bug is not evident in that test case is because the A- and
B-coefficients pulled when the index was -1 (later decremented to -2) was also
coincidentally 0. However, if this was not the case (as it does not *have* to
be), then who knows what could happen.
This also adds more of a check against 10-12 topology files. ParmEd actually
supports using the 10-12 …
=> Fix very subtle bug in Amber prmtop with NBFIX

platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/findInteractingBlocks_cpu.cl, platforms/opencl/src/kernels/nonbonded_cpu.cl, platforms/opencl/tests/TestOpenCLNonbondedForce.cpp
This didn't get updated correctly when I implemented triclinic boxes.
=> Fixed errors using OpenCL with CPU device

platforms/opencl/include/OpenCLFFT3D.h, platforms/opencl/src/OpenCLFFT3D.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/fft.cl, platforms/opencl/src/kernels/pme.cl, platforms/opencl/tests/TestOpenCLFFT.cpp
It isn't (yet) taking advantage of this to save any computation.  But it does reduce the memory bandwidth a bit, which has some benefit.
=> OpenCL FFT supports real-to-complex transforms

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customIntegratorGlobal.cu, platforms/cuda/src/kernels/customIntegratorPerDof.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customIntegratorGlobal.cl, platforms/opencl/src/kernels/customIntegratorPerDof.cl
This addresses #880.  I think I even managed to do it in a way that won't hurt performance.  @kyleabeauchamp could you confirm this fixes all your problems?
=> Fixed bug in CustomIntegrator

docs-source/usersguide/application.rst, openmmapi/include/openmm/LocalEnergyMinimizer.h, platforms/cuda/tests/TestCudaLocalEnergyMinimizer.cpp, platforms/opencl/tests/TestOpenCLLocalEnergyMinimizer.cpp, platforms/reference/tests/TestReferenceLocalEnergyMinimizer.cpp, wrappers/python/simtk/openmm/app/simulation.py
=> Fixed failing test cases.  Increased default minimizer tolerance to 10.

platforms/cpu/src/CpuNonbondedForce.cpp
=> Improved accuracy of correction for exclusions with PME

wrappers/python/simtk/openmm/app/simulation.py, wrappers/python/tests/TestSimulation.py
This is the first piece of #914.  Comments would be great.
=> Added checkpointing functions to Simulation

wrappers/python/simtk/openmm/app/simulation.py, wrappers/python/tests/TestSimulation.py
=> Implemented runForClockTime()

platforms/cpu/include/CpuNonbondedForce.h, platforms/cpu/include/CpuNonbondedForceVec4.h, platforms/cpu/include/CpuNonbondedForceVec8.h, platforms/cpu/src/CpuNonbondedForce.cpp, platforms/cpu/src/CpuNonbondedForceVec4.cpp, platforms/cpu/src/CpuNonbondedForceVec8.cpp
This should hopefully fix #907.  @jchodera could you test it on your system to see how both the accuracy and the performance are?
=> Tabulated erfc() to improve accuracy of energies

wrappers/python/simtk/openmm/app/internal/customgbforces.py
=> GBn now uses Discrete2DFunctions

platforms/cuda/src/kernels/pme.cu
This should fix #946.  @kyleabeauchamp could you try it out?
=> Fixed race condition doing PME in a separate stream

wrappers/python/simtk/openmm/app/topology.py
- Add an informative ``__repr__`` to Topology
- Add ``__len__`` to Chain and Residue to quickly tell how many residues or atoms are in them, respectively
Now, instead of getting something like this:
```
>>> app.PDBFile('4lzt.pdb').topology
<simtk.openmm.app.topology.Topology object at 0x7fdb419a2050>
```
You get something like this:
```
>>> app.PDBFile('4lzt.pdb').topology
<Topology; 2 chains, 274 residues, 1164 atoms, 1043 bonds>
```
=> Minor enhancements to Topology

libraries/lepton/src/ExpressionTreeNode.cpp
This is a correct fix for the issue that #954 tried to fix.
=> Fixed a compiler warning

openmmapi/src/BrownianIntegrator.cpp, openmmapi/src/CustomIntegrator.cpp, openmmapi/src/LangevinIntegrator.cpp, openmmapi/src/VariableLangevinIntegrator.cpp, openmmapi/src/VariableVerletIntegrator.cpp, openmmapi/src/VerletIntegrator.cpp, plugins/drude/openmmapi/src/DrudeLangevinIntegrator.cpp, plugins/drude/openmmapi/src/DrudeSCFIntegrator.cpp, plugins/rpmd/openmmapi/src/RPMDIntegrator.cpp
=> Add check for null context inside integrator.step()

platforms/cpu/src/CpuNonbondedForceVec4.cpp, platforms/cpu/src/CpuNonbondedForceVec8.cpp
=> Fixed compilation errors on Visual Studio 2013

CMakeLists.txt
=> Ensure Lepton headers get installed

wrappers/python/simtk/testInstallation.py
=> Fixed an error under Python 2.6

plugins/cpupme/src/CpuPmeKernels.cpp
Fixes a segfault when running with PME plugin w/ VS2010. Presumably another bug in the compiler.
=> Fix MSVC2010 segfault

platforms/cpu/src/CpuNeighborList.cpp
=> Reverted an incorrect optimization

plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.h
=> NVRTC sadface

plugins/amoeba/serialization/src/AmoebaStretchBendForceProxy.cpp
This fixes an error that was introduced in https://github.com/pandegroup/openmm/commit/94ca75c6d65404cf9239e6c33ecdb22d657af5e9
=> Fixed a change to AmoebaStretchBendForceProxy that broke compatibility with old files

platforms/reference/src/SimTKReference/ReferenceCCMAAlgorithm.cpp
=> Fixed error in constructing CCMA matrix

platforms/cpu/tests/TestCpuCustomNonbondedForce.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/nonbonded.cu, platforms/cuda/tests/TestCudaCustomNonbondedForce.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/nonbonded.cl, platforms/opencl/tests/TestOpenCLCustomNonbondedForce.cpp, platforms/reference/tests/TestReferenceCustomNonbondedForce.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp
This is the implementation of #974.  I won't merge this until after 6.3, but you can try it out now if you want.
=> Different force groups can have different cutoffs

openmmapi/include/openmm/CustomIntegrator.h, openmmapi/include/openmm/internal/CompiledExpressionSet.h, openmmapi/include/openmm/internal/CustomIntegratorUtilities.h, openmmapi/src/CompiledExpressionSet.cpp, openmmapi/src/CustomIntegrator.cpp, openmmapi/src/CustomIntegratorUtilities.cpp, platforms/cpu/include/CpuCustomGBForce.h, platforms/cpu/include/CpuCustomManyParticleForce.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customIntegrator.cu, platforms/cuda/src/kernels/customIntegratorGlobal.cu, platforms/cuda/src/kernels/customIntegratorPerDof.cu, platforms/cuda/src/kernels/integrationUtilities.cu, platforms/cuda/tests/TestCudaCustomIntegrator.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customIntegrator.cl, platforms/opencl/src/kernels/customIntegratorGlobal.cl, platforms/opencl/src/kernels/customIntegratorPerDof.cl, platforms/opencl/tests/TestOpenCLCustomIntegrator.cpp, platforms/reference/include/ReferenceCustomDynamics.h, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp, platforms/reference/tests/TestReferenceCustomIntegrator.cpp
This involved big changes to how CustomIntegrator is implemented in CUDA and OpenCL.  All global computations are now done on the CPU instead of the GPU.  So keep a close watch for any problems, either bugs or changes in performance.
=> CustomIntegrator supports if and while blocks

platforms/cuda/src/CudaFFT3D.cpp
=> Fixed potential compilation error in CUDA FFT

openmmapi/src/CustomIntegratorUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
These are fairly minor optimizations that slightly reduce the cost of per-dof computations.
=> Optimizations to custom integrator

README.md
* labeled Travis badge
* moved all badges to below Introduction
* added binstar badges
=> Badging update

platforms/cuda/tests/TestCudaCustomIntegrator.cpp, platforms/opencl/tests/TestOpenCLCustomIntegrator.cpp
=> Fix issue with test type casting.

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/opencl/src/OpenCLNonbondedUtilities.cpp
=> Fixed segfault in AmoebaMultipoleForce

CMakeLists.txt
=> Install SFMT headers

wrappers/python/simtk/openmm/app/topology.py
This is mainly to help with debugging.
=> Added a more useful string representation of atoms, residues, and chains

platforms/opencl/src/OpenCLKernels.cpp
=> Fixed a memory leak in OpenCL platform on Nvidia GPUs

olla/src/Kernel.cpp, olla/src/KernelImpl.cpp, plugins/cpupme/src/CpuPmeKernels.cpp, plugins/cpupme/src/CpuPmeKernels.h
This is an attempt at fixing #1065.  I am not at all confident that this fix is actually correct!  Any testing you can do of it would be great.
=> Attempt at fixing a race condition in CPU PME

platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/opencl/src/OpenCLIntegrationUtilities.cpp, platforms/reference/src/SimTKReference/ReferenceConstraints.cpp
=> Fixed an unnecessary exception in SETTLE code

plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.h
Take II.  Tests pass on my machine, after fixing a small PBC-related error.  This *should* give the spherical harmonic direct space terms for the reference platform's PME implementation.
=> Spherical harmonics

wrappers/python/src/swig_doxygen/swig_lib/python/extend.i
=> Added some missing %newobject tags in SWIG configuration

docs-source/developerguide/conf.py, docs-source/usersguide/conf.py
=> Turn off HTML index generation in Sphinx.

platforms/opencl/src/kernels/nonbonded_cpu.cl
Fixes https://github.com/pandegroup/openmm/issues/1079#issuecomment-136193271
=> Fix OpenCL Nonbonded Force on certain CPU devices

docs-source/usersguide/theory.rst, olla/include/openmm/kernels.h, openmmapi/include/OpenMM.h, openmmapi/include/openmm/CustomCentroidBondForce.h, openmmapi/include/openmm/internal/CustomCentroidBondForceImpl.h, openmmapi/src/CustomCentroidBondForce.cpp, openmmapi/src/CustomCentroidBondForceImpl.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernelFactory.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaPlatform.cpp, platforms/cuda/src/kernels/customCentroidBond.cu, platforms/cuda/tests/TestCudaCustomCentroidBondForce.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernelFactory.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLPlatform.cpp, platforms/opencl/src/kernels/customCentroidBond.cl, platforms/opencl/tests/TestOpenCLCustomCentroidBondForce.cpp, platforms/reference/include/ReferenceCustomCentroidBondIxn.h, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernelFactory.cpp, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/ReferencePlatform.cpp, platforms/reference/src/SimTKReference/ReferenceCustomCentroidBondIxn.cpp, platforms/reference/tests/TestReferenceCustomCentroidBondForce.cpp
=> Created CustomCentroidBondForce

serialization/src/StateProxy.cpp, serialization/src/SystemProxy.cpp
=> Added openmmVersion attribute to serialized XML files

docs-source/developerguide/developer.rst, docs-source/developerguide/index.rst, docs-source/developerguide/license.rst, docs-source/usersguide/index.rst, docs-source/usersguide/license.rst
=> Improved placement of license information in manuals

platforms/cuda/src/CudaContext.cpp, platforms/opencl/src/OpenCLContext.cpp
=> Throw an exception if an illegal device or platform index is specified

examples/benchmark.py
Previously we used a 1 fs time step for the AMOEBA benchmarks, but really it's only the bonded forces that need to be evaluated that often.  Now that MTSIntegrator is a standard feature, it makes sense to use it to compute the nonbonded forces half as often.  This leads to a nearly 2x speedup.
=> Use MTSIntegrator for AMOEBA benchmarks

docs-source/usersguide/application.rst, openmmapi/src/ContextImpl.cpp
=> Created OPENMM_DEFAULT_PLATFORM environment variable

wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i
@peastman asked me to file this as a separate PR. It's currently part of #1076, but that PR is still WIP pending other additions, and this can be merged separately.
=> More typechecks

openmmapi/include/openmm/CustomExternalForce.h, platforms/cuda/include/CudaExpressionUtilities.h, platforms/cuda/src/CudaBondedUtilities.cpp, platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/tests/TestCudaCustomExternalForce.cpp, platforms/opencl/include/OpenCLExpressionUtilities.h, platforms/opencl/src/OpenCLBondedUtilities.cpp, platforms/opencl/src/OpenCLExpressionUtilities.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/tests/TestOpenCLCustomExternalForce.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/tests/TestReferenceCustomExternalForce.cpp
=> Created periodicdistance() function for CustomExternalForce

openmmapi/include/openmm/internal/CustomCentroidBondForceImpl.h, openmmapi/include/openmm/internal/CustomCompoundBondForceImpl.h, openmmapi/include/openmm/internal/CustomHbondForceImpl.h, openmmapi/include/openmm/internal/CustomManyParticleForceImpl.h, openmmapi/src/CustomCentroidBondForceImpl.cpp, openmmapi/src/CustomCompoundBondForceImpl.cpp, openmmapi/src/CustomHbondForceImpl.cpp, openmmapi/src/CustomManyParticleForceImpl.cpp, platforms/cpu/src/CpuKernels.cpp, platforms/reference/src/ReferenceKernels.cpp, tests/TestCustomAngleForce.h, tests/TestCustomBondForce.h, tests/TestCustomCentroidBondForce.h, tests/TestCustomCompoundBondForce.h, tests/TestCustomExternalForce.h, tests/TestCustomGBForce.h, tests/TestCustomHbondForce.h, tests/TestCustomManyParticleForce.h, tests/TestCustomNonbondedForce.h, tests/TestCustomTorsionForce.h
=> Added error checking for illegal variable names

openmmapi/include/openmm/CustomAngleForce.h, openmmapi/include/openmm/CustomBondForce.h, openmmapi/include/openmm/CustomCentroidBondForce.h, openmmapi/include/openmm/CustomCompoundBondForce.h, openmmapi/include/openmm/CustomExternalForce.h, openmmapi/include/openmm/CustomGBForce.h, openmmapi/include/openmm/CustomHbondForce.h, openmmapi/include/openmm/CustomManyParticleForce.h, openmmapi/include/openmm/CustomNonbondedForce.h, openmmapi/include/openmm/CustomTorsionForce.h, tests/TestCustomAngleForce.h, tests/TestCustomBondForce.h, tests/TestCustomCentroidBondForce.h, tests/TestCustomCompoundBondForce.h, tests/TestCustomExternalForce.h, tests/TestCustomGBForce.h, tests/TestCustomHbondForce.h, tests/TestCustomManyParticleForce.h, tests/TestCustomNonbondedForce.h, tests/TestCustomTorsionForce.h
This is a minor API simplification when creating custom forces
=> Added default values for some arguments

platforms/cuda/CMakeLists.txt, platforms/opencl/CMakeLists.txt
=> Don't try to build tests if BUILD_TESTING is off

plugins/amoeba/platforms/cuda/src/kernels/multipolePme.cu, plugins/amoeba/platforms/cuda/src/kernels/pmeMultipoleElectrostatics.cu, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp
This fixes the bug mentioned in #1153.
=> Fixed a bug in AmoebaMultipoleForce

platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/opencl/src/OpenCLExpressionUtilities.cpp, platforms/reference/src/ReferenceKernels.cpp, tests/TestCustomExternalForce.h
=> Fix gradient of periodicdistance at 0

examples/simulateGromacs.py
The default include directory logic is much more sophisticated https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/gromacstopfile.py#L876
=> No GMX include directory in example

wrappers/python/simtk/openmm/app/topology.py, wrappers/python/tests/TestTopology.py
This addresses #1207 by adding the following to `simtk.openmm.app.Topology`:
* `getNumAtoms()`
* `getNumResidues()`
* `getNumChains()`
I've also added a corresponding test.
=> Added getNumAtoms, getNumResidues, getNumChains to simtk.openmm.app.Topology

openmmapi/src/CustomNonbondedForce.cpp
=> Check for index validity when setting interaction groups

platforms/opencl/src/kernels/customGBEnergyN2_cpu.cl, platforms/opencl/src/kernels/customGBValueN2_cpu.cl, tests/TestGBSAOBCForce.h
=> Fixed some test failures on OpenCL with CPU device

wrappers/python/src/swig_doxygen/swig_lib/python/extend.i, wrappers/python/tests/TestForceGroups.py
=> Fix force group 31

wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
=> Added neutralize option to addSolvent()

openmmapi/include/openmm/Context.h, openmmapi/src/Context.cpp, wrappers/python/src/swig_doxygen/swigInputConfig.py
=> Added Context::getParameters()

docs-source/usersguide/application.rst, openmmapi/include/openmm/CompoundIntegrator.h, openmmapi/include/openmm/Integrator.h, openmmapi/src/CompoundIntegrator.cpp, openmmapi/src/Integrator.cpp, platforms/cpu/tests/TestCpuCompoundIntegrator.cpp, platforms/cuda/include/CudaIntegrationUtilities.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/include/CudaPlatform.h, platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaPlatform.cpp, platforms/cuda/tests/TestCudaCompoundIntegrator.cpp, platforms/opencl/include/OpenCLIntegrationUtilities.h, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/include/OpenCLPlatform.h, platforms/opencl/src/OpenCLIntegrationUtilities.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/OpenCLPlatform.cpp, platforms/opencl/tests/TestOpenCLCompoundIntegrator.cpp, platforms/reference/tests/TestReferenceCompoundIntegrator.cpp, serialization/include/openmm/serialization/CompoundIntegratorProxy.h, serialization/src/CompoundIntegratorProxy.cpp, serialization/src/SerializationProxyRegistration.cpp, serialization/tests/TestSerializeIntegrator.cpp, tests/TestCompoundIntegrator.h, wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/src/swig_doxygen/swigInputConfig.py
=> Implemented CompoundIntegrator

wrappers/python/simtk/openmm/app/forcefield.py
This fixes #1188.  If there are multiple constraints for a pair of atoms, but they all have the same length, it simply removes the duplicates.  If they have different lengths, it throws an exception.
=> ForceField will not create duplicate constraints

wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/tests/TestModeller.py
=> Added missing support for LocalCoordinatesSite

.travis.yml
RE https://github.com/pandegroup/openmm/pull/1228#issuecomment-156209569, this should deploy the development docs to S3 at http://docs.openmm.org/development, which could aid with debugging.
=> Deploy development docs to S3

wrappers/python/simtk/openmm/app/modeller.py
This fixes a test case that was failing occasionally.
=> Increased SHAKE iterations when positioning extra particles

.travis.yml, appveyor.yml, devtools/run-ctest.py, wrappers/python/CMakeLists.txt, wrappers/python/tests/pytest.ini
=> Add OpenCL to Appveyor and fix nosetests

.travis.yml, devtools/run-ctest.py
=> Rewrite run-ctest.py

wrappers/python/simtk/testInstallation.py
- Fixes a py3 bug in testInstallation (see the traceback in https://github.com/pandegroup/openmm/issues/1307#issuecomment-165925356), `Exceptions` don't have a `.message` attribute.
- Simplifies the complicated decorator-based exception re-writing that IMO doesn't really accomplish anything.
=> Fix testInstallation, and simplify the error handling

plugins/amoeba/platforms/cuda/src/kernels/amoebaTorsionTorsionForce.cu
=> AmoebaTorsionTorsionForce avoids singularity in acos()

docs-source/usersguide/library.rst
cc: https://github.com/pandegroup/openmm/pull/1328#issuecomment-170169883
=> Document how to turn on API docs building

wrappers/python/simtk/openmm/app/data/hydrogens.xml, wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
Fixes #1301.  Also adds a HIN variant.
=> Improvements to addHydrogens()

openmmapi/src/ContextImpl.cpp, platforms/cpu/tests/TestCpuCheckpoints.cpp, platforms/cuda/tests/TestCudaCheckpoints.cpp, platforms/opencl/tests/TestOpenCLCheckpoints.cpp, platforms/reference/tests/TestReferenceCheckpoints.cpp
=> Loading a checkpoint marks that positions have been set

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/gromacstopfile.py, wrappers/python/simtk/openmm/app/internal/amber_file_parser.py, wrappers/python/simtk/openmm/app/internal/customgbforces.py, wrappers/python/simtk/openmm/app/topology.py
Previously, parameters were defined in multiple places -- amber_file_parser.py and charmmpsffile.py.
=> Move all of the logic for GB parameter assignment into the new subclasses

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
A test would be good too - let me complete that.
=> Enable wildcard use for Atom Types

wrappers/python/simtk/openmm/app/forcefield.py
Fixes #1361.  @rafwiewiora could you verify this fixes your test, and also see if it affects the agreement with Amber?
=> Improper torsions without wildcards override ones with

wrappers/python/simtk/openmm/app/forcefield.py
=> Fix calling createSystem with unitless hydrogenMass

wrappers/python/CMakeLists.txt
=> Install typemaps.i for use by plugins

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py, wrappers/python/tests/systems/test_amber_ff.xml
Fixes #1367 
This commit also changes a bunch of old-style Python classes to new-style (Py3 only has the latter).
=> Compare 1-4 scaling factors by looking at size of difference

wrappers/python/simtk/openmm/mtsintegrator.py
See http://docs.openmm.org/development/api-python/generated/simtk.openmm.mtsintegrator.MTSIntegrator.html#
for the rendered results that are less than ideal.
=> Hopefully improve the docstring so the generated docs will improve

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, tests/TestCustomIntegrator.h
Fixes #1380.  This error was introduced post-6.3, so it isn't in any released version.
=> Fixed error in computing global variables

platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/opencl/include/OpenCLExpressionUtilities.h, platforms/opencl/src/OpenCLExpressionUtilities.cpp
=> Fixed compilation error in double precision mode

.travis.yml, platforms/cuda/src/kernels/customManyParticle.cu, platforms/opencl/src/kernels/customManyParticle.cl
This isn't meant to be merged.  I'm just using this PR as a way to run debugging code on travis to try to figure out what's causing the errors.
=> Debugging OpenCL errors on travis

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
=> Part of the Ewald energy was being returned even when that force group wasn't requested

wrappers/python/simtk/openmm/app/forcefield.py
This adds just a bit of code to ensure that the set of atoms being added to a proper torsion does not include a duplicate of one of the angle atoms. Let me know if anything seems off or should be fixed.
Thanks!
=> Fix 3 member rings

wrappers/python/simtk/openmm/app/pdbfile.py
Fixes #1406.  Note that it was already writing CONECT records correctly.  It was just using the wrong record name (ATOM instead of HETATM).
=> PDBFile writes HETATM for heterogens

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, tests/TestCustomNonbondedForce.h
=> Fixed bug using tabulated functions with interaction groups

wrappers/python/simtk/openmm/app/charmmpsffile.py
See https://simtk.org/forums/viewtopic.php?f=161&t=6512&p=16820#p16820 for more
information
Is it too late to get this into 7.0?  Sorry, I haven't really been following the timeline as closely as I normally do...
=> Support negative residue numbers in PSF files.

docs-source/usersguide/library.rst, platforms/cuda/include/CudaPlatform.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaPlatform.cpp, platforms/cuda/src/kernels/pme.cu, platforms/cuda/tests/TestCudaFFT3D.cpp, platforms/cuda/tests/TestCudaNonbondedForce.cpp, platforms/cuda/tests/TestCudaRandom.cpp, platforms/cuda/tests/TestCudaSort.cpp
=> Added property to request deterministic forces

wrappers/python/simtk/openmm/app/modeller.py
=> Optimized energy minimization when adding hydrogens

serialization/src/CMAPTorsionForceProxy.cpp, serialization/src/CustomAngleForceProxy.cpp, serialization/src/CustomBondForceProxy.cpp, serialization/src/CustomCentroidBondForceProxy.cpp, serialization/src/CustomCompoundBondForceProxy.cpp, serialization/src/CustomTorsionForceProxy.cpp, serialization/src/HarmonicAngleForceProxy.cpp, serialization/src/HarmonicBondForceProxy.cpp, serialization/src/PeriodicTorsionForceProxy.cpp, serialization/src/RBTorsionForceProxy.cpp, serialization/tests/TestSerializeCMAPTorsion.cpp, serialization/tests/TestSerializeCustomAngleForce.cpp, serialization/tests/TestSerializeCustomBondForce.cpp, serialization/tests/TestSerializeCustomCentroidBondForce.cpp, serialization/tests/TestSerializeCustomCompoundBondForce.cpp, serialization/tests/TestSerializeCustomTorsionForce.cpp, serialization/tests/TestSerializeHarmonicAngleForce.cpp, serialization/tests/TestSerializeHarmonicBondForce.cpp, serialization/tests/TestSerializePeriodicTorsionForce.cpp, serialization/tests/TestSerializeRBTorsionForce.cpp
I forgot to do this part when implementing #1461.
=> Serialization works for periodic boundary conditions on bonded forces

platforms/reference/include/ReferenceTabulatedFunction.h, platforms/reference/src/ReferenceTabulatedFunction.cpp
See https://simtk.org/forums/viewtopic.php?f=161&t=6561 for details.
=> Optimized reference implementation of continuous tabulated functions

platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/opencl/src/OpenCLExpressionUtilities.cpp, tests/TestCustomCompoundBondForce.h
See https://simtk.org/forums/viewtopic.php?f=161&t=6561.
=> Fixed error in Continuous3DFunction on CUDA and OpenCL

openmmapi/src/LocalEnergyMinimizer.cpp
Instead of making the harmonic restraints enforce the constraints to the full tolerance, it only requires them to produce roughly correct lengths (1e-4 tolerance).  It then does a projection to remove any remaining error.
This has two benefits.  First, it means that minimization is faster when using a very strict tolerance.  Second, if the tolerance is stricter than can actually be achieved (less than about 1e-6 in single precision), this prevents the minimization from failing.  See #1237.
=> Improved minimization with strict constraint tolerance

libraries/lepton/src/CompiledExpression.cpp, platforms/reference/include/ReferenceCustomDynamics.h, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp
I switched it over to using CompiledExpression instead of ExpressionProgram, which makes it a lot faster.
=> Optimized CPU implementation of CustomIntegrator

wrappers/python/simtk/openmm/app/gromacstopfile.py
=> Fixed error using CMAP with GRO files on Python 3

wrappers/python/simtk/openmm/app/dcdreporter.py
=> Fix periodic box vector writing in the DCD reporter

wrappers/python/simtk/openmm/app/forcefield.py
=> Improved speed of template matching

plugins/amoeba/platforms/cuda/tests/TestCudaAmoebaAngleForce.cpp
=> Fixed compilation error on Windows

plugins/drude/platforms/cuda/src/CudaDrudeKernels.cpp, plugins/drude/platforms/opencl/src/OpenCLDrudeKernels.cpp
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=6733 for details.
=> DrudeLangevinIntegrator was not disabling hardwall constraint for maxDistance=0

wrappers/python/simtk/openmm/app/modeller.py
If you gave it an empty Topology and asked it to build a water box with a fixed number of waters, it threw an exception.  This fixes it.
=> Fixed an exception in addSolvent()

platforms/cpu/src/CpuNonbondedForce.cpp, platforms/cuda/src/kernels/coulombLennardJones.cu, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/kernels/coulombLennardJones.cl, platforms/reference/src/SimTKReference/ReferenceLJCoulombIxn.cpp, plugins/drude/platforms/cuda/tests/TestCudaDrudeLangevinIntegrator.cpp, plugins/drude/platforms/opencl/tests/TestOpenCLDrudeLangevinIntegrator.cpp, plugins/drude/platforms/reference/tests/TestReferenceDrudeLangevinIntegrator.cpp
=> Fixed energy error for Drude particle at same location as its parent atom

docs-source/api-python/app.rst.jinja2, docs-source/api-python/render.py
Fixed #1523.  Also cleaned up where a few classes get listed in the index.
=> Added units classes to Python API docs

openmmapi/src/CustomNonbondedForce.cpp, openmmapi/src/NonbondedForce.cpp
=> Added check for illegal particle index

wrappers/python/simtk/openmm/app/forcefield.py
=> Further optimization to template matching

wrappers/python/simtk/openmm/app/forcefield.py
AMOEBA now uses the same code as other forces to identify bonds for exceptions.  This means that virtual sites and drude particles will be handled correctly as far as identifying exceptions is concerned.  The current AMOEBA force fields don't actually use either of those, but a future one might.  This also eliminated some duplicated code.
=> Improved how AMOEBA identifies exceptions

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/internal/amber_file_parser.py, wrappers/python/simtk/openmm/app/internal/customgbforces.py
@swails Can you take a look at this incomplete PR?
The speed has improved again, but I'm not getting results that match the previous version. I suspect the problem is in `customgbforces.py` in the `_createUniqueTable` function. I'm guessing I screwed up computing the interpolated values, but I can't seem to spot the mistake.
=> [WIP] Precompute GBNeck terms

platforms/cpu/src/CpuKernels.cpp, platforms/cpu/src/CpuPlatform.cpp, wrappers/python/simtk/openmm/app/internal/customgbforces.py
This fixes two bugs, both of which caused exceptions to be thrown in certain situations.
=> Fixed bugs related to CustomGBForce

libraries/lepton/include/lepton/CompiledExpression.h, libraries/lepton/src/CompiledExpression.cpp, platforms/cpu/include/CpuCustomGBForce.h, platforms/cpu/include/CpuCustomNonbondedForce.h, platforms/cpu/src/CpuCustomGBForce.cpp, platforms/cpu/src/CpuCustomNonbondedForce.cpp, platforms/reference/include/ReferenceCustomDynamics.h, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp, tests/TestParser.cpp
In my tests, this produces ~25% speedup to CustomGBForce and CustomIntegrator, and a smaller but still significant speedup to CustomNonbondedForce.
=> Optimizations to custom forces/integrators on CPU platform

platforms/cpu/include/CpuCustomNonbondedForce.h, platforms/cpu/src/CpuCustomNonbondedForce.cpp, tests/TestCustomNonbondedForce.h
=> Empty interaction group should produce no interactions

wrappers/python/simtk/openmm/app/forcefield.py
=> Optimization to ForceField

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customGBEnergyN2.cu, platforms/cuda/src/kernels/gbsaObc1.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customGBEnergyN2.cl, platforms/opencl/src/kernels/customGBEnergyN2_cpu.cl, platforms/opencl/src/kernels/gbsaObc.cl, platforms/opencl/src/kernels/gbsaObc_cpu.cl
=> Improved GB performance in mixed precision

libraries/jama/include/tnt_sparse_matrix_csr.h, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp
=> Optimizations to DIIS

openmmapi/include/openmm/internal/ContextImpl.h, openmmapi/src/CMAPTorsionForceImpl.cpp, openmmapi/src/ContextImpl.cpp, openmmapi/src/CustomAngleForceImpl.cpp, openmmapi/src/CustomBondForceImpl.cpp, openmmapi/src/CustomCentroidBondForceImpl.cpp, openmmapi/src/CustomCompoundBondForceImpl.cpp, openmmapi/src/CustomExternalForceImpl.cpp, openmmapi/src/CustomGBForceImpl.cpp, openmmapi/src/CustomHbondForceImpl.cpp, openmmapi/src/CustomManyParticleForceImpl.cpp, openmmapi/src/CustomNonbondedForceImpl.cpp, openmmapi/src/CustomTorsionForceImpl.cpp, openmmapi/src/GBSAOBCForceImpl.cpp, openmmapi/src/GayBerneForceImpl.cpp, openmmapi/src/HarmonicAngleForceImpl.cpp, openmmapi/src/HarmonicBondForceImpl.cpp, openmmapi/src/NonbondedForceImpl.cpp, openmmapi/src/PeriodicTorsionForceImpl.cpp, openmmapi/src/RBTorsionForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaAngleForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaBondForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaGeneralizedKirkwoodForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaInPlaneAngleForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaMultipoleForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaOutOfPlaneBendForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaPiTorsionForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaStretchBendForceImpl.cpp, plugins/drude/openmmapi/src/DrudeForceImpl.cpp
See https://github.com/choderalab/openmmtools/issues/118.  @gregoryross or @jchodera can one of you verify this fixes the problem for you?
=> updateParametersInContext() causes stateChanged() to be called

platforms/cpu/src/CpuGBSAOBCForce.cpp
=> Fixed a potential nan

examples/benchmark.py
=> Fixed friction coefficient in explicit solvent benchmarks

openmmapi/include/openmm/MonteCarloAnisotropicBarostat.h, openmmapi/include/openmm/MonteCarloBarostat.h, openmmapi/include/openmm/MonteCarloMembraneBarostat.h, openmmapi/src/MonteCarloAnisotropicBarostatImpl.cpp, openmmapi/src/MonteCarloBarostatImpl.cpp, openmmapi/src/MonteCarloMembraneBarostatImpl.cpp, platforms/reference/tests/TestReferenceMonteCarloMembraneBarostat.cpp, tests/TestMonteCarloAnisotropicBarostat.h, tests/TestMonteCarloBarostat.h
=> Throw an exception if a barostat is used with a non-periodic system

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, tests/TestCustomIntegrator.h
=> Fixed error when CustomIntegrator modifies step size

openmmapi/include/openmm/CompoundIntegrator.h, openmmapi/src/CompoundIntegrator.cpp
Fixes https://github.com/choderalab/openmmtools/issues/118.
=> CompoundIntegrator::stateChanged() calls through to component integrators

openmmapi/src/CustomIntegrator.cpp
=> CustomIntegrator checks for writing to an unknown variable

wrappers/python/src/swig_doxygen/swig_lib/python/extend.i, wrappers/python/src/swig_doxygen/swig_lib/python/header.i, wrappers/python/src/swig_doxygen/swig_lib/python/pythoncode.i
This got missed when I implemented derivatives of the energy with respect to parameters.  And no one seems to have noticed, from which I conclude that no one has actually been using this feature!
=> Python API for parameter derivatives

platforms/reference/src/SimTKReference/ReferenceVariableStochasticDynamics.cpp
=> Fixed bug in reference implementation of VariableLangevinIntegrator

.travis.yml
This should fix the issue observed with our jenkins server in https://github.com/pandegroup/openmm/pull/1629#issuecomment-253620356
=> Fix AMD APP SDK path

platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/include/CudaParallelKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/CudaParallelKernels.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/cuda/src/kernels/nonbonded.cu
This is a major optimization I've been working on for quite a while.  It ended up producing a speedup of roughly 3%.  Sigh.  I've debated about whether I should actually commit it, or whether the extra code complexity isn't worth the very small speedup.  Still it does help performance, even if not by a lot, and it's possible I can squeeze more out of it in the future.
=> Fine grained pair list of nonbonded interactions

wrappers/python/simtk/openmm/mtsintegrator.py, wrappers/python/tests/TestIntegrators.py
This should fix the precision issue with `MTSIntegrator` noted by @kyleabeauchamp in #1616.
=> Fix precision issue in MTSIntegrator

plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.h, plugins/amoeba/platforms/cuda/src/kernels/multipoleInducedField.cu
=> Solve DIIS matrix on GPU

platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/opencl/src/kernels/findInteractingBlocks.cl
This fixes a bug that was introduced in #1564 (about two months ago).
=> Fixed bug computing neighbor list

plugins/amoeba/platforms/cuda/src/kernels/multipoles.cu, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.h, wrappers/python/simtk/openmm/app/forcefield.py
=> Fixed errors with multipoles set to ZOnly mode

plugins/amoeba/platforms/cuda/src/kernels/multipoleElectrostatics.cu
=> Support multipoles with polarization set to 0

plugins/amoeba/platforms/cuda/src/kernels/multipoleInducedField.cu
=> Handle singular matrix in DIIS

plugins/amoeba/openmmapi/src/AmoebaMultipoleForceImpl.cpp
=> Added error checking to axis particle indices

wrappers/python/simtk/openmm/app/dcdfile.py, wrappers/python/tests/TestDcdFile.py
=> Fixed error writing a DCD file for a very long trajectory

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestForceField.py
=> Added ignoreExternalBonds option to createSystem()

wrappers/python/setup.py, wrappers/python/simtk/openmm/app/__init__.py, wrappers/python/simtk/openmm/app/amberprmtopfile.py, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/simtk/openmm/app/internal/singleton.py, wrappers/python/simtk/openmm/app/topology.py, wrappers/python/tests/TestTopology.py
=> Created Bond class that can store bond type and order

olla/src/Platform.cpp
=> Fixed a bug in setting property by deprecated name

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customIntegratorPerDof.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customIntegratorPerDof.cl
=> Fixes to CustomIntegrator

wrappers/python/simtk/openmm/app/checkpointreporter.py
=> CheckpointReporter does not create output file until first report

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/findInteractingBlocks.cl
Hopefully fixes #1666.  Try this out and see if it makes your nans go away.
=> Fixed error building neighbor list with triclinic boxes

platforms/cpu/src/CpuPlatform.cpp, platforms/reference/include/ReferencePlatform.h
See https://simtk.org/tracker/index.php?func=detail&aid=2464&group_id=161&atid=435.
=> Fixed a memory leak

openmmapi/include/openmm/TabulatedFunction.h, wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/src/swig_doxygen/swig_lib/python/extend.i
=> Support copy() and deepcopy() for TabulatedFunctions

docs-source/api-python/process-docstring.py, wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/src/swig_doxygen/swigInputBuilder.py, wrappers/python/src/swig_doxygen/swig_lib/python/extend.i
=> Fixed deprecation warnings in Python API docs

openmmapi/src/ContextImpl.cpp
=> Added more error checking to constraints

platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/opencl/src/kernels/findInteractingBlocks.cl
Fixes #1695.  Perhaps now I've *finally* fixed all the bugs I introduced in my neighbor list optimizations?
=> Fixed bug in building neighbor list

.travis.yml
=> Update travis s3 credentials

libraries/lbfgs/src/lbfgs.cpp, openmmapi/src/LocalEnergyMinimizer.cpp
=> Fixed memory leaks when minimizer fails

platforms/cuda/include/CudaContext.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/utilities.cu, platforms/opencl/include/OpenCLContext.h, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/utilities.cl
This partially addresses #1661.  I'm hoping to speed it up a bit more in the future.
=> Optimizations to updateParametersInContext()

wrappers/python/simtk/openmm/app/modeller.py
=> Fixed error adding triclinic solvent boxes

wrappers/python/simtk/openmm/app/dcdfile.py, wrappers/python/simtk/openmm/app/dcdreporter.py, wrappers/python/tests/TestDcdFile.py
Fixes one part of #1645.  PDBFile and PDBReporter now have an optional `append` argument.
=> Can append to DCD files

devtools/ci/jenkins/install.sh
=> Add script to build on my Jenkins machine

plugins/amoeba/platforms/cuda/src/kernels/multipoles.cu, plugins/amoeba/platforms/cuda/tests/TestCudaAmoebaMultipoleForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp, plugins/amoeba/platforms/reference/tests/TestReferenceAmoebaMultipoleForce.cpp
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=7463&p=0&start=0&view= for details.
=> Fixed bugs in multipoles with ZOnly axis type

.travis.yml
=> Fix errors on travis downloading files

openmmapi/src/CustomGBForce.cpp, openmmapi/src/CustomHbondForce.cpp, openmmapi/src/CustomManyParticleForce.cpp, openmmapi/src/CustomNonbondedForce.cpp, openmmapi/src/GBSAOBCForce.cpp, openmmapi/src/GayBerneForce.cpp, openmmapi/src/NonbondedForce.cpp, plugins/amoeba/openmmapi/src/AmoebaMultipoleForce.cpp, plugins/amoeba/openmmapi/src/AmoebaVdwForce.cpp
=> Added error checking to setNonbondedMethod()

wrappers/python/simtk/openmm/app/pdbfile.py
I've found some PDB files that put a digit at the start of some atom names.  This tries to deal better with those.
=> Improved logic for guessing elements from atom names

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customHbondForce.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customHbondForce.cl, tests/TestCustomHbondForce.h
=> Fixed bug accessing parameters for CustomHbondForce

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customHbondForce.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customHbondForce.cl
Fixes #1771.  See https://github.com/pandegroup/openmm/issues/1771#issuecomment-294376370.
=> Bug fixes to CustomHbondForce

wrappers/python/simtk/openmm/app/amberprmtopfile.py, wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/internal/amber_file_parser.py, wrappers/python/tests/TestAmberPrmtopFile.py, wrappers/python/tests/TestCharmmFiles.py
=> Make the nonpolar part of GBSA available via an argument to createSystem for both Amber and CHARMM files.

openmmapi/src/SplineFitter.cpp
=> Fixed error in create3DNaturalSpline()

devtools/packaging/README.md, devtools/packaging/scripts/osx/prepare.sh
* Updated `README` with latest packaging build intructions
* Update `osx` packaging script to fix missing packages
=> Minor updates to packaging scripts

openmmapi/include/openmm/CustomIntegrator.h, openmmapi/include/openmm/internal/CustomIntegratorUtilities.h, openmmapi/src/CustomIntegrator.cpp, openmmapi/src/CustomIntegratorUtilities.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp, serialization/src/CustomIntegratorProxy.cpp, serialization/tests/TestSerializeIntegrator.cpp, tests/TestCustomIntegrator.h
=> CustomIntegrator can use tabulated functions

wrappers/python/simtk/openmm/app/pdbxfile.py, wrappers/python/simtk/openmm/app/topology.py, wrappers/python/tests/TestPdbxFile.py
=> PDBxFile records bonds

openmmapi/include/openmm/internal/ContextImpl.h, openmmapi/src/ContextImpl.cpp, openmmapi/src/CustomIntegratorUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, tests/TestCustomIntegrator.h
Fixes #1815.  I'll post details there.
=> Bug fix to custom integrator

appveyor.yml
=> [WIP] Fix failures on appveyor

.travis.yml
=> Pin sphinx to 1.5.6 because 1.6.x breaks things

openmmapi/include/openmm/internal/CustomNonbondedForceImpl.h, openmmapi/src/CustomNonbondedForceImpl.cpp
This tries to address #1832, but don't expect anything dramatic.  It's a bit faster than before, but not hugely faster.
=> Optimized computing long range correction for CustomNonbondedForce

.travis.yml
=> Fixed compilation error on travis

docs-source/usersguide/application.rst, docs-source/usersguide/theory.rst, openmmapi/include/openmm/VirtualSite.h, openmmapi/src/VirtualSite.cpp, platforms/cuda/include/CudaIntegrationUtilities.h, platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/cuda/src/kernels/integrationUtilities.cu, platforms/opencl/include/OpenCLIntegrationUtilities.h, platforms/opencl/src/OpenCLIntegrationUtilities.cpp, platforms/opencl/src/kernels/virtualSites.cl, platforms/reference/src/SimTKReference/ReferenceVirtualSites.cpp, serialization/src/SystemProxy.cpp, serialization/tests/TestSerializeSystem.cpp, tests/TestVirtualSites.h, wrappers/generateWrappers.py, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/src/swig_doxygen/swigInputConfig.py
=> LocalCoordinatesSite can depend on arbitary number of particles

openmmapi/src/CustomCVForceImpl.cpp
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=8032&p=21597.
=> Fixed an incorrect exception in CustomCVForce

wrappers/python/simtk/openmm/app/dcdreporter.py
=> Fixed error appending to DCD files

docs-source/api-python/process-docstring.py, wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/forcefield.py
=> Fix sphinx errors

wrappers/python/src/swig_doxygen/swigInputConfig.py, wrappers/python/src/swig_doxygen/swig_lib/python/extend.i, wrappers/python/src/swig_doxygen/swig_lib/python/pythoncode.i
Fixes #1878.  This reverts the part of #1870 related to CustomIntegrator.
=> Revert changes that caused segfault

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customNonbondedGroups.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customNonbondedGroups.cl, tests/TestCustomNonbondedForce.h
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=8088&p=22163&start=0&view=&sid=47f603a167e13ef8ce7f10f3c8b394f4.
=> Fixed error using interaction groups with parameter derivatives

wrappers/python/src/swig_doxygen/swigInputBuilder.py
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=8189&p=22165&start=0&view=&sid=9387bb4c54c047b3e4882edd3e449b4f.
=> getTabulatedFunction() returns correct subclass

docs-source/usersguide/application.rst, wrappers/python/simtk/openmm/app/dcdreporter.py, wrappers/python/simtk/openmm/app/pdbreporter.py, wrappers/python/simtk/openmm/app/simulation.py, wrappers/python/tests/TestSimulation.py
=> Reporters can request wrapped or unwrapped coordinates

platforms/cpu/src/CpuLangevinDynamics.cpp
Closes https://github.com/pandegroup/openmm/issues/1902
=> removed unused line

wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
=> Fixed bug in LennardJonesGenerator

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
=> Fixed a segfault

platforms/cuda/src/CudaContext.cpp
=> Fixed error using CUDA 8.0 toolkit with 9.0 driver

wrappers/python/simtk/openmm/app/forcefield.py
cc: https://github.com/choderalab/openmm-forcefields/pull/48#issuecomment-345551405
This removes an optimization to `ForceField`'s `LennardJonesGenerator` that was causing issues with the CHARMM conversion by creating discrepancies in exceptions defined for `NonbondedForce` and `CustomNonbondedForce` for CGenFF-parameterized small molecules.
=> Remove optimization to ForceField's LennardJonesGenerator that was causing issues with CHARMM conversion

wrappers/python/simtk/openmm/app/forcefield.py
See https://github.com/pandegroup/openmm/issues/1611#issuecomment-345885609
=> Optimized creation of proper torsions

docs-source/usersguide/application.rst, docs-source/usersguide/references.bib, examples/simulatePdb.py, wrappers/python/setup.py, wrappers/python/simtk/openmm/app/data/amber14-all.xml, wrappers/python/simtk/openmm/app/data/amber14/DNA.OL15.xml, wrappers/python/simtk/openmm/app/data/amber14/DNA.bsc1.xml, wrappers/python/simtk/openmm/app/data/amber14/RNA.OL3.xml, wrappers/python/simtk/openmm/app/data/amber14/lipid17.xml, wrappers/python/simtk/openmm/app/data/amber14/protein.ff14SB.xml, wrappers/python/simtk/openmm/app/data/amber14/protein.ff15ipq.xml, wrappers/python/simtk/openmm/app/data/amber14/spce.xml, wrappers/python/simtk/openmm/app/data/amber14/tip3p.xml, wrappers/python/simtk/openmm/app/data/amber14/tip3pfb.xml, wrappers/python/simtk/openmm/app/data/amber14/tip4pew.xml, wrappers/python/simtk/openmm/app/data/amber14/tip4pfb.xml, wrappers/python/simtk/openmm/app/data/charmm36/spce.xml, wrappers/python/simtk/openmm/app/data/charmm36/tip3p-pme-b.xml, wrappers/python/simtk/openmm/app/data/charmm36/tip3p-pme-f.xml, wrappers/python/simtk/openmm/app/data/charmm36/tip4p2005.xml, wrappers/python/simtk/openmm/app/data/charmm36/tip4pew.xml, wrappers/python/simtk/openmm/app/data/charmm36/tip5p.xml, wrappers/python/simtk/openmm/app/data/charmm36/tip5pew.xml, wrappers/python/simtk/openmm/app/data/charmm36/water.xml
At long last!  Look this over and see if everything looks OK: the files I've chosen to include, the way I've named and organized them, and the documentation.
=> Added new Amber and CHARMM force fields

.travis.yml, docs-source/usersguide/references.bib
=> Eliminate stray non-ASCII characters from references.bib since this breaks sphinx

docs-source/usersguide/theory.rst, openmmapi/include/openmm/CustomAngleForce.h, openmmapi/include/openmm/CustomBondForce.h, openmmapi/include/openmm/CustomCVForce.h, openmmapi/include/openmm/CustomCentroidBondForce.h, openmmapi/include/openmm/CustomCompoundBondForce.h, openmmapi/include/openmm/CustomExternalForce.h, openmmapi/include/openmm/CustomGBForce.h, openmmapi/include/openmm/CustomHbondForce.h, openmmapi/include/openmm/CustomManyParticleForce.h, openmmapi/include/openmm/CustomNonbondedForce.h, openmmapi/include/openmm/CustomTorsionForce.h
=> Improved documentation on how to set parameters

wrappers/python/simtk/openmm/app/pdbfile.py
Fixes https://github.com/pandegroup/pdbfixer/issues/159.
=> Avoid truncating PDB file if the IDs are too long

docs-source/usersguide/application.rst
@jchodera I just linked to the main page for the github repository.  You'll probably want to update the README to provide more information to users arriving there, such as a list of force fields and installation instructions.
=> Added link to openmm-forcefields in the manual

platforms/cuda/include/CudaContext.h, platforms/opencl/include/OpenCLContext.h
=> Added missing Windows exports

openmmapi/src/LocalEnergyMinimizer.cpp, tests/TestLocalEnergyMinimizer.h
=> LocalEnergyMinimizer switches to CPU if forces are getting clipped

platforms/cpu/src/CpuGBSAOBCForce.cpp
=> Fixed uninitialized memory

wrappers/python/src/swig_doxygen/swigInputConfig.py
=> Fixed error in SWIG wrapper for CustomIntegrator.addTabulatedFunction()

platforms/cuda/src/CudaArray.cpp
Fixes error described in #2032.
=> Fixed CUDA error when working with multiple contexts

wrappers/python/simtk/openmm/app/modeller.py
Fixes https://github.com/pandegroup/pdbfixer/issues/161.
=> Fixed error in determining protein size when building membrane

wrappers/python/simtk/openmm/app/forcefield.py
=> Fixed reference to self.force when using a switch function for LJ

platforms/cuda/src/kernels/customNonbondedGroups.cu, platforms/opencl/src/kernels/customNonbondedGroups.cl
=> Fixed incorrect synchronization on Volta 

wrappers/python/simtk/openmm/app/forcefield.py
Fixes #2028.  @jchodera could you verify this fixes it for you?
=> Improved behavior of adding force field directories

libraries/lepton/include/lepton/CustomFunction.h, openmmapi/include/openmm/CustomIntegrator.h, openmmapi/include/openmm/internal/CustomIntegratorUtilities.h, openmmapi/include/openmm/internal/VectorExpression.h, openmmapi/src/CustomIntegratorUtilities.cpp, openmmapi/src/VectorExpression.cpp, platforms/cuda/include/CudaExpressionUtilities.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customIntegratorPerDof.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLExpressionUtilities.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/customIntegratorPerDof.cl, platforms/reference/include/ReferenceCustomDynamics.h, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp, tests/TestCustomIntegrator.h, tests/TestVectorExpression.cpp
Fixes #2050 and #2029.  Also addresses parts of #1445.
=> CustomIntegrator can use vector functions

docs-source/usersguide/application.rst, docs-source/usersguide/index.rst
@peastman: I've taken a stab at the documentation improvements suggested in https://github.com/pandegroup/openmm/issues/2041#issuecomment-384011482. I haven't yet had a chance to see if I broke doc compilation, so apologies if this causes errors!
=> Documentation improvements for Amber14 and CHARMM36

wrappers/python/simtk/openmm/app/modeller.py
The main focus of this is to reduce the amount of memory used while building membranes.  I've also tried to make the process slightly more robust.
=> Improvements to building membranes

wrappers/python/simtk/openmm/app/forcefield.py
When building a system with the CHARMM36 force field, this will often save about ten seconds.
It first tries to match every residue to a template without using patches.  If it succeeds, that's fine.  But if even one residue can't be matched, in then needs to build a list of all possible patched templates.  (And it really does need to build all of them, since it needs to throw an exception if there's more than one way to match it.)  So for every template, it needs to apply all possible combinations of patches.  In some cases, that led to thousands of patched versions of a single template.
To do that, it needs to decide which patches are compatible with each other.  Before it did that in a naive way: just try to apply each patch on top of the others, and if it throws an exception (for …
=> Improved speed of applying patches

.travis.yml, docs-source/sphinx/autonumber.py
This fix was contributed by a user of another project where I use the autonumber script: https://github.com/peastman/statmech/pull/2
=> Changes to work correctly with latest version of Sphinx

platforms/cpu/include/CpuKernels.h, platforms/cpu/include/CpuPlatform.h, platforms/cpu/src/CpuKernels.cpp, platforms/cpu/src/CpuPlatform.cpp, platforms/cuda/include/CudaContext.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/coulombLennardJones.cu, platforms/cuda/src/kernels/gbsaObc1.cu, platforms/cuda/src/kernels/gbsaObc2.cu, platforms/cuda/src/kernels/pme.cu, platforms/opencl/include/OpenCLContext.h, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/coulombLennardJones.cl, platforms/opencl/src/kernels/gbsaObc.cl, platforms/opencl/src/kernels/gbsaObc2.cl, platforms/opencl/src/kernels/gbsaObc_cpu.cl, platforms/opencl/src/kernels/pme.cl, tests/TestDispersionPME.h, tests/TestNonbondedForce.h
=> Support multiple NonbondedForces in one System 

wrappers/python/simtk/openmm/app/modeller.py
Membranes are added by tiling a patch of pre-equilibrated membrane.  That patch includes water on either side, but in some cases your protein may extend beyond that water.  In that case, it's supposed to fill in the rest of the box with extra water, but due to a bug it wasn't doing that.
=> Fixed problems in adding water with membranes

platforms/cuda/src/kernels/sort.cu, platforms/opencl/src/kernels/sort.cl
This hopefully fixes #1728.  At least it does in the particular case I found.
=> Fixed race condition in sorting

openmmapi/include/openmm/NonbondedForce.h, openmmapi/include/openmm/internal/NonbondedForceImpl.h, openmmapi/src/NonbondedForce.cpp, openmmapi/src/NonbondedForceImpl.cpp, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/nonbondedParameters.cu, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/nonbondedParameters.cl, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, plugins/rpmd/platforms/cuda/src/kernels/rpmd.cu, plugins/rpmd/platforms/opencl/src/kernels/rpmd.cl, tests/TestNonbondedForce.h
Fixes #1702.  So far I've created the API and implemented it on the reference platform.  Give it a try.
=> NonbondedForce can use context parameters to modify particles

serialization/src/NonbondedForceProxy.cpp, serialization/tests/TestSerializeNonbondedForce.cpp
=> Serialization of parameter offsets

openmmapi/include/openmm/NonbondedForce.h, openmmapi/src/NonbondedForce.cpp, openmmapi/src/NonbondedForceImpl.cpp, serialization/src/NonbondedForceProxy.cpp, serialization/tests/TestSerializeNonbondedForce.cpp, tests/TestNonbondedForce.h
=> Global parameters for NonbondedForce are explicitly defined

olla/include/openmm/kernels.h, openmmapi/include/openmm/CustomCVForce.h, openmmapi/include/openmm/internal/CustomCVForceImpl.h, openmmapi/src/CustomCVForce.cpp, openmmapi/src/CustomCVForceImpl.cpp, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/include/ReferenceCustomCVForce.h, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceCustomCVForce.cpp, tests/TestCustomCVForce.h
This allows it to update tabulated functions, which is needed for implementing metadynamics with it.
=> Added CustomCVForce.updateParametersInContext()

platforms/reference/include/ReferenceCustomAngleIxn.h, platforms/reference/include/ReferenceCustomBondIxn.h, platforms/reference/include/ReferenceCustomExternalIxn.h, platforms/reference/include/ReferenceCustomTorsionIxn.h, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceCustomAngleIxn.cpp, platforms/reference/src/SimTKReference/ReferenceCustomBondIxn.cpp, platforms/reference/src/SimTKReference/ReferenceCustomExternalIxn.cpp, platforms/reference/src/SimTKReference/ReferenceCustomTorsionIxn.cpp
This avoids recreating a somewhat expensive object on every time step.
=> Optimization to custom forces on CPU

wrappers/python/simtk/openmm/app/charmmpsffile.py
=> Fixed stack overflow

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
=> Avoid unnecessary uploads of global parameters

plugins/amoeba/platforms/cuda/src/kernels/pmeMultipoleElectrostatics.cu, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp
=> Fixed overflow when polarizability is 0

.travis.yml
=> Fix Travis error on Mac

platforms/cpu/src/CpuKernels.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/ReferenceKernels.cpp
=> Fixed bugs in particle parameter offsets

platforms/opencl/include/OpenCLSort.h, platforms/opencl/src/OpenCLSort.cpp
This was an optimization I implemented for Volta, but it turns out to be slower on AMD.  So I've switched it to only use the new code on Nvidia, but continue to use the old version on AMD.
=> Improved performance on AMD GPUs

platforms/cpu/src/CpuKernels.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/ReferenceKernels.cpp, tests/TestNonbondedForce.h
=> Fixed error in parameter offsets for nonbonded exceptions

plugins/drude/platforms/cuda/src/CudaDrudeKernels.cpp, plugins/drude/platforms/opencl/src/OpenCLDrudeKernels.cpp
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=9633&p=26368.
=> Fixed error using DrudeForce with multiple GPUs

platforms/cuda/src/CudaIntegrationUtilities.cpp
This might or might not be related to #2191.
=> Fixed a case of uninitialized memory

platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaKernels.cpp
Yet another attempt at maybe fixing(?) #2191 .
=> Use separate events for different stream synchronizations

platforms/cuda/src/CudaKernels.cpp
Yet another attempt at fixing #2191.
=> Fixed potential uninitialized memory error setting up PME stream

olla/include/openmm/kernels.h, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, plugins/cpupme/src/CpuPmeKernelFactory.cpp, plugins/cpupme/src/CpuPmeKernels.cpp, plugins/cpupme/src/CpuPmeKernels.h, plugins/cpupme/tests/TestCpuPme.cpp, wrappers/python/simtk/testInstallation.py
This was mostly implemented before, but never got quite finished.
=> Completed CPU implementation of LJPME

openmmapi/src/CustomHbondForceImpl.cpp, tests/TestCustomHbondForce.h
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=9915&p=27212.
=> Fixed error using 2D tabulated function with CustomHbondForce

wrappers/python/simtk/openmm/app/charmmpsffile.py
=> Fixed an error in parsing PSF files with multiple segments

platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/opencl/src/OpenCLExpressionUtilities.cpp, tests/TestCustomIntegrator.h
=> Fixed bug involving nested cross products

openmmapi/src/LocalEnergyMinimizer.cpp
=> Improved behavior of energy minimizer

platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/nonbondedParameters.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/nonbondedParameters.cl
=> Fixed inconsistency in computing Ewald self energy

platforms/cuda/include/CudaExpressionUtilities.h, platforms/cuda/src/CudaExpressionUtilities.cpp, tests/TestCustomIntegrator.h
=> Fixed bug in vector operations in CustomIntegrator on CUDA

olla/include/openmm/kernels.h, openmmapi/src/CustomHbondForceImpl.cpp, openmmapi/src/LocalEnergyMinimizer.cpp, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, platforms/cuda/include/CudaExpressionUtilities.h, platforms/cuda/src/CudaExpressionUtilities.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/customNonbondedGroups.cu, platforms/cuda/src/kernels/nonbondedParameters.cu, platforms/opencl/src/OpenCLExpressionUtilities.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/nonbondedParameters.cl, platforms/reference/src/SimTKReference/ObcParameters.cpp, plugins/cpupme/src/CpuPmeKernelFactory.cpp, plugins/cpupme/src/CpuPmeKernels.cpp, plugins/cpupme/src/CpuPmeKernels.h, plugins/cpupme/tests/TestCpuPme.cpp, tests/TestCustomHbondForce.h, tests/TestCustomIntegrator.h, wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/simtk/testInstallation.py
=> Merge changes for 7.3.1 into 7.3 branch

platforms/reference/src/SimTKReference/ReferenceCCMAAlgorithm.cpp
When a system involves lots of constraints that get handled by CCMA, this can make context creation much faster.
=> Optimized building constraint matrix

platforms/cpu/src/CpuCustomNonbondedForce.cpp
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10190&p=0&start=0&view=&sid=ce333b0bf1af2935a8617b2e954168bb.
=> Improved performance of interaction groups on CPU

plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h, plugins/amoeba/openmmapi/src/HippoNonbondedForce.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.h, plugins/amoeba/platforms/cuda/src/kernels/hippoComputeField.cu, plugins/amoeba/platforms/cuda/src/kernels/hippoFixedField.cu, plugins/amoeba/platforms/cuda/src/kernels/hippoInteraction.cu, plugins/amoeba/platforms/cuda/src/kernels/hippoInteractionHeader.cu, plugins/amoeba/platforms/cuda/src/kernels/hippoMutualField.cu, plugins/amoeba/platforms/cuda/src/kernels/hippoNonbondedExceptions.cu, plugins/amoeba/platforms/cuda/tests/TestCudaHippoNonbondedForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceHippoNonbondedForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceHippoNonbondedForce.h, plugins/amoeba/platforms/reference/tests/TestReferenceHippoNonbondedForce.cpp, plugins/amoeba/serialization/src/HippoNonbondedForceProxy.cpp, plugins/amoeba/serialization/tests/TestSerializeHippoNonbondedForce.cpp, wrappers/python/simtk/openmm/app/forcefield.py
This adds ForceField support, and also some minor optimizations.
=> Improvements to HippoNonbondedForce

wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i
If you pass a NumPy array to setPositions(), it's usually possible to directly copy the memory.  That is much faster than treating it as a sequence and iterating over elements.
=> Optimized setPositions() from Python

wrappers/python/simtk/openmm/app/pdbxfile.py
See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10385&p=0&start=0&view=&sid=d2be583da2873e907e44bb0eab22b20a.
=> PDBxFile is more robust

libraries/lepton/src/ParsedExpression.cpp, tests/TestParser.cpp
This is to help deal with the issue described at https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10481&p=29083.
=> Algebraic optimizations

platforms/cuda/include/CudaContext.h, platforms/cuda/include/CudaKernels.h, platforms/cuda/src/CudaContext.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/include/OpenCLContext.h, platforms/opencl/include/OpenCLKernels.h, platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/src/OpenCLKernels.cpp
=> CustomCVForce applies ForceInfos from inner context to the outer one

openmmapi/include/openmm/internal/hardware.h
=> Fixed error on PPC

platforms/cpu/src/CpuKernels.cpp
=> Fixed error applying parameter offsets with CPU platform

appveyor.yml
At least until something breaks it again next week.
=> Trying to get appveyor working again

docs-source/usersguide/application.rst, docs-source/usersguide/references.bib, wrappers/python/simtk/openmm/app/__init__.py, wrappers/python/simtk/openmm/app/metadynamics.py, wrappers/python/simtk/openmm/app/simulatedtempering.py, wrappers/python/tests/TestMetadynamics.py, wrappers/python/tests/TestSimulatedTempering.py
=> Added simulated tempering and metadynamics scripts

wrappers/python/simtk/openmm/app/charmmcrdfiles.py
Since we don't do anything with it anyway and it is not required to be an integer.
Fixes #2348
=> Don't parse resid

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/pdbfile.py
Fixes #2348 and https://github.com/pandegroup/pdbfixer/issues/153.
=> Fixed errors with residue insertion codes

CONTRIBUTING.md, SUPPORT.md
This is a first draft.  Comments welcome!
=> Added CONTRIBUTING and SUPPORT files

wrappers/python/simtk/openmm/app/internal/customgbforces.py
=> Fixed Bondi radius for Cl

wrappers/python/simtk/openmm/app/internal/customgbforces.py
=> Improved robustness of custom GB forces

openmmapi/include/openmm/VariableLangevinIntegrator.h, openmmapi/include/openmm/VariableVerletIntegrator.h, openmmapi/src/VariableLangevinIntegrator.cpp, openmmapi/src/VariableVerletIntegrator.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/ReferenceKernels.cpp, serialization/src/VariableLangevinIntegratorProxy.cpp, serialization/src/VariableVerletIntegratorProxy.cpp, serialization/tests/TestSerializeIntegrator.cpp, tests/TestVariableLangevinIntegrator.h, tests/TestVariableVerletIntegrator.h, wrappers/python/src/swig_doxygen/swigInputConfig.py
=> Added max step size option to variable step size integrators

platforms/cuda/src/kernels/findInteractingBlocks.cu
This (hopefully) *really* fixes #2361.
=> Fixed error in #2416

appveyor.yml
Supposedly this will make it start up faster.
=> Updated Appveyor VM

docs-source/licenses/Licenses.txt
=> Added L-BFGS to licenses file

platforms/opencl/src/OpenCLPlatform.cpp
=> Do not register OpenCL platform if no implementations are available

openmmapi/src/CustomNonbondedForce.cpp, openmmapi/src/System.cpp, plugins/amoeba/openmmapi/src/AmoebaTorsionTorsionForceImpl.cpp, serialization/tests/TestSerializeState.cpp
doing this will make the code more efficient as using post increment usually involves keeping a copy of the previous value and extra code
=> make non-primitave types pre increment instead of post increment

wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
Second attempt at #2443 with a cleaner git history.
=> Restraint existing atoms during addHydrogens

wrappers/python/simtk/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
Addresses #2439 and problem raised in #2430. 
I'd rather have someone thoroughly review the changes... It took me quite a few hours to figure this out and I'm not sure I got all the behaviour right (especially the test code). Shoutout to @joaomcteixeira for helping debug this.
Thanks for all the patience!
=> Fixes _addIons behavior for membrane systems.

platforms/cpu/src/CpuNeighborList.cpp
=> Prevent memory from exploding when particles get too spread out

wrappers/python/simtk/openmm/app/gromacstopfile.py, wrappers/python/tests/TestGromacsTopFile.py
=> Improved determination of elements from Gromacs top files

wrappers/python/simtk/openmm/app/simulation.py, wrappers/python/tests/TestSimulation.py
=> runForClockTime() updates currentStep correctly

wrappers/python/simtk/openmm/app/pdbxfile.py, wrappers/python/tests/TestPdbxFile.py, wrappers/python/tests/systems/insertions.pdbx
See https://github.com/pandegroup/pdbfixer/issues/193
=> Fixed handling of insertion codes in PDBx/mmCIF files

examples/benchmark.py
may need checking
starting work pylinting the projcet
=> remove deprecated modules from project

openmmapi/include/openmm/NoseHooverChain.h, openmmapi/include/openmm/NoseHooverIntegrator.h
This led to errors on some compilers
=> Fixed incorrect formatting

docs-source/api-c++/Doxyfile.in, docs-source/developerguide/developer.rst, docs-source/developerguide/license.rst, docs-source/usersguide/theory.rst, openmmapi/include/openmm/CustomIntegrator.h
The biggest changes are giving more mathematical details on the Langevin integrators, and providing more examples of CustomIntegrator in the API docs.  There are also a few other minor fixes.
=> Updates to documentation

platforms/opencl/src/OpenCLContext.cpp, platforms/opencl/tests/TestOpenCLDeviceQuery.cpp
Fixes #2541.
@tristanic could you test this and see if it works for you?
=> Catch exception when an OpenCL platform has no devices

wrappers/python/simtk/openmm/app/gromacstopfile.py, wrappers/python/tests/TestGromacsTopFile.py
=> Implemented switchDistance option for GromacsTopFile

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/tests/TestCharmmFiles.py
=> Replace nonstandard atom and residue names when loading PSF files

platforms/common/src/kernels/customNonbondedGroups.cc, platforms/cuda/src/CudaContext.cpp
This should fix the illegal address error on Jenkins.  It happened on older GPUs.
=> Fixed incorrect indexing in kernel

wrappers/python/simtk/openmm/app/pdbxfile.py
Fixes https://github.com/pandegroup/pdbfixer/issues/194.
=> Add chain break when either auth_asym_id or label_asym_id changes

openmmapi/include/openmm/NonbondedForce.h, openmmapi/src/NonbondedForce.cpp, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/nonbondedExceptions.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/nonbondedExceptions.cl, platforms/reference/include/ReferenceKernels.h, platforms/reference/include/ReferenceLJCoulomb14.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceLJCoulomb14.cpp, serialization/src/NonbondedForceProxy.cpp, serialization/tests/TestSerializeNonbondedForce.cpp, tests/TestNonbondedForce.h
=> NonbondedForce can optionally apply periodic boundary conditions to exceptions

wrappers/python/simtk/openmm/app/pdbxfile.py
Fixes part of https://github.com/pandegroup/pdbfixer/issues/195.
=> PDBxFile marks heterogens with HETATM

wrappers/python/simtk/openmm/app/pdbxfile.py
Fixes https://github.com/pandegroup/pdbfixer/issues/195.
=> Improved identification of chain IDs in PDBx/mmCIF files

platforms/opencl/src/OpenCLContext.cpp
=> Improved error checking when specifying an OpenCL device

olla/src/Platform.cpp
=> Fix error loading CPU PME on Mac

wrappers/python/simtk/openmm/app/charmmparameterset.py
Fixes #2502.  @Olllom could you review this and make sure it looks correct?
=> Accept more variants of labels in CHARMM files

devtools/forcefield-scripts/processAmberForceField.py, devtools/forcefield-scripts/processCharmmForceField.py, wrappers/python/setup.py, wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/internal/amber_file_parser.py, wrappers/python/simtk/openmm/app/internal/charmm/topologyobjects.py, wrappers/python/simtk/openmm/app/internal/pdbstructure.py
I read the [post](https://foldingathome.org/2020/03/10/covid19-update/) from Folding@Home about their effort on simulating SARS-CoV-2, and that they were using OpenMM.
Here is a small effort in trying to support your project :blush: it's mostly just minor tweaks making the Python code more idiomatic.
I used the alerts from https://lgtm.com/projects/g/openmm/openmm/?mode=tree to find opportunities for improvements, and might do a few more PRs based on this if you're happy about this PR :blush: (for full disclosure, I work on this project in my day-to-day work).
=> Minor Python tweaks

wrappers/python/simtk/openmm/app/internal/charmm/topologyobjects.py, wrappers/python/simtk/unit/quantity.py, wrappers/python/simtk/unit/unit.py
Wow, that was slightly embarrassing :flushed:
I also stumbled upon the fact that you it's slightly more correct to implement `__ne__` by using `not self == other` instead of `not self.__eq__(other)`. (explained [here](https://stackoverflow.com/a/30676267/538973))
=> Fix bug in __ne__ implementation from #2616

wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/tests/TestCharmmFiles.py, wrappers/python/tests/TestForceField.py
=> Added drudeMass argument for setting mass of Drude particles

platforms/opencl/src/OpenCLSort.cpp
=> Fixed errors in sorting on some AMD GPUs

wrappers/python/simtk/openmm/app/statedatareporter.py
=> Improved counting of degrees of freedom

openmmapi/include/openmm/CustomIntegrator.h, openmmapi/include/openmm/Integrator.h, openmmapi/src/ContextImpl.cpp, openmmapi/src/CustomIntegrator.cpp, tests/TestCustomIntegrator.h
=> CustomIntegrator variables are saved to checkpoints

.travis.yml
#2645 made me realize we really ought to have CI testing for PPC and ARM.  Travis has alpha level support for this (https://docs.travis-ci.com/user/multi-cpu-architectures/), so I'm trying it out.
=> Added CI builds for PPC and ARM

openmmapi/include/openmm/CompoundIntegrator.h, openmmapi/src/CompoundIntegrator.cpp, tests/TestCompoundIntegrator.h
=> CompoundIntegrator handles checkpoints correctly

openmmapi/include/openmm/NoseHooverIntegrator.h, platforms/common/src/CommonKernels.cpp, platforms/common/src/kernels/noseHooverChain.cc, platforms/reference/include/ReferenceNoseHooverDynamics.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceNoseHooverDynamics.cpp
=> Minor fixes to Nose Hoover code

docs-source/usersguide/application.rst, wrappers/python/simtk/openmm/__init__.py, wrappers/python/simtk/openmm/mtsintegrator.py, wrappers/python/tests/TestIntegrators.py
Fixes #2689.  I'll run some tests using this with AMOEBA to see what kind of time steps it can handle.
=> Created MTSLangevinIntegrator

openmmapi/include/openmm/internal/vectorize8.h, openmmapi/include/openmm/internal/vectorize_neon.h, openmmapi/include/openmm/internal/vectorize_pnacl.h, openmmapi/include/openmm/internal/vectorize_ppc.h, openmmapi/include/openmm/internal/vectorize_sse.h
Little optimizations and bug fixing
=> Improvements for ARM64 vector implementation

wrappers/python/simtk/openmm/app/forcefield.py
This is needed for the new version of the CHARMM drude force field
=> Fixed an error using virtual sites with patches

openmmapi/include/openmm/internal/vectorizeAvx2.h, platforms/cpu/include/CpuNonbondedForceFvec.h
Approximately 20% speedup over AVX on a Skylake machine.
=> CPU: Various optimisations which improve AVX/AVX2

docs-source/usersguide/application.rst, docs-source/usersguide/library.rst, docs-source/usersguide/references.bib, docs-source/usersguide/theory.rst
The text is probably too verbose, but here is an attempt at documenting the Nosé-Hoover integrator, which is on the to-do list for #2578.
=> Nosé Hoover Integrator docs

openmmapi/include/openmm/internal/vectorize_ppc.h
=> Workaround for bug in GCC 8 on PPC

olla/include/openmm/kernels.h, openmmapi/include/openmm/CompoundIntegrator.h, openmmapi/include/openmm/CustomIntegrator.h, openmmapi/include/openmm/Integrator.h, openmmapi/include/openmm/NoseHooverIntegrator.h, openmmapi/include/openmm/State.h, openmmapi/src/CompoundIntegrator.cpp, openmmapi/src/Context.cpp, openmmapi/src/CustomIntegrator.cpp, openmmapi/src/NoseHooverIntegrator.cpp, openmmapi/src/State.cpp, platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, serialization/src/StateProxy.cpp, serialization/tests/TestSerializeState.cpp, tests/TestCompoundIntegrator.h, tests/TestCustomIntegrator.h, tests/TestNoseHooverIntegrator.h, wrappers/python/simtk/openmm/app/simulation.py, wrappers/python/src/swig_doxygen/swig_lib/python/extend.i
=> States can save integrator parameters

.azure-pipelines/azure-pipelines-windows.yml
=> Attempt at fixing Azure builds

platforms/common/src/kernels/customGBEnergyN2.cc, platforms/common/src/kernels/customGBEnergyN2_cpu.cc, platforms/common/src/kernels/customGBValueN2.cc, platforms/common/src/kernels/customGBValueN2_cpu.cc, platforms/common/src/kernels/gbsaObc.cc, platforms/common/src/kernels/gbsaObc_cpu.cc, platforms/cpu/tests/TestCpuNonbondedForce.cpp, platforms/cuda/include/CudaNonbondedUtilities.h, platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/cuda/src/kernels/nonbonded.cu, platforms/cuda/tests/TestCudaNonbondedForce.cpp, platforms/opencl/include/OpenCLNonbondedUtilities.h, platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/findInteractingBlocks.cl, platforms/opencl/src/kernels/findInteractingBlocks_cpu.cl, platforms/opencl/src/kernels/nonbonded.cl, platforms/opencl/src/kernels/nonbonded_cpu.cl, platforms/opencl/tests/TestOpenCLNonbondedForce.cpp, plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp, plugins/amoeba/platforms/cuda/src/kernels/amoebaGk.cu, plugins/amoeba/platforms/cuda/src/kernels/hippoComputeField.cu, plugins/amoeba/platforms/cuda/src/kernels/hippoNonbonded.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoleElectrostatics.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoleFixedField.cu, plugins/amoeba/platforms/cuda/src/kernels/multipoleInducedField.cu, plugins/amoeba/platforms/cuda/src/kernels/pmeMultipoleElectrostatics.cu, tests/TestNonbondedForce.h
=> Fixed range overflow with very large numbers of atoms

docs-source/usersguide/application.rst
=> Add brief reference and examples to openmmforcefields to user guide

platforms/cuda/src/CudaContext.cpp
=> Fixed incorrect error handling on Windows

platforms/opencl/src/kernels/findInteractingBlocks.cl
Fixes #2817.  This caused errors when simulating more than about 2 million atoms on pre-Navi AMD GPUs.
=> Fixed range overflow on older AMD GPUs

platforms/cuda/src/kernels/findInteractingBlocks.cu, platforms/opencl/src/kernels/findInteractingBlocks.cl
=> Fixed illegal read in kernel

wrappers/python/simtk/openmm/app/internal/charmm/topologyobjects.py
=> Fixed error in parsing PSF files

wrappers/python/simtk/openmm/app/metadynamics.py
=> Fixed incorrect step calculation in metadynamics

wrappers/python/simtk/openmm/app/desmonddmsfile.py
=> Fixed warnings about string comparisons

platforms/cuda/src/CudaSort.cpp, platforms/opencl/src/OpenCLSort.cpp
=> Reduced cutoff for short list sorting kernel

.travis.yml, wrappers/generateWrappers.py
=> Fix errors on Python 3.9

examples/benchmark.py
=> Added HMR to make ApoA1 benchmark more stable

openmmapi/src/NoseHooverIntegrator.cpp
=> Fixed check for subsystem thermostats

docs-source/usersguide/application.rst
=> Update installation instructions for the new conda-forge packages

docs-source/usersguide/application.rst
Based on this comment: https://github.com/conda-forge/cudatoolkit-feedstock/issues/15#issuecomment-732530686
=> Add a little note on conda versions

platforms/cpu/include/CpuNonbondedForce.h, platforms/cpu/src/CpuKernels.cpp, platforms/cpu/src/CpuNonbondedForce.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/cuda/src/kernels/pmeExclusions.cu, platforms/opencl/src/OpenCLKernels.cpp, platforms/opencl/src/kernels/pmeExclusions.cl, platforms/reference/include/ReferenceLJCoulombIxn.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceLJCoulombIxn.cpp, tests/TestNonbondedForce.h
=> Fixed error using periodic exceptions with PME

platforms/cuda/src/kernels/findInteractingBlocks.cu, plugins/cudacompiler/src/CudaCompilerKernels.cpp
Changes suggested in #2943 with @peastman's suggestion to use `GROUP_SIZE`
Thanks for your time and let me know if you have any other suggestions!
=> Minor CUDA Changes

platforms/common/src/CommonKernels.cpp
=> Removed redundant checks

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp, platforms/reference/src/SimTKReference/ReferencePME.cpp, plugins/cpupme/src/CpuPmeKernels.cpp
=> Fixed potential out of range index

wrappers/python/src/swig_doxygen/swig_lib/python/features.i, wrappers/python/tests/TestNumpyCompatibility.py
=> Fixed errors passing Numpy int64 values for int arguments

wrappers/python/simtk/openmm/app/simulation.py
The tolerance was incorrectly described as being an energy rather than a force.
=> Fixed documentation and units for minimizeEnergy()

wrappers/python/setup.py, wrappers/python/simtk/openmm/app/internal/compiled.pyx
=> Fixed deprecated option in setup.py

wrappers/python/src/swig_doxygen/swigInputBuilder.py
=> Removed code related to old SWIG versions

wrappers/python/simtk/openmm/app/amberprmtopfile.py, wrappers/python/simtk/openmm/app/charmmpsffile.py, wrappers/python/simtk/openmm/app/forcefield.py, wrappers/python/simtk/openmm/app/gromacstopfile.py, wrappers/python/tests/TestAmberPrmtopFile.py, wrappers/python/tests/TestCharmmFiles.py, wrappers/python/tests/TestForceField.py, wrappers/python/tests/TestGromacsTopFile.py
=> Do not alter mass of hydrogens in rigid water

platforms/opencl/CMakeLists.txt, platforms/opencl/include/OpenCLArray.h, platforms/opencl/include/OpenCLContext.h, platforms/opencl/tests/TestOpenCLNonbondedForce.cpp
This is necessary for building plugins that use OpenCL.
=> Install opencl.hpp

serialization/src/SystemProxy.cpp
=> Minor code cleanup

wrappers/python/simtk/unit/unit.py
This is an attempt at fixing #2966.
=> Reduce numerical error in computing conversion factors between units

platforms/cpu/src/CpuNeighborList.cpp
See https://github.com/openmm/openmm/pull/2964#issuecomment-767946817.
=> Workaround for bug in GCC 9 on PPC

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/findInteractingBlocks.cu
This is a very minor optimization.  See https://github.com/openmm/openmm/pull/2989.
=> Reduced padding on cutoff

plugins/cudacompiler/src/CudaCompilerKernels.cpp
See https://github.com/openmm/openmm/pull/3017#issuecomment-786598920.
=> Fixed minimum CUDA version for querying supported architectures

wrappers/python/openmm/app/internal/amber_file_parser.py
Fixes #3040 
Just adds a trap - I really don't have an interest in re-implementing this from ParmEd, but we should at least prevent people from running the wrong force field.
=> Trap Amber CMAPs

libraries/lepton/include/lepton/ExpressionTreeNode.h, libraries/lepton/include/lepton/ParsedExpression.h, libraries/lepton/src/ExpressionTreeNode.cpp, libraries/lepton/src/Operation.cpp, libraries/lepton/src/ParsedExpression.cpp
When using custom forces with complicated expressions, this makes context creation much faster.
=> Optimizations to Lepton

plugins/drude/tests/TestDrudeLangevinIntegrator.h, plugins/rpmd/platforms/cuda/tests/TestCudaRpmd.cpp, plugins/rpmd/platforms/opencl/tests/TestOpenCLRpmd.cpp, plugins/rpmd/platforms/reference/tests/TestReferenceRpmd.cpp
I reviewed CI errors to see which tests fail most often, and modified them to be a bit more reliable.  This should hopefully decrease the number of errors we see.
=> Made some flaky tests a little less flaky

docs-source/usersguide/application.rst
=> Fixed error in instructions for installing CUDA toolkit

devtools/CONDA_FORGE_RELEASES.md
Addresses https://github.com/openmm/openmm/issues/2993#issuecomment-813472836
=> add docs for conda forge releases

devtools/CONDA_FORGE_RELEASES.md
Addresses https://github.com/conda-forge/openmm-feedstock/pull/54#issuecomment-830211403
=> add docs for conda-forge empty commit retriggers

devtools/ci/gh-actions/conda-envs/docs.yml, docs-source/api-python/conf.py, docs-source/sphinx/numsec.py, docs-source/usersguide/conf.py
With these changes, it works with Sphinx 4.0.2.
=> Changes to work with recent versions of Sphinx

platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
=> Disable PME stream when using CPU PME

wrappers/python/openmm/app/modeller.py
Fixes #3113.  I tried a few more complicated solutions, but none of them really seemed to be better than the simple approach.
=> Add padding when adding a fixed number of water molecules

platforms/common/src/ExpressionUtilities.cpp, tests/TestCustomIntegrator.h
=> Fixed compilation error in kernel with CustomIntegrator

wrappers/python/openmm/app/metadynamics.py
=> Fixed error in metadynamics when using multiple processes

wrappers/python/openmm/app/charmmpsffile.py
=> Fixed an error in condensing LJ types in CharmmPsfFile

wrappers/python/openmm/app/modeller.py
=> Make addMembrane() more robust

wrappers/python/openmm/app/modeller.py
=> Use deepcopy for cloning positions

wrappers/python/openmm/app/statedatareporter.py, wrappers/python/tests/TestStateDataReporter.py
=> Added append option to StateDataReporter

wrappers/python/openmm/app/checkpointreporter.py, wrappers/python/tests/TestCheckpointReporter.py
=> Added option for CheckpointReporter to save States

openmmapi/src/CustomNonbondedForce.cpp, platforms/common/src/CommonKernels.cpp
This fixes the test cases that have been failing on Jenkins.  The error was introduced in #3236.
=> Fixed error in long range correction with force groups

wrappers/generateWrappers.py
=> Improve accuracy of constants in Fortran interface

openmmapi/include/openmm/CustomCentroidBondForce.h, openmmapi/include/openmm/CustomCompoundBondForce.h, openmmapi/include/openmm/CustomGBForce.h, openmmapi/include/openmm/CustomHbondForce.h, openmmapi/include/openmm/CustomManyParticleForce.h, openmmapi/include/openmm/CustomNonbondedForce.h, openmmapi/include/openmm/TabulatedFunction.h, openmmapi/src/TabulatedFunction.cpp, platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/cpu/include/CpuKernels.h, platforms/cpu/src/CpuKernels.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/src/ReferenceKernels.cpp, tests/TestCustomCentroidBondForce.h, tests/TestCustomCompoundBondForce.h, tests/TestCustomGBForce.h, tests/TestCustomHbondForce.h, tests/TestCustomManyParticleForce.h, tests/TestCustomNonbondedForce.h, wrappers/generateWrappers.py
Fixes #2200.  So far I've only implemented it for CustomCompoundBondForce.  @ljmartin and @tristanic can you take a look and see whether this meets your needs?  If the implementation looks ok, I'll copy it over to additional force types.
=> updateParametersInContext() can change tabulated functions

openmmapi/src/NonbondedForceImpl.cpp
=> Removed incorrect checks for offset scale factors

openmmapi/src/HarmonicAngleForceImpl.cpp, openmmapi/src/NonbondedForceImpl.cpp
=> Removed more unnecessarily restrictive parameter checks

wrappers/generateWrappers.py
=> Workaround for a behavior change in Doxygen 1.9.2

.github/workflows/CI.yml
Use miniforge version that was known to be working
=> Cleanup Conda Env on Mac Mini

wrappers/python/openmm/app/forcefield.py
Fix for #3409 suggested by @peastman.
Feel free to edit etc (its possible I may have got some formatting incorrect), and let me know if you want me to add anything? (maybe a test?)
G
=> Fix for non-equal force constants in stretch-bend

wrappers/python/openmm/app/amberprmtopfile.py, wrappers/python/openmm/app/internal/amber_file_parser.py, wrappers/python/tests/TestAmberPrmtopFile.py
=> Support prmtop files created by chamber

wrappers/python/openmm/app/forcefield.py
=> Fixed exception when splitting AMOEBA force field between two files

wrappers/python/openmm/app/forcefield.py
Fixes #3376.  This catches an obscure situation that could lead to forces being omitted.
=> Added error checking for incomplete AMOEBA force fields

docs-source/usersguide/theory/02_standard_forces.rst, openmmapi/include/openmm/NonbondedForce.h
This is to clarify the question raised in #3467.
=> Added documentation to clarify behavior of nonbonded exceptions

.github/workflows/CI.yml, wrappers/python/openmm/__init__.py
I'm hopeful this will fix the problems with Python 3.10 on Windows.
=> Add library path with os.add_dll_directory()

platforms/common/src/CommonKernels.cpp
See https://github.com/openmm/openmm/issues/2898#issuecomment-1055664566.
=> Barostat does not reset cell offsets

wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
=> Ensure bond lengths are set before creating forces that depend on them

platforms/common/src/kernels/customCVForce.cc
=> Fixed an error when using a NonbondedForce inside a CustomCVForce

platforms/cuda/src/CudaNonbondedUtilities.cpp, platforms/cuda/src/kernels/nonbonded.cu
These are some changes discussed in #3389.
=> Minor optimizations to computing single pairs

wrappers/python/openmm/app/forcefield.py
Fixes #3397.
cc @jchodera @jaimergp
=> Use importlib_metadata instead of pkg_resources

plugins/drude/openmmapi/include/openmm/DrudeIntegrator.h, plugins/drude/openmmapi/include/openmm/DrudeLangevinIntegrator.h, plugins/drude/openmmapi/include/openmm/DrudeNoseHooverIntegrator.h, plugins/drude/openmmapi/src/DrudeLangevinIntegrator.cpp, plugins/drude/openmmapi/src/DrudeNoseHooverIntegrator.cpp, plugins/drude/openmmapi/src/DrudeSCFIntegrator.cpp, wrappers/python/tests/TestAPIUnits.py
=> Max Drude distance defaults to 0.02 nm

openmmapi/include/openmm/internal/vectorize_neon.h
This updates the NEON vectorization code, making use of new intrinsics introduced in ARM v8.  It improves the speed of the CPU platform.
=> Improvements to vectorization on ARM

openmmapi/include/openmm/System.h
=> Fixed minor error in documentation

devtools/ci/gh-actions/scripts/install_cuda.sh
=> Update CUDA keys

openmmapi/include/openmm/CustomCVForce.h, openmmapi/include/openmm/Force.h, openmmapi/include/openmm/internal/ForceImpl.h, openmmapi/src/CustomCVForce.cpp, openmmapi/src/Force.cpp
=> Made getCollectiveVariableValues() const

wrappers/python/openmm/app/forcefield.py
=> ForceFields can store extra attributes for residues

tests/TestNoseHooverIntegrator.h
This will hopefully fix a test case that was failing on Windows CI.
=> Made a test case slightly more accurate

wrappers/python/tests/TestSimulatedTempering.py
A test case introduced in #3614 was slightly flaky.
=> Prevent intermittent failures in a test case

wrappers/python/openmm/app/forcefield.py
=> Support multiple XML files with AMOEBA GK

wrappers/python/openmm/app/gromacstopfile.py
=> Avoid adding duplicate exclusions to CustomNonbondedForce

wrappers/python/openmm/app/metadynamics.py
Proposed Solution to Issue #3633
=> ZeroDivisionError Fix to Metadynamics Bias

wrappers/python/openmm/app/gromacstopfile.py, wrappers/python/tests/TestGromacsTopFile.py, wrappers/python/tests/systems/tip4pew.top
See https://github.com/openmm/openmm/issues/3620#issuecomment-1150315829.
=> GromacsTopFile supports three particle average vsites

wrappers/python/openmm/app/data/pdbNames.xml, wrappers/python/openmm/app/pdbxfile.py
=> PDBxFile replaces nonstandard names with standard ones

wrappers/python/openmm/app/modeller.py
Fixes #3692.  @rosemary-cresset can you try this out and see if it fixes the problem for you?
=> Avoid clashes when adding solvent to non-rectangular boxes

platforms/common/include/openmm/common/ComputeContext.h, platforms/common/src/ComputeContext.cpp, platforms/cuda/src/CudaKernels.cpp, platforms/opencl/src/OpenCLKernels.cpp
=> Ensure valid atom order after loading a checkpoint

docs-source/usersguide/application/05_creating_ffs.rst
Fixes #3735.  The old documentation was out of date.
=> Updated documentation on combining multiple force field files

platforms/cpu/include/CpuCustomNonbondedForceFvec.h
This fixes the error described in https://github.com/openmm/openmm/issues/3832#issuecomment-1308214473.  Hopefully it also fixes the other problems described in that issue, but we'll need to test and find out.
=> Fixed error in CustomNonbondedForce on CPU

libraries/lepton/src/ParsedExpression.cpp
Fixes #3833.
@dominicrufa can you test this and verify it works for you?
=> Improvement to expression optimizer

wrappers/python/openmm/app/data/iamoeba.xml
=> Update sigma parameter in iamoeba.xml

plugins/amoeba/openmmapi/src/AmoebaVdwForceImpl.cpp
=> Added checks for invalid sigma in AmoebaVdwForce

examples/benchmark.py
These are the changes from #3386.  That branch somehow got messed up and I'm not sure how to fix it, so it's easiest to create a new PR.
In addition to the changes there, I added more help text with usage examples.
=> Overhaul benchmarking script to add lots of new features

docs-source/developerguide/05_cpu_platform.rst, docs-source/usersguide/library/04_platform_specifics.rst
I was just scrolling through the docs and found this!
=> Nit plaform -> platform

platforms/opencl/src/OpenCLContext.cpp
=> [macOS GPU Support] Fix SIMD width

.gitignore
Refs: https://github.com/openmm/openmm/issues/3916
Specific files for other operating systems can come later.
=> [macOS Support] Add .DS_Store

platforms/opencl/src/OpenCLKernels.cpp
- Appear to be copy and pasted from getPositions and were not removed
=> Remove unused offset variables

docs-source/usersguide/application/02_running_sims.rst
The GLYCAM website keeps changing URLs.
=> Fix a broken URL again

openmmapi/include/openmm/LocalEnergyMinimizer.h, wrappers/python/src/swig_doxygen/swigInputConfig.py
=> Check units for LocalEnergyMinimizer.minimize()

wrappers/python/openmm/app/modeller.py
=> Set box shape correctly when numAdded is specified

wrappers/python/src/swig_doxygen/swigInputBuilder.py
=> Fixed SWIG wrapping of DrudeIntegrator subclasses

docs-source/usersguide/application/02_running_sims.rst, examples/simulateAmber.py, wrappers/python/openmm/app/amberprmtopfile.py, wrappers/python/openmm/app/internal/amber_file_parser.py, wrappers/python/tests/TestAmberPrmtopFile.py
See #4078 for a discussion of the problems this solves.
=> AmberPrmtopFile accepts box vectors as a constructor argument

wrappers/python/openmm/app/modeller.py
=> Fixed edge case in Modeller._CellList

wrappers/python/openmm/app/simulation.py
=> Throw exception when specifying properties without a Platform

wrappers/python/openmm/app/forcefield.py
=> Fix for patches that affect only bonds, not atoms

wrappers/python/openmm/app/gromacstopfile.py, wrappers/python/tests/TestGromacsTopFile.py
=> GromacsTopFile supports [ settles ] directive

README.md
This reverts a change to the README made in #4170 that caused the docs CI build to start failing.
=> Fix CI failure

platforms/common/src/CommonKernels.cpp, platforms/reference/src/ReferenceKernels.cpp, plugins/amoeba/platforms/common/src/AmoebaCommonKernels.cpp, tests/TestATMForce.h
- Fix variable name in string
- Remove odd space between variable and period that is inconsistently styled
- Replace random tabs with spaces in new ATM Force
=> Amoeba and ATM Force minor cleanup

platforms/common/src/CommonKernels.cpp, tests/TestCustomIntegrator.h
=> Fixed bug in CustomIntegrator detecting changes to context parameters

wrappers/python/openmm/app/forcefield.py
Fixes #4276.  This corrects two issues.
1. `_VirtualSiteData` did not implement `__eq__()`.  The result was that if a residue had virtual sites, and if two different combinations of patches could produce matching templates, it would always report an error for having multiple matches, even if the templates were actually identical.
2. When applying multiple patches to a template, the order in which they were applied was nondeterministic.  This could lead to different results from one run to the next.  I changed it to always apply patches in the order they're defined in the file.
=> Fixed issues in applying patches

docs-source/usersguide/application/03_model_building_editing.rst
=> Fixed list of solvent types in manual

openmmapi/include/openmm/VirtualSite.h
=> Clarified documentation on virtual sites

wrappers/python/openmm/app/modeller.py
=> addExtraParticles() handles LocalCoordinatesSites with more than three particles

openmmapi/include/openmm/CustomCompoundBondForce.h, platforms/reference/src/SimTKReference/ReferencePME.cpp
=> Fixed some incorrect comments

wrappers/python/src/swig_doxygen/swigInputConfig.py, wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i, wrappers/python/tests/TestAPIUnits.py
=> Fixes to Python API for ATMForce

platforms/opencl/src/OpenCLNonbondedUtilities.cpp, platforms/opencl/src/kernels/findInteractingBlocks.cl, platforms/opencl/src/kernels/findInteractingBlocks_cpu.cl, platforms/opencl/src/kernels/nonbonded_cpu.cl
We've been collecting test failures on the CPU OpenCL build recently.  I'm trying to fix some of them.
=> Fixed errors in OpenCL on CPU

openmmapi/src/ContextImpl.cpp, platforms/common/include/openmm/common/IntegrationUtilities.h, platforms/common/src/IntegrationUtilities.cpp, platforms/common/src/kernels/integrationUtilities.cc, platforms/cpu/src/CpuKernels.cpp, platforms/cuda/src/CudaIntegrationUtilities.cpp, platforms/opencl/src/OpenCLIntegrationUtilities.cpp, platforms/reference/include/ReferenceDynamics.h, platforms/reference/include/ReferencePlatform.h, platforms/reference/include/ReferenceVirtualSites.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/ReferencePlatform.cpp, platforms/reference/src/SimTKReference/ReferenceBrownianDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceCustomDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceLangevinMiddleDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceNoseHooverDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceStochasticDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceVariableStochasticDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceVariableVerletDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceVerletDynamics.cpp, platforms/reference/src/SimTKReference/ReferenceVirtualSites.cpp, plugins/drude/platforms/reference/src/ReferenceDrudeKernels.cpp, tests/TestVirtualSites.h
Implements #3223.
@ex-rzr @philipturner this requires very minor changes to the HIP and Metal platforms: see `distributeForcesFromVirtualSites()`.
=> Virtual sites can depend on other virtual sites

openmmapi/src/ATMForceImpl.cpp
=> Fixed memory leak

openmmapi/include/openmm/internal/vectorize_portable.h
See #4449.  gcc is a bit more picky than clang with the portable vectorization API.
=> vectorize_portable.h works on gcc

openmmapi/src/Context.cpp
=> reinitialize() remembers whether positions have been set

wrappers/python/openmm/app/forcefield.py
=> Fixed error when using both CustomNonbondedForce and LennardJonesForce

plugins/drude/openmmapi/include/openmm/DrudeForce.h, plugins/drude/openmmapi/src/DrudeForce.cpp, plugins/drude/platforms/common/src/CommonDrudeKernels.cpp, plugins/drude/platforms/common/src/kernels/drudePairForce.cc, plugins/drude/platforms/reference/src/ReferenceDrudeKernels.cpp, plugins/drude/platforms/reference/src/ReferenceDrudeKernels.h, plugins/drude/tests/TestDrudeForce.h
=> DrudeForce supports periodic boundary conditions

wrappers/python/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
=> Fixed errors with residueTemplates arguments to Modeller methods

.github/workflows/CI.yml, devtools/ci/gh-actions/conda-envs/build-macos-latest.yml, devtools/ci/gh-actions/scripts/run_steps_inside_docker_image.sh, docs-source/usersguide/application/02_running_sims.rst
Some of the builds have started failing.  I'm trying to get them working again.
=> Debug CI failures

devtools/ci/gh-actions/conda-envs/build-macos-13.yml, devtools/ci/gh-actions/conda-envs/build-macos-latest.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-latest.yml, devtools/ci/gh-actions/conda-envs/build-ubuntu-pypy.yml, devtools/ci/gh-actions/conda-envs/build-windows-latest.yml, devtools/ci/gh-actions/conda-envs/docs.yml, wrappers/python/setup.py, wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i
=> Support numpy 2

platforms/opencl/src/kernels/findInteractingBlocks.cl
=> Fixed error on GPUs with SIMT width 64

wrappers/python/CMakeLists.txt, wrappers/python/setup.py
These are a few minor changes that will be helpful for building PyPI packages in the future.
=> Changes for PyPI packaging

.github/workflows/CI.yml
=> Use miniforge instead of mambaforge

plugins/amoeba/openmmapi/include/openmm/internal/AmoebaGeneralizedKirkwoodForceImpl.h, plugins/amoeba/openmmapi/src/AmoebaGeneralizedKirkwoodForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaTorsionTorsionForceImpl.cpp, plugins/amoeba/openmmapi/src/AmoebaWcaDispersionForce.cpp, plugins/amoeba/openmmapi/src/AmoebaWcaDispersionForceImpl.cpp, plugins/amoeba/platforms/common/src/AmoebaCommonKernels.cpp, plugins/amoeba/platforms/common/src/kernels/amoebaGk.cc, plugins/amoeba/platforms/common/src/kernels/amoebaWcaForce.cc, plugins/amoeba/platforms/common/src/kernels/gkPairForce2.cc, plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceGeneralizedKirkwoodForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceTorsionTorsionForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceVdwForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceWcaDispersionForce.cpp, plugins/amoeba/serialization/src/AmoebaVdwForceProxy.cpp, plugins/amoeba/serialization/tests/TestSerializeAmoebaGeneralizedKirkwoodForce.cpp, plugins/amoeba/tests/TestAmoebaGeneralizedKirkwoodForce.h, plugins/amoeba/tests/TestAmoebaMultipoleForce.h, plugins/amoeba/tests/TestAmoebaTorsionTorsionForce.h, plugins/amoeba/tests/TestAmoebaVdwForce.h
Mostly this is just minor formatting changes.  It also fixes a compilation error on Windows introduced by #4647.
=> Cleanup of AMOEBA code

libraries/sfmt/include/sfmt/SFMT.h, platforms/cpu/include/CpuKernels.h, platforms/cpu/include/CpuRandom.h, platforms/cpu/src/CpuKernelFactory.cpp, platforms/cpu/src/CpuKernels.cpp, platforms/cpu/src/CpuPlatform.cpp, platforms/cpu/src/CpuRandom.cpp, platforms/reference/include/ReferenceKernels.h, tests/TestCheckpoints.h
=> CPU platform checkpoints random number generator

olla/include/openmm/kernels.h, openmmapi/src/NoseHooverIntegrator.cpp, platforms/common/include/openmm/common/CommonKernels.h, platforms/common/src/CommonKernels.cpp, platforms/reference/include/ReferenceKernels.h, platforms/reference/include/ReferenceNoseHooverDynamics.h, platforms/reference/src/ReferenceKernels.cpp, platforms/reference/src/SimTKReference/ReferenceNoseHooverDynamics.cpp
=> Prevent extra force evaluations with NoseHooverIntegrator

openmmapi/src/NoseHooverIntegrator.cpp
This fixes an error introduced by #4753.
=> Restore call to updateContextState()

wrappers/python/openmm/app/modeller.py
=> Use cell list to speed up addHydrogens()

platforms/common/src/IntegrationUtilities.cpp, platforms/reference/src/SimTKReference/ReferenceVirtualSites.cpp
=> Fixed error in checking for circular virtual site definitions

platforms/cuda/src/CudaContext.cpp, platforms/hip/src/HipContext.cpp
=> Fixed exception from re-enabling peer-to-peer access

wrappers/python/openmm/app/amberprmtopfile.py, wrappers/python/tests/TestAmberPrmtopFile.py
=> flexibleConstraints option for AmberPrmtopFile

wrappers/python/openmm/app/forcefield.py, wrappers/python/tests/TestForceField.py
Should fix #4850.  Adds a test that would have caught the issue.
=> Correctly assign CMAPs to torsions across multiple CMAPTorsionForce sections

wrappers/python/openmm/app/dcdfile.py, wrappers/python/openmm/app/dcdreporter.py, wrappers/python/openmm/app/xtcfile.py, wrappers/python/openmm/app/xtcreporter.py, wrappers/python/tests/TestDcdFile.py, wrappers/python/tests/TestXtcFile.py
Fixes https://github.com/openmm/openmm/issues/4873
=> Fixing XTC/DCD time and step writing

wrappers/python/openmm/app/modeller.py, wrappers/python/tests/TestModeller.py
=> Fixed error adding vsites that depend on other vsites

.github/workflows/CI.yml
This is an attempt to fix the CI failures on PPC.
=> Use newer docker container for PPC

docs-source/api-c++/forces.rst, docs-source/usersguide/theory/03_custom_forces.rst, openmmapi/include/openmm/CustomVolumeForce.h, openmmapi/include/openmm/internal/CustomVolumeForceImpl.h, openmmapi/src/CustomVolumeForce.cpp, openmmapi/src/CustomVolumeForceImpl.cpp, serialization/include/openmm/serialization/CustomVolumeForceProxy.h, serialization/src/CustomVolumeForceProxy.cpp, serialization/src/SerializationProxyRegistration.cpp, serialization/tests/TestSerializeCustomVolumeForce.cpp, tests/TestCustomVolumeForce.cpp
Implements #4861.  This adds a force that depends on the box volume, or on the components of the box vectors.
=> Created CustomVolumeForce

plugins/amoeba/platforms/common/src/AmoebaCommonKernels.cpp, plugins/amoeba/platforms/common/src/AmoebaCommonKernels.h, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceHippoNonbondedForce.cpp, plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp, plugins/amoeba/tests/TestAmoebaMultipoleForce.h, plugins/amoeba/tests/TestHippoNonbondedForce.h
See #4907.  This adds the same correction for AmoebaMultipoleForce and HippoNonbondedForce.
=> Neutralizing plasma self energy for AMOEBA

docs-source/usersguide/library/03_tutorials.rst
This updates a URL that had changed.  It was causing a CI failure.
=> Update a URL in the docs

.github/workflows/CI.yml
Updates bucket region for documentation upload
=> Update AWS S3 bucket region

platforms/common/src/CommonIntegrateQTBStepKernel.cpp, platforms/common/src/kernels/qtb.cc
This fixes a bug in the GPU implementation.
=> Bug fix to QTB
